const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE_KEY='fieldwork-serum-v2-notebook-1',fresh=()=>({format:'fieldwork-serum-v2',version:1,selected:'rolling-bass',bpm:128,favourites:[],built:[],recalled:[],notes:{},sessions:[]});
let state=fresh(),storageOK=true,currentView='library',labA=null;
function validateNotebook(data){
 if(!data||data.format!=='fieldwork-serum-v2'||data.version!==1)throw Error('Choose a Sound Design V2 notebook JSON.');
 const valid=new Set(PATCHES.map(p=>p.id)),result=fresh();
 for(const key of ['favourites','built','recalled']){if(!Array.isArray(data[key])||data[key].length>200||data[key].some(x=>!valid.has(x)))throw Error('Notebook contains invalid recipe marks.');result[key]=[...new Set(data[key])];}
 if(!data.notes||typeof data.notes!=='object'||Array.isArray(data.notes))throw Error('Notebook notes are invalid.');
 for(const [id,note]of Object.entries(data.notes)){if(!valid.has(id)||typeof note!=='string'||note.length>12000)throw Error('Notebook contains an invalid or oversized note.');result.notes[id]=note;}
 if(!Array.isArray(data.sessions)||data.sessions.length>40||data.sessions.some(x=>!/^w[1-8]d[1-5]$/.test(x)))throw Error('Notebook sessions are invalid.');
 result.sessions=[...new Set(data.sessions)];if(valid.has(data.selected))result.selected=data.selected;result.bpm=bound(Number(data.bpm)||128,60,200);return result;
}
try{const stored=localStorage.getItem(STORE_KEY);if(stored)state=validateNotebook(JSON.parse(stored));}catch{storageOK=false;}
let toastTimer;function toast(message){$('toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4500);}
function save(){try{localStorage.setItem(STORE_KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}updateStorage();}
function updateStorage(){if($('storageStatus'))$('storageStatus').textContent=storageOK?'Local autosave is available. A downloaded notebook is your portable backup.':'Browser storage is unavailable or could not be read. Your work stays in this tab; download a notebook to keep it.';}
function toggleMark(key,id,on){state[key]=state[key].filter(x=>x!==id);if(on)state[key].push(id);save();}
const current=()=>PATCHES.find(p=>p.id===state.selected)||PATCHES[0];
const timeLabel=ms=>ms>=1000?(ms/1000).toFixed(ms%1000?2:0)+' s':ms+' ms';
const sustainLabel=v=>v===0?'minimum / −∞ dB':v===100?'100% / 0 dB':`${v}% / ${(20*Math.log10(v/100)).toFixed(1)} dB`;
const ampText=p=>`ATK ${timeLabel(p.amp[0])} · HOLD ${timeLabel(p.amp[1])} · DEC ${timeLabel(p.amp[2])} · SUS ${sustainLabel(p.amp[3])} · REL ${timeLabel(p.amp[4])}`;
const hz=v=>v>=1000?(v/1000).toFixed(v%1000?1:0)+' kHz':v+' Hz';
const triggerText=p=>p.engine==='Noise'?`MIDI ${p.note} triggers the envelope; noise has no single stable pitch.`:p.engine==='Wavetable'?`MIDI ${p.note} (${HZ(p.note).toFixed(1)} Hz before oscillator transposition).`:`MIDI ${p.note}; the recorded source's tuning depends on its root-note mapping.`;
function filterText(p){return p.filter==='Off'?'Filter off; no filter-envelope assignment.':`${p.filter} · cutoff ${hz(p.cut)} · RES ${p.res}% · MIX 100% · DRIVE 0% initially. ${p.env&&p.peak!==p.cut?`ENV 2 opens to approximately ${hz(p.peak)}, then closes over ${timeLabel(p.env)}.`:'No filter-envelope movement.'}`;}
function stepsFor(p){
 const filter=p.filter==='Off'?'Leave Filter 1 and Filter 2 off. Route the audible source to Main so it can reach the output and any effects.':`Enable Filter 1 and choose ${p.filter}. Set cutoff ${hz(p.cut)}, RES ${p.res}%, MIX 100% and DRIVE 0% initially. Route the sources named in the source step to Filter 1; route Filter 1 to Main. ${p.env&&p.peak!==p.cut?`ENV 2: ATK ${timeLabel(p.envAttack||0)}, HOLD 0, DEC ${timeLabel(p.env)}, SUS ${p.envSustain||0}%, REL ${timeLabel(p.envRelease ?? Math.min(p.amp[4],150))}. Drag ENV 2 onto Filter 1 Cutoff. Use positive, unipolar depth: base ${hz(p.cut)}, peak about ${hz(p.peak)}. Set the depth by the target travel; the Matrix amount is not a number of Hz.`:'Leave ENV 2 unassigned to cutoff; this recipe uses a static filter.'}`;
 return [
 ['Start with an empty patch','MENU → Init Preset. Keep Filter 2, FX, ARP, CLIP, unused oscillators and bus sends off. Leave OCT/SEM at 0 unless this recipe specifies otherwise. Start with a comfortable master output.', 'Play the Serum keyboard once before editing; you should hear the Init tone.'],
 ['Choose the source',p.source, ['Wavetable','Noise'].includes(p.engine)?'You should hear a plain tone or noise before the envelope and effects make it musical.':'Audition the source at its root note before changing the envelope.'],
 ['Shape the volume','On ENV 1 set '+ampText(p)+'. Keep the normal ENV 1 amplitude control enabled. Use a long held note to hear the whole decay; then try the recipe MIDI gates.',p.amp[3]===0?'With the key held, the dry sound should fall to silence.':'With the key held, a body should remain after the decay.'],
 ['Shape the brightness',filter,p.filter==='Off'?'The source supplies the tone; the filter is not needed for this core recipe.':'Temporarily sweep cutoff to confirm the intended source really passes through this filter.'],
 ['Add the defining movement',p.movement,p.hear],
 ['Finish, perform and save',p.fx+' Map Macro 1 to '+p.macro[1]+' Name it “'+p.macro[0]+'”. Set its low and high ends by watching the destination readout. Save using the disk icon by Serum’s preset name.', 'Compare FX bypassed at similar output level, then test the patch in your track.']
 ];
}
function envelopeSVG(p,dark=false){
 const a=p.amp,s=142-(a[3]/100)*110,color=dark?'#ed8c70':'#a55c39',grid=dark?'#4b584b':'#d0d7c4';
 return `<line x1="24" y1="145" x2="530" y2="145" stroke="${grid}"/><line x1="340" y1="20" x2="340" y2="153" stroke="${grid}" stroke-dasharray="4 5"/><path d="M24 142L100 32L128 32L225 ${s}L340 ${s}L500 142" stroke="${color}" stroke-width="3" fill="none"/><path d="M24 142L100 32L128 32L225 ${s}L340 ${s}L500 142Z" fill="${color}" opacity=".08"/><g font-family="Consolas,monospace" font-size="11" fill="${dark?'#d1dbc6':'#59684a'}"><text x="28" y="177">A ${timeLabel(a[0])}</text><text x="142" y="177">D ${timeLabel(a[2])}</text><text x="266" y="177">S ${a[3]}%</text><text x="402" y="177">R ${timeLabel(a[4])}</text><text x="343" y="17">NOTE OFF</text><text x="28" y="202">HOLD ${timeLabel(a[1])} · SCHEMATIC, NOT TO TIME SCALE</text></g>`;
}
function filteredPatches(){const q=$('search').value.trim().toLowerCase(),family=$('family').value,level=$('level').value;return PATCHES.filter(p=>(!family||p.family===family)&&(!level||p.level===+level)&&(!$('onlySaved').checked||state.favourites.includes(p.id))&&(!q||[p.name,p.family,p.styles,p.description,p.source,p.why,p.level===1?'beginner foundation easy':'',p.engine,...p.variants].join(' ').toLowerCase().includes(q)));}
function renderList(){const found=filteredPatches();$('resultCount').textContent=`${found.length} / ${PATCHES.length} RECIPES`;let last='';$('patchList').innerHTML=found.length?found.map(p=>{const group=p.family!==last?`<div class="patch-group">${esc(p.family)}</div>`:'';last=p.family;return group+`<button class="patch-button ${p.id===state.selected?'active':''}" data-patch="${p.id}" aria-pressed="${p.id===state.selected}"><span class="num">${String(PATCHES.indexOf(p)+1).padStart(2,'0')}</span><span>${esc(p.name)}<small>Level ${p.level} · ${esc(p.engine)}</small></span><span class="saved" aria-label="${state.favourites.includes(p.id)?'Favourite':state.recalled.includes(p.id)?'Recalled':''}">${state.favourites.includes(p.id)?'★':state.recalled.includes(p.id)?'✓':''}</span></button>`;}).join(''):'<div class="empty">No sounds match. Try a broader word or clear the filters.<br><button id="clearFilters" style="margin-top:12px">Clear filters</button></div>';}
function renderRecipe(){const p=current(),index=PATCHES.indexOf(p),events=patternFor(p),available=['Wavetable','Noise'].includes(p.engine);
 $('recipe').innerHTML=`<div class="recipe-head"><div class="recipe-top"><p class="eyebrow" style="margin:0">RECIPE ${String(index+1).padStart(2,'0')} / ${esc(p.family.toUpperCase())}</p><span class="badge">LEVEL ${p.level} · ${['','FOUNDATIONS','CHARACTER','EXPLORATION'][p.level]}</span></div><h2>${esc(p.name)}</h2><p class="description">${esc(p.description)}</p><p class="tagline">${esc(p.styles)} / ${esc(p.engine)}</p><div class="recipe-tools"><button id="favourite" aria-pressed="${state.favourites.includes(p.id)}">${state.favourites.includes(p.id)?'★ Saved':'☆ Favourite'}</button><button id="printRecipe">Print this recipe</button><button id="downloadRecipe">Download recipe (.md)</button><button id="downloadMidi">↓ Test MIDI</button><button id="copyLink">Copy recipe link</button></div></div>
 <div class="core"><p class="eyebrow">WHY IT<br>WORKS</p><p>${esc(p.why)}</p></div><div class="recipe-body">
 <div class="listen-box"><div class="tempo-row"><label>Tempo<input id="recipeBpm" type="number" min="60" max="200" value="${state.bpm}"></label><p class="small"><b>${available?'Hear the core idea':'Build with your source audio'}</b><br>${available?'Simplified browser synthesis; not a Serum patch recording. Glide, exact filters, warps and full FX chains are not reproduced.':'This recipe depends on a recording or factory instrument. Use its steps in Serum; no substitute preview is presented.'}</p></div><div class="button-row">${available?'<button id="preview" class="play-btn">▶ Core sketch</button><button id="rawPreview">▶ Raw source</button><button id="stopPreview">Stop</button>':''}<span id="playStatus" class="small" aria-live="polite">${available?'One pass; starts only when pressed.':'Test MIDI is available above.'}</span></div><div class="pattern-strip" aria-label="First-bar note onset map">${Array.from({length:16},(_,i)=>`<span class="beat ${events.some(e=>Math.floor(e.step)===i)?'hit':''}">${i%4===0?i/4+1:'·'}</span>`).join('')}</div><div>First bar · 16 columns = sixteenth notes · filled = note starts · MIDI includes ${p.pattern==='rise'?'four':'two'} bars</div><p class="small" style="margin-top:10px"><b>First trigger:</b> ${esc(triggerText(p))} ${['chords','sparse-chords','pad'].includes(p.pattern)?'MIDI contains a chord; use a polyphonic patch.':'MIDI contains single-note events.'} Drag the .mid file onto your Serum track; keep Serum’s ARP and CLIP off. Note names may use different octave numbers across DAWs.</p></div>
 <h3>The settings at a glance</h3><div class="table-wrap"><table class="settings-table"><thead><tr><th>WHERE</th><th>START HERE</th></tr></thead><tbody><tr><td>Source</td><td>${esc(p.source)}</td></tr><tr><td>ENV 1 / volume</td><td>${esc(ampText(p))}</td></tr><tr><td>Filter 1 / tone</td><td>${esc(filterText(p))}</td></tr><tr><td>Performance control</td><td>${esc(p.macro[0])}: ${esc(p.macro[1])}</td></tr></tbody></table></div><svg class="envelope-diagram" viewBox="0 0 560 215" role="img" aria-label="Schematic amplitude envelope: ${esc(ampText(p))}">${envelopeSVG(p)}</svg>
 <h3>Build it in Serum 2</h3><p class="small" style="margin-bottom:18px">Work down the list. Listen after each stage. <button class="text-button" data-view="start">First time? Read the setup and modulation walkthrough →</button></p><ol class="steps">${stepsFor(p).map(([title,body,check])=>`<li><h4>${esc(title)}</h4><p>${esc(body)}</p><p class="step-check">↳ Listen / check: ${esc(check)}</p></li>`).join('')}</ol>
 <h3>Know when you have it.</h3><div class="two-col"><div class="callout green"><h4>You should hear</h4><p>${esc(p.hear)}</p></div><div class="callout"><h4>If it is not there yet</h4><p>${esc(p.fix)}</p><button class="text-button" data-view="fix">Open the diagnosis guide →</button></div></div>
 <h3>Make two new versions.</h3><ol>${p.variants.map(v=>`<li>${esc(v)}</li>`).join('')}</ol><p class="small">Save separate versions. Predict the change before you touch the knob, then write what you actually heard.</p><h3>Give it a place in the track.</h3><p>${esc(p.mix)}</p><div class="callout green" style="margin-top:20px"><h4>Close the guide. Try this.</h4><p>${esc(p.challenge)}</p></div>
 <div class="note-area"><p class="eyebrow">YOUR LAB NOTES / SAVED LOCALLY WHEN AVAILABLE</p><div class="button-row"><label class="inline"><input id="built" type="checkbox" ${state.built.includes(p.id)?'checked':''}> I built it in Serum</label><label class="inline"><input id="recalled" type="checkbox" ${state.recalled.includes(p.id)?'checked':''}> I rebuilt it from memory</label></div><label for="recipeNote">What changed, what you heard, and the preset name you saved</label><textarea id="recipeNote" maxlength="12000" placeholder="Example: ENV 2 decay 110 → 70 ms. Less bark, better gap before the kick. Saved BS_Roll_Tight_v02.">${esc(state.notes[p.id]||'')}</textarea><p class="small">These notes do not change Serum. <button class="text-button" data-view="practice">Back up your notebook →</button></p></div><div class="recipe-pagination"><button data-patch="${PATCHES[(index-1+PATCHES.length)%PATCHES.length].id}">← Previous recipe</button><button data-patch="${PATCHES[(index+1)%PATCHES.length].id}">Next recipe →</button></div></div>`;
 $('favourite').onclick=()=>{toggleMark('favourites',p.id,!state.favourites.includes(p.id));renderList();$('favourite').setAttribute('aria-pressed',state.favourites.includes(p.id));$('favourite').textContent=state.favourites.includes(p.id)?'★ Saved':'☆ Favourite';};
 $('recipeBpm').onchange=e=>{state.bpm=bound(Number(e.target.value)||128,60,200);e.target.value=state.bpm;AudioSketch.stop();save();};
 $('built').onchange=e=>toggleMark('built',p.id,e.target.checked);$('recalled').onchange=e=>{toggleMark('recalled',p.id,e.target.checked);renderList();};
 $('recipeNote').oninput=e=>{state.notes[p.id]=e.target.value;save();};
 $('downloadMidi').onclick=()=>{download(`${p.id}-${state.bpm}bpm.mid`,midiBytes(p,state.bpm),'audio/midi');toast('Test MIDI downloaded. Load your Serum patch separately.');};
 $('downloadRecipe').onclick=()=>download(p.id+'-serum-2.md',recipeMarkdown(p),'text/markdown');
 $('printRecipe').onclick=()=>window.print();$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Recipe link copied. Keep the HTML file at the same location.');}catch{toast('Copy the address from your browser; it includes this recipe’s bookmark.');}};
 if(p.id==='rumble'){$('recipe').querySelector('.recipe-body').insertAdjacentHTML('afterbegin','<div class="callout green" style="margin-bottom:20px"><b>Explore eight rumble characters.</b> Learn the complete DAW chain, from tight rolling tails to reverse swells.<br><button class="text-button" data-view="rumble">Open Techno rumbles →</button></div>');}
 if(available){$('preview').onclick=()=>playPreview(false);$('rawPreview').onclick=()=>playPreview(true);$('stopPreview').onclick=()=>AudioSketch.stop();}
}
async function playPreview(raw){try{await AudioSketch.play(current(),state.bpm,{raw});if(AudioSketch.current)$('playStatus').textContent=raw?'Playing a simplified unshaped source…':'Playing the core sketch…';}catch(error){toast('Audio could not start. Check your browser audio permissions.');console.error(error);}}
AudioSketch.onStop=()=>{if($('playStatus'))$('playStatus').textContent='Stopped. Press a preview to listen.';};
function setView(view,{scroll=true,hash=true}={}){if(!$('view-'+view))view='library';AudioSketch.stop();currentView=view;document.body.dataset.printView=view;document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!=='view-'+view);document.querySelectorAll('.section-nav [data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));if(view==='practice')renderPractice();if(hash)history.replaceState(null,'',view==='library'?'#recipe/'+state.selected:view==='rumble'?'#rumble/'+selectedRumble:'#'+view);if(scroll)$('view-'+view).scrollIntoView({block:'start',behavior:'auto'});}
function selectPatch(id,{scroll=true}={}){if(!PATCHES.some(p=>p.id===id))return;AudioSketch.stop();state.selected=id;save();renderList();renderRecipe();setView('library',{scroll:false});if(scroll)$('recipe').scrollIntoView({block:'start',behavior:'auto'});}
document.addEventListener('click',e=>{const patch=e.target.closest('[data-patch]'),view=e.target.closest('[data-view]');if(patch){e.preventDefault();selectPatch(patch.dataset.patch);}else if(view){e.preventDefault();setView(view.dataset.view);}else if(e.target.closest('#clearFilters')){$('search').value='';$('family').value='';$('level').value='';$('onlySaved').checked=false;renderList();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')AudioSketch.stop();if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){e.preventDefault();setView('library');$('search').focus();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)AudioSketch.stop();});window.addEventListener('pagehide',()=>AudioSketch.stop());
function routeHash(){const hash=decodeURIComponent(location.hash.slice(1));if(hash.startsWith('recipe/')&&PATCHES.some(p=>p.id===hash.slice(7)))selectPatch(hash.slice(7),{scroll:false});else if(hash.startsWith('rumble/')){renderRumble(hash.slice(7));setView('rumble',{scroll:false,hash:false});}else if($('view-'+hash))setView(hash,{scroll:false,hash:false});}
window.addEventListener('hashchange',routeHash);
function download(name,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function recipeMarkdown(p){return `# ${p.name} — Serum 2\n\nSound Design V2 · ${p.family} · Level ${p.level} · ${p.engine}\n\n${p.styles}\n\n${p.description}\n\n## Why it works\n\n${p.why}\n\n## Setup\n\nStart from MENU → Init Preset. Unmentioned settings stay at Init. OCT/SEM 0 unless specified. Basic waves: Analog → Basic Shapes; select by the waveform picture, not an assumed frame number. Leave ARP/CLIP off. Modulation ranges are approximate target endpoints. Sustain percentages describe linear level; for ENV 1 use the dB equivalent shown.\n\n## Starting settings\n\n- Source: ${p.source}\n- ENV 1: ${ampText(p)}\n- Filter: ${filterText(p)}\n- MIDI first trigger: ${triggerText(p)}\n- Test tempo: ${state.bpm} BPM. Download test MIDI separately from the HTML guide.\n\n## Build it\n\n${stepsFor(p).map(([t,b,c],i)=>`${i+1}. **${t}.** ${b}\n\n   Listen / check: ${c}`).join('\n\n')}\n\n## Listening checkpoint\n\n${p.hear}\n\n## If it sounds wrong\n\n${p.fix}\n\n## Variations\n\n${p.variants.map(x=>'- '+x).join('\n')}\n\n## In the track\n\n${p.mix}\n\n## Recall challenge\n\n${p.challenge}\n\n## Scope\n\nOriginal starting-point recipe, not a factory preset or a patch auditioned in Serum for this release. Browser audio is a simplified sketch; sample-based recipes depend on your selected source. Official control reference: https://xferrecords.com/manual/serum-2/docs\n`;}
function plainText(el){const copy=el.cloneNode(true);copy.querySelectorAll('button,input,select,svg,.lab-controls').forEach(x=>x.remove());if(el.id==='view-start'){const map=copy.querySelector('#mapDetail');if(map)map.textContent=Object.values(MAP).join('\n\n');}copy.querySelectorAll('br').forEach(x=>x.replaceWith(document.createTextNode('\n')));copy.querySelectorAll('a').forEach(x=>x.replaceWith(document.createTextNode(`[${x.textContent}](${x.getAttribute('href')})`)));copy.querySelectorAll('h2,h3,h4').forEach(x=>x.prepend(document.createTextNode('\n'+(x.tagName==='H2'?'## ':x.tagName==='H3'?'### ':'#### '))));copy.querySelectorAll('li').forEach(x=>{x.prepend(document.createTextNode('\n- '));x.append(document.createTextNode('\n'));});copy.querySelectorAll('h2,h3,h4,p,div,ol,ul').forEach(x=>x.append(document.createTextNode('\n\n')));return copy.textContent.replace(/[ \t]+/g,' ').replace(/\n\s*\n\s*\n/g,'\n\n').trim();}
function handbookMarkdown(){return '# Sound Design 02 — Make the sound in Serum 2\n\n48 original house and techno recipes plus eight rumble studies, a beginner workflow, dictionary and eight-week practice plan.\n\n## Start here\n\n'+plainText($('view-start'))+'\n\n## Hear & learn\n\n'+plainText($('view-lab'))+'\n\n---\n\n'+PATCHES.map(recipeMarkdown).join('\n\n---\n\n')+'\n\n'+rumbleMarkdown()+'\n\n# Diagnosis\n\n'+DIAGNOSES.map(([a,b,c])=>`## ${a}\n\n${b}\n\n${c}`).join('\n\n')+'\n\n# Eight-week practice\n\n'+WEEKS.map((w,i)=>`## Week ${i+1}: ${w.name}\n\n${w.focus}\n\n${w.days.map((d,j)=>`${j+1}. ${d}`).join('\n')}\n\nPass check: ${w.pass}`).join('\n\n')+'\n\n# Dictionary\n\n'+TERMS.map(([a,b,c])=>`## ${a}\n\n${b}\n\nWhere: ${c}`).join('\n\n')+'\n\n# Sources and scope\n\n'+plainText($('view-sources'))+'\n\n'+[...$('view-sources').querySelectorAll('a')].map(a=>`- [${a.textContent}](${a.href})`).join('\n')+'\n';}
function renderPractice(){$('weeks').innerHTML=WEEKS.map((w,i)=>`<article class="week panel"><p class="eyebrow">WEEK ${String(i+1).padStart(2,'0')}</p><h3>${esc(w.name)}</h3><p>${esc(w.focus)}</p><div>${w.ids.map(id=>`<a href="#recipe/${id}" data-patch="${id}">${esc(PATCHES.find(p=>p.id===id).name)} ↗</a>`).join('')}</div>${w.days.map((day,j)=>{const id=`w${i+1}d${j+1}`;return `<label class="inline"><input type="checkbox" data-session="${id}" ${state.sessions.includes(id)?'checked':''}><span><b>Day ${j+1}.</b> ${esc(day)}</span></label>`;}).join('')}<div class="pass"><b>Ready to move on when:</b> ${esc(w.pass)}</div></article>`).join('');updateProgress();}
function updateProgress(){$('progressText').textContent=`${state.sessions.length} / 40 SESSIONS · ${state.built.length} BUILT · ${state.recalled.length} RECALLED`;$('courseProgress').value=state.sessions.length;updateStorage();}
$('weeks').addEventListener('change',e=>{if(e.target.dataset.session){toggleMark('sessions',e.target.dataset.session,e.target.checked);updateProgress();}});
$('exportJournal').onclick=()=>download('sound-design-notebook.json',JSON.stringify(state,null,2),'application/json');
$('importJournal').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('Notebook must be smaller than 1 MB.');const incoming=validateNotebook(JSON.parse(await file.text()));for(const key of ['favourites','built','recalled','sessions'])state[key]=[...new Set([...state[key],...incoming[key]])];for(const [id,note]of Object.entries(incoming.notes)){if(!state.notes[id])state.notes[id]=note;else if(note&&!state.notes[id].includes(note)){const merged=state.notes[id]+'\n\n[Imported notebook]\n'+note;if(merged.length<=12000)state.notes[id]=merged;else toast('A long note was kept unchanged; the imported copy remains in your file.');}}save();renderList();renderRecipe();renderPractice();toast('Notebook merged. Existing notes and marks were kept.');}catch(error){toast(error.message);}finally{e.target.value='';}};
$('exportHandbook').onclick=()=>download('Serum-2-Sound-Design-Handbook.md',handbookMarkdown(),'text/markdown');
$('downloadRumbles').onclick=()=>download('Techno-Rumbles-Eight-Studies.md',rumbleMarkdown(),'text/markdown');
$('printRumble').onclick=()=>window.print();
$('rumbleChoices').onclick=e=>{const b=e.target.closest('[data-rumble]');if(!b)return;renderRumble(b.dataset.rumble);history.replaceState(null,'','#rumble/'+selectedRumble);$('rumbleRecipe').scrollIntoView({block:'start',behavior:'auto'});};
$('rumbleBpm').onchange=updateRumbleTiming;$('rumbleGap').oninput=updateRumbleTiming;$('rumbleRise').oninput=updateRumbleTiming;
function renderDictionary(){const q=$('termSearch').value.trim().toLowerCase(),found=TERMS.filter(t=>t.join(' ').toLowerCase().includes(q));$('dictionary').innerHTML=found.length?found.map(([term,meaning,where])=>`<article class="term panel"><h3>${esc(term)}</h3><p>${esc(meaning)}</p><p class="where">WHERE / ${esc(where)}</p></article>`).join(''):'<p class="empty">No matching term. Try a shorter word.</p>';}
$('termSearch').oninput=renderDictionary;
$('diagnoses').innerHTML=DIAGNOSES.map(([title,cause,check])=>`<details><summary>${esc(title)}</summary><div><p>${esc(cause)}</p><div class="callout green" style="margin-top:15px">${esc(check)}</div></div></details>`).join('');
function timing(){const bpm=bound(+$('timingBpm').value||128,60,200),q=60000/bpm;$('timingBpm').value=bpm;$('timingResult').textContent=`1/4: ${Math.round(q)} ms · 1/8: ${Math.round(q/2)} ms · 1/16: ${Math.round(q/4)} ms · dotted 1/8: ${Math.round(q*.75)} ms · 1/8 triplet: ${Math.round(q/3)} ms`;}$('timingBpm').onchange=timing;
$('signalMap').onclick=e=>{const b=e.target.closest('[data-map]');if(!b)return;$('signalMap').querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});$('mapDetail').textContent=MAP[b.dataset.map];};$('mapDetail').textContent=MAP.source;$('signalMap').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.map==='source'));
const labIds=['Attack','Decay','Sustain','Release','Cutoff','Opening'];
function labValues(){return labIds.map(id=>+$('lab'+id).value);}
function updateLab(){const [a,d,s,r,c,o]=labValues();for(let i=0;i<labIds.length;i++)$(labIds[i].toLowerCase()+'Value').textContent=i===2?s+'%':i===4?hz(c):i===5?o+' oct':timeLabel([a,d,s,r,c,o][i]);$('labEnvelope').innerHTML=envelopeSVG({amp:[a,0,d,s,r]},true);}
async function playLab(values){const [a,d,s,r,c,o]=values;try{await AudioSketch.play({wave:'sawtooth',voices:1,amp:[a,0,d,s,r],filter:'MG Low 24',cut:c,peak:Math.min(16000,c*2**o),res:10,env:Math.min(d,650),fx:'',note:57},120,{events:[{step:0,note:57,len:16,vel:90}]});}catch(error){toast('Audio could not start in this browser.');console.error(error);}}
labIds.forEach(id=>$('lab'+id).oninput=updateLab);$('labPlay').onclick=()=>playLab(labValues());$('labStop').onclick=()=>AudioSketch.stop();$('labReset').onclick=()=>{AudioSketch.stop();[3,350,0,100,650,2.5].forEach((v,i)=>$('lab'+labIds[i]).value=v);updateLab();};$('labStore').onclick=()=>{labA=labValues();$('labCompare').disabled=false;toast('A stored. Change one setting and compare.');};$('labCompare').onclick=()=>labA&&playLab(labA);
for(const family of [...new Set(PATCHES.map(p=>p.family))])$('family').add(new Option(family,family));
for(const id of ['search','family','level','onlySaved'])$(id).addEventListener(id==='search'?'input':'change',renderList);
renderList();renderRecipe();renderPractice();renderDictionary();renderRumble();updateRumbleTiming();updateLab();timing();updateStorage();routeHash();
