(async()=>{
 const results=[],errors=[],audioStats=[];const assert=(ok,text)=>{if(!ok)throw Error(text);results.push(text);};
 window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
 try{
  assert(PATCHES.length===48,'48 distinct recipes load');assert(document.querySelectorAll('.patch-button').length===48,'All recipes discoverable');
  assert(!document.querySelector('script[src],link[rel="stylesheet"]'),'Standalone file has no external runtime resources');
  assert(TERMS.length>=50,'Dictionary includes at least 50 terms');assert(WEEKS.length===8&&WEEKS.every(w=>w.days.length===5),'40 daily practice sessions');
  for(const p of PATCHES){selectPatch(p.id,{scroll:false});assert($('recipe').querySelector('h2').textContent===p.name&&$('recipe').querySelectorAll('.steps>li').length===6,p.id+': recipe and six steps render');assert(p.variants.length>=2&&p.hear&&p.fix&&p.challenge,p.id+': teaching fields present');const notes=patternFor(p);assert(notes.length>0&&notes.every(e=>e.note>=0&&e.note<=127&&e.len>0&&e.step>=0&&e.vel>0&&e.vel<128),p.id+': valid MIDI events');const m=midiBytes(p,128);assert(String.fromCharCode(...m.slice(0,4))==='MThd'&&String.fromCharCode(...m.slice(14,18))==='MTrk',p.id+': SMF header');let pos=22,ticks=0,active=new Map(),count=0;while(pos<m.length){let delta=0,v;do{v=m[pos++];delta=(delta<<7)|(v&127);}while(v&128);ticks+=delta;const status=m[pos++];if(status===255){const type=m[pos++],len=m[pos++];pos+=len;if(type===47)break;}else{const n=m[pos++],v=m[pos++];if(status===144){active.set(n,(active.get(n)||0)+1);count++;}else if(status===128){assert(active.get(n)>0,p.id+': note-off follows note-on');active.set(n,active.get(n)-1);}else throw Error('Unexpected MIDI event');}}assert(count===notes.length&&[...active.values()].every(v=>v===0)&&ticks===(p.pattern==='rise'?7680:3840),p.id+': MIDI notes and loop length round-trip');}
  assert(patternFor(PATCHES.find(p=>p.id==='spectral-freeze')).length===1,'Recorded spectral chord is triggered by one note');
  $('search').value='acid';$('search').dispatchEvent(new Event('input'));assert(document.querySelectorAll('.patch-button').length>0&&document.querySelectorAll('.patch-button').length<48,'Search narrows the library');
  $('family').value='Pads';$('family').dispatchEvent(new Event('change'));assert(document.querySelectorAll('.patch-button').length===0,'Search and family combine');$('clearFilters').click();
  $('level').value='1';$('level').dispatchEvent(new Event('change'));assert([...document.querySelectorAll('.patch-button')].every(b=>PATCHES.find(p=>p.id===b.dataset.patch).level===1),'Beginner filter');$('level').value='';renderList();
  selectPatch('rolling-bass',{scroll:false});$('favourite').click();$('onlySaved').checked=true;renderList();assert(document.querySelectorAll('.patch-button').length===1,'Favourite-only filter');$('onlySaved').checked=false;renderList();
  $('recipeNote').value='Test <script> must stay plain text';$('recipeNote').dispatchEvent(new Event('input'));$('built').click();$('recalled').click();selectPatch('round-sub',{scroll:false});selectPatch('rolling-bass',{scroll:false});assert($('recipeNote').value.includes('<script>')&&$('built').checked&&$('recalled').checked,'Notes and progress survive recipe navigation safely');
  assert(validateNotebook(JSON.parse(localStorage.getItem(STORE_KEY))).notes['rolling-bass'].includes('<script>'),'Notebook serializes and validates');let rejected=false;try{validateNotebook({format:'wrong'});}catch{rejected=true;}assert(rejected,'Invalid notebook rejected');
  setView('practice',{scroll:false});const day=document.querySelector('[data-session="w1d1"]');day.click();assert(state.sessions.includes('w1d1')&&$('courseProgress').value===1,'Practice progress updates');
  const file=new File([JSON.stringify({...fresh(),favourites:['fm-bell'],notes:{'rolling-bass':'Imported learning note'}})],'notebook.json',{type:'application/json'}),dt=new DataTransfer();dt.items.add(file);$('importJournal').files=dt.files;await $('importJournal').onchange({target:$('importJournal')});assert(state.favourites.includes('fm-bell')&&state.notes['rolling-bass'].includes('Imported learning note')&&state.notes['rolling-bass'].includes('<script>'),'Import merges and preserves existing notes');
  setView('glossary',{scroll:false});$('termSearch').value='portamento';$('termSearch').dispatchEvent(new Event('input'));assert(document.querySelectorAll('.term').length===1,'Dictionary search');
  for(const view of ['library','start','lab','fix','practice','glossary','rumble','sources']){setView(view,{scroll:false});assert(!$('view-'+view).hidden&&[...document.querySelectorAll('.view')].filter(e=>!e.hidden).length===1,view+': navigation selects one section');assert(document.documentElement.scrollWidth<=window.innerWidth+1,view+': no page horizontal overflow');}
  setView('rumble',{scroll:false});assert(RUMBLES.length===8&&new Set(RUMBLES.map(r=>r.id)).size===8,'Eight distinct rumble methods');
  for(const r of RUMBLES){document.querySelector(`[data-rumble="${r.id}"]`).click();assert($('rumbleRecipe').querySelector('h3').textContent===r.name&&$('rumbleRecipe').querySelectorAll('ol li').length===4,r.id+': rumble selector opens the full build');assert(document.documentElement.scrollWidth<=innerWidth+1,r.id+': rumble fits the viewport');}
  history.replaceState(null,'','#rumble/cavern');routeHash();assert(selectedRumble==='cavern'&&!$('view-rumble').hidden,'Rumble deep link restores selected study');
  $('rumbleBpm').value=120;$('rumbleBpm').dispatchEvent(new Event('change'));assert($('rumbleTimingReadout').textContent.includes('beat 500 ms')&&$('rumbleTimingReadout').textContent.includes('dotted 1/8 375 ms'),'Rumble timings track BPM');
  $('rumbleGap').value=30;$('rumbleGap').dispatchEvent(new Event('input'));assert($('rumbleGapValue').textContent.includes('150 ms')&&rumbleTimes(120,30,40).rise===200,'Rumble gap and fade-up use fractions of the beat');
  assert(document.body.dataset.printView==='rumble','Print state identifies the rumble section');
  const rumbleMD=rumbleMarkdown();assert(RUMBLES.every(r=>rumbleMD.includes('## '+r.name))&&rumbleMD.includes('Post FX')&&rumbleMD.includes('Render it'),'Rumble export includes all eight methods, routing and rendering');
  setView('lab',{scroll:false});$('labStore').click();$('labAttack').value=650;updateLab();assert(!$('labCompare').disabled&&labA[0]===3&&labValues()[0]===650,'A/B preserves stored settings');
  const env=envelopePoints([2,0,100,0,1600],2);assert(env[env.length-2][1]===0,'Release from an already silent envelope remains silent');
  for(const p of PATCHES.filter(p=>['Wavetable','Noise'].includes(p.engine))){const rate=16000,events=patternFor(p),duration=Math.max(...events.map(e=>(e.step+e.len)*60/128/4))+p.amp[4]/1000+1.8,ctx=new OfflineAudioContext(1,Math.ceil(duration*rate),rate);soundGraph(ctx,ctx.destination,p,events,128,.01);const rendered=await ctx.startRendering(),data=rendered.getChannelData(0);let peak=0,sum=0;for(const x of data){if(!Number.isFinite(x))throw Error(p.id+' non-finite audio');peak=Math.max(peak,Math.abs(x));sum+=x*x;}const rms=Math.sqrt(sum/data.length);if(peak<=.0001||peak>=1||rms<=.00001)throw Error(p.id+' silent or clipped audio: '+peak);audioStats.push({id:p.id,peak:+peak.toFixed(4),rms:+rms.toFixed(4)});}
  assert(audioStats.length===42,'42 synthesized sketches render finite, non-silent, non-clipped audio');
  const rawHat=new OfflineAudioContext(1,16000,16000);soundGraph(rawHat,rawHat.destination,PATCHES.find(p=>p.id==='closed-hat'),[{step:0,note:60,len:2,vel:90}],128,.01,true);const rawData=(await rawHat.startRendering()).getChannelData(0);assert(rawData.some(v=>Math.abs(v)>.005),'Raw noise preview remains audible without its recipe high-pass');
  await playLab([3,350,0,100,650,2.5]);assert(!!AudioSketch.current,'Live audio starts from UI path');AudioSketch.stop();assert(AudioSketch.current===null,'Stop clears active playback');
  const md=handbookMarkdown();assert(PATCHES.every(p=>md.includes('# '+p.name+' — Serum 2'))&&md.includes('Eight-week practice')&&md.includes('Dictionary')&&RUMBLES.every(r=>md.includes('## '+r.name)),'Full handbook contains all recipes, rumble studies and learning material');await fetch('/handbook',{method:'POST',body:md});
  state=fresh();save();selectPatch('rolling-bass',{scroll:false});$('search').value='';$('family').value='';$('level').value='';$('onlySaved').checked=false;renderList();
 }catch(error){errors.push(error.stack||String(error));}
 await fetch('/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:errors.length?'failed':'passed',viewport:window.innerWidth,assertions:results.length,results,audioStats,errors})});
})();
