'use strict';
(() => {
 const $=id=>document.getElementById(id),F=V3,roles=['melody','bass','chords','arp','drums'],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const roleNames={melody:'Melody',bass:'Bass',chords:'Chords',arp:'Arp',drums:'Drums'};
 const approaches={hook:['A hook, not a chase.','The melody has a small vocabulary, a clear contour and somewhere to breathe. Repeating the same pitches over new chords lets their colour change.'],rave:['Say it again.','Repeated attacks build recognition. A longer landing gives the short notes a destination. Try the same idea as a dry pluck and a broad lead.'],hypnotic:['Small moves. Deep pull.','The anchor returns again and again. Listen for the little interval, the missing hit and the accents that keep a narrow motif alive.'],percussion:['The rhythm is the hook.','Pitched attacks work like another drum. Leave space for the bass to answer and let the quieter notes connect the strong accents.'],cinematic:['Give the notes air.','A phrase can carry emotion through its contour and its pauses. Keep the hook while the harmony changes, then compare a different landing.'],rolling:['An anchor in motion.','A recurring pitch holds the sequence together. Small deviations and accent groups add movement without rebuilding the line every bar.'],broken:['Catch the space between.','The motif crosses a broken beat. Its familiar opening gives you something to recognise as the drums and bass answer around it.'],disco:['A little lift in the pocket.','Repeated pitches, offbeat attacks and short connecting notes form a rhythmic conversation with the bass.'],stab:['Hit it. Leave it.','Short stabs on the offbeat do the work of a whole riff. The silence after each hit is part of the hook, so keep the notes clipped.'],piano:['Rock between the chords.','A house riff lives in its syncopation. Hear how the 3-3-2 pocket rocks back and forth while a few notes jump to brighter chord tones.'],vocal:['Chop it. Answer it.','Quick repeated syllables build the call; one longer note answers. Try the line on a vocal-colour sound, then on a pluck.'],sequence:['Let the pattern turn.','A chord-tone arpeggio cycles through the bars. One changed note, or an octave jump, is enough to give the sequence a new emotion.'],acid:['Accent, slide, octave.','A narrow line becomes alive through accents, legato slides and sudden octave jumps. Set glide on your mono synth in Live and ride the filter.'],jack:['Make the low end sing.','The riff sits in the bass register and swings. Leave space for the kick and let a single octave jump provide the hook.']};
 const exercises={hook:'Choose one sound. Loop the phrase. Change only the last two beats, then hear what you miss when you remove them.',rave:'Duplicate the lead. Put one copy on a dry pluck and one on a wide saw, and automate the crossfade into the drop.',hypnotic:'Loop eight bars. Automate only filter and delay feedback for a minute. Resist adding notes.',percussion:'Put the melody on a pitched percussion sound, then pan it slightly away from the hats.',cinematic:'Stretch the last note to a full bar and add a long reverb only to that note.',rolling:'Mute one note in the sequence every four bars. Listen for how much tension the missing note creates.',broken:'Keep the motif and try three different drum patterns under it. Choose the one where the hook breathes most.',disco:'Double the bass an octave up with a short pluck, then filter it in during the build.',stab:'Resample the stab to audio, then reverse the tail of every fourth hit.',piano:'Voice the chords a little lower, then lift only the top note of the riff by an octave in the chorus section.',vocal:'Try the line on a vocal chop sampler with formant shift, then repitch one syllable per bar.',sequence:'Automate a slow filter opening over sixteen bars and keep the notes unchanged.',acid:'Set glide to about 60 ms, map accent to filter envelope, and slowly open resonance over the phrase.',jack:'Sidechain the riff to the kick, then add a short octave-up copy only in the second half of the phrase.'};
 let S={version:3,c:F.config(),motif:[],mix:{},view:'motif',listen:'groove',shelf:[]},history=[],future=[],variants=[],variantRound=0,selected=null,rollGeometry=null,drag=null,toastTimer,imported=null,familyFilter='All';
 let ac=null,engine=null,playing=false,clockTimer=null,frame=null,playStart=0,scheduled=0,playNotes=[],playBeats=8,audition=-1,playRequest=0;
 const fold=s=>String(s).normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase(),familyOf=artist=>F.getStyle(artist.style).family;
 function initialMix(style,artist=''){const s=F.getStyle(style),a=F.getArtist(artist);return Object.fromEntries(roles.map(role=>[role,{sound:role==='melody'?a?.sound||s.sound:role==='bass'?s.bassSound||(s.kind==='rolling'?'psy-bass':s.id==='amapiano'?'log-drum':'round-saw'):role==='chords'?s.chordSound||'warm-pad':role==='arp'?'glass-pluck':s.kit||(['garage'].includes(s.id)?'uk-garage':['breaks','dnb','electro'].includes(s.id)?'break-machine':s.id==='hardtech'?'hard-909':'club-909'),enabled:!['arp','chords'].includes(role),solo:false,mix:{level:role==='melody'?85:role==='bass'?68:role==='drums'?65:42,tone:0,space:role==='melody'?10:0,pan:0}}]));}
 S.motif=F.melody(S.c);S.mix=initialMix(S.c.style);
 const snapshot=()=>F.copy(S);
 function toast(msg){$('toast').textContent=msg;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4000);}
 function checkpoint(){history.push(snapshot());if(history.length>60)history.shift();future=[];}
 function change(fn,msg,makeVariants=true){const resume=playing;stop();checkpoint();fn();selected=null;if(makeVariants)refreshVariants();render();if(msg)$('changeNote').textContent=msg;if(resume)start();}
 function newProtected(){const fixed=S.motif.filter(n=>n.locked);if(!fixed.length)return F.melody(S.c);const generated=F.melody(S.c).map(n=>({...n,id:'s'+S.c.seed+n.id})).filter(n=>!fixed.some(f=>n.t<f.t+f.d&&n.t+n.d>f.t));return F.clean([...generated,...F.copy(fixed)]);}
 function refreshVariants(){variantRound++;variants=['rhythm','pitch','ending'].map((kind,i)=>({kind,notes:F.mutate(S.motif,S.c,kind,S.c.seed+variantRound*2377+i*7919)}));}
 function options(items,value){return items.map(([id,label])=>`<option value="${esc(id)}" ${String(id)===String(value)?'selected':''}>${esc(label)}</option>`).join('');}
 function chordName(d){const p=F.degree(d,S.c.mode),third=F.degree(d+2,S.c.mode)-p,fifth=F.degree(d+4,S.c.mode)-p;return NOTE_NAMES[((S.c.root+p)%12+12)%12]+(third===3?(fifth===6?'°':'m'):fifth===8?'+':'');}
 function renderStyles(){
  const q=fold($('search').value);let family='';
  // Rows are appended for stable seeds; display groups them by family.
  const matched=F.D.styles.filter(s=>(familyFilter==='All'||s.family===familyFilter)&&fold([s.name,s.refs,s.family,s.lesson,...F.D.artists.filter(a=>a.style===s.id).map(a=>a.name)].join(' ')).includes(q)).sort((a,b)=>F.D.families.indexOf(a.family)-F.D.families.indexOf(b.family));
  $('familyFilter').innerHTML=['All',...F.D.families].map(f=>`<button class="${f===familyFilter?'active':''}" data-family="${esc(f)}" aria-pressed="${f===familyFilter}">${esc(f)}<small>${f==='All'?F.D.styles.length:F.D.styles.filter(s=>s.family===f).length}</small></button>`).join('');
  $('styleList').innerHTML=matched.map(s=>{let heading=s.family!==family?`<div class="style-family">${s.family}</div>`:'';family=s.family;const count=F.D.artists.filter(a=>a.style===s.id).length;return heading+`<button class="style-button ${s.id===S.c.style?'active':''}" data-style="${s.id}" aria-pressed="${s.id===S.c.style}">${esc(s.name)}<span>${count?count+' artist'+(count>1?'s':'')+' \u00b7 ':''}${esc(s.refs)}</span></button>`}).join('')||'<p class="empty-search">No matches. Try a genre or artist name.</p>';
  $('styleCount').textContent=F.D.styles.length;
 }
 function artistOptions(value){return `<option value="" ${value?'':'selected'}>Style perspective</option>`+F.D.families.map(f=>{const list=F.D.artists.filter(a=>familyOf(a)===f).sort((a,b)=>fold(a.name).localeCompare(fold(b.name)));return list.length?`<optgroup label="${esc(f)} \u00b7 ${list.length}">${options(list.map(a=>[a.id,a.name+' \u2014 '+F.getStyle(a.style).name]),value)}</optgroup>`:''}).join('');}
 function renderArtistChips(){const c=S.c,list=F.D.artists.filter(a=>a.style===c.style);$('artistChips').innerHTML=list.length?`<span class="small-label">PERSPECTIVES IN THIS STYLE</span><button class="${c.artist?'':'active'}" data-artist="" aria-pressed="${!c.artist}">Style</button>`+list.map(a=>`<button class="${a.id===c.artist?'active':''}" data-artist="${esc(a.id)}" aria-pressed="${a.id===c.artist}" title="${esc(a.focus)}">${esc(a.name)}</button>`).join(''):'';}
 function chooseArtist(id){change(()=>{const a=F.getArtist(id);if(a){const root=S.c.root,seed=S.c.seed;S.c=F.config(a.style,a.id);S.c.root=root;S.c.seed=seed;S.mix=initialMix(a.style,a.id);}else{const root=S.c.root,seed=S.c.seed,style=S.c.style;S.c=F.config(style);S.c.root=root;S.c.seed=seed;S.mix=initialMix(style);}S.motif=F.melody(S.c);},F.getArtist(id)?'An original study of this writing approach.':'Back to the style\u2019s own writing character.');}
 function render(){
  const c=S.c,s=F.getStyle(c.style),a=F.getArtist(c.artist);renderStyles();$('familyLabel').textContent=s.family+' / '+s.kind+' writing';$('styleTitle').textContent=s.name;$('styleLesson').textContent=a?a.name+' · '+a.focus:s.lesson;
  $('artist').innerHTML=artistOptions(c.artist);renderArtistChips();
  $('root').innerHTML=options(NOTE_NAMES.map((n,i)=>[i,n]),c.root);$('mode').innerHTML=options(Object.entries(MODE_NAMES),c.mode);
  for(const id of ['emotion','bpm','bars','seed','space','span','swing','life','form','relation'])$(id).value=c[id];
  for(const id of ['space','swing','life'])$(id+'Value').textContent=c[id]+'%';$('spanValue').textContent=c.span+' steps';
  $('listen').value=S.listen;$('viewMotif').classList.toggle('active',S.view==='motif');$('viewPhrase').classList.toggle('active',S.view==='phrase');
  $('viewMotif').setAttribute('aria-pressed',S.view==='motif');$('viewPhrase').setAttribute('aria-pressed',S.view==='phrase');
  $('harmony').innerHTML=options(s.progressions.map((p,i)=>[i,p.map(chordName).join(' → ')]),c.harmony);
  $('approachTitle').textContent=approaches[s.kind][0];$('approachText').textContent=approaches[s.kind][1];$('exercise').textContent=exercises[s.kind];
  $('ideaTitle').innerHTML=a?esc(a.focus)+'.':'A little repetition.<br>A lot of possibility.';
  $('undo').disabled=!history.length;$('redo').disabled=!future.length;
  const met=F.metrics(S.motif);$('metrics').innerHTML=`<span><b>${met.notes}</b> notes</span><span><b>${met.range}</b> semitone range</span><span><b>${met.repeat}%</b> repeated pitches</span><span><b>${met.held}</b> held notes</span>`;
  $('phraseBlocks').innerHTML=Array.from({length:c.bars/2},(_,i)=>`<div class="phrase-block"><span>BAR ${i*2+1}–${i*2+2}</span><b>${esc(F.labels(c)[i%4])}</b><small>${esc(chordName(F.progression(c)[i%4]))} · ${F.labels(c)[i%4]==='A'?'Repeat':F.labels(c)[i%4]==='B'?'Answer':'Articulate'}${c.relation==='land'&&i%4>0?' / adapt landing':''}</small></div>`).join('');
  $('parts').innerHTML=roles.map(role=>`<div class="part"><input type="checkbox" data-enable="${role}" aria-label="Enable ${role}" ${S.mix[role].enabled?'checked':''}><span class="part-name">${roleNames[role]}</span><select data-sound="${role}" aria-label="${roleNames[role]} preview instrument">${options(soundOptions(role).map(p=>[p.id,p.name]),S.mix[role].sound)}</select><button class="${S.mix[role].solo?'active':''}" data-solo="${role}" aria-label="Solo ${role}" aria-pressed="${S.mix[role].solo}">S</button><input type="range" min="0" max="100" value="${S.mix[role].mix.level}" data-volume="${role}" aria-label="${roleNames[role]} volume"></div>`).join('');
  $('shelfCount').textContent=S.shelf.length;$('shelf').innerHTML=S.shelf.length?S.shelf.map((item,i)=>`<div class="shelf-item"><button data-restore="${i}">${esc(item.name)}<small>${item.c.bpm} BPM / ${esc(NOTE_NAMES[item.c.root])} ${esc(item.c.mode)} / ${item.c.seed}</small></button><button data-remove="${i}" aria-label="Remove saved idea ${i+1}">×</button></div>`).join(''):'<p class="shelf-empty">Keep a promising idea here.<br>Follow another direction. Come back.</p>';
  renderRoll();renderVariants();renderSelection();
 }
 function rollData(){return S.view==='motif'?S.motif:F.phrase(S.motif,S.c);}
 function renderRoll(){
  const ns=rollData(),beats=S.view==='motif'?8:S.c.bars*4,min=ns.length?Math.min(...ns.map(n=>n.p)):60,max=ns.length?Math.max(...ns.map(n=>n.p)):72;
  const low=Math.max(0,min-3),high=Math.min(127,Math.max(max+3,low+14)),row=230/(high-low+1),left=43,width=903,top=29;
  rollGeometry={low,high,row,left,width,top,beats};let svg='';
  for(let p=low;p<=high;p++){const y=top+(high-p)*row,black=[1,3,6,8,10].includes(p%12);svg+=`<rect x="0" y="${y}" width="960" height="${row}" fill="${black?'#25362e':'#2c3e34'}"/><line x1="43" x2="947" y1="${y+row}" y2="${y+row}" stroke="#435044" stroke-width=".35"/>`;if(p%12===0||p===min)svg+=`<text x="8" y="${y+row*.72}" fill="#b3c6a4" font-size="9" font-family="monospace">${esc(noteName(p))}</text>`;}
  for(let step=0;step<=beats*4;step++){const x=left+step/4/beats*width,bar=step%16===0;svg+=`<line x1="${x}" x2="${x}" y1="${bar?20:top}" y2="259" stroke="${bar?'#829175':step%4===0?'#53624f':'#3c4c3f'}" stroke-width="${bar?1:.5}"/>`;if(bar&&step<beats*4)svg+=`<text x="${x+5}" y="15" fill="#bacaa9" font-family="monospace" font-size="9">${String(step/16+1).padStart(2,'0')}</text>`;}
  for(const n of ns){const x=left+n.t/beats*width,y=top+(high-n.p)*row+1,w=Math.max(3,n.d/beats*width),h=Math.max(4,row-2),sel=n.id===selected,col=n.locked?'#f19a7e':n.block!==undefined&&F.labels(S.c)[n.block%4]==='B'?'#e4c997':'#c8e294';
   svg+=`<g data-note="${esc(n.id)}" role="button" tabindex="0" aria-label="${esc(noteName(n.p))}, beat ${n.t}, length ${n.d.toFixed(2)}, velocity ${n.v}${n.locked?', protected':''}"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="2" fill="${col}" fill-opacity="${.55+n.v/280}" stroke="${sel?'#fff':col}" stroke-width="${sel?2:.5}"/>${w>28&&h>11?`<text x="${x+4}" y="${y+h*.73}" font-size="8" fill="#2c402e" font-family="monospace" pointer-events="none">${esc(noteName(n.p))}${n.locked?' •':''}</text>`:''}</g><rect x="${x}" y="${285-n.v/127*17}" width="${Math.min(w,6)}" height="${n.v/127*17}" fill="${col}" fill-opacity=".6"/>`;
  }
  svg+='<line id="playhead" class="playhead" x1="43" x2="43" y1="21" y2="290" stroke="#fff8" stroke-width="1.5" visibility="hidden"/>';$('roll').innerHTML=svg;
  $('rollHint').textContent=S.view==='motif'?'Click to add · drag to move · Shift-click to protect':'Full phrase preview · edit the two-bar motif to change the source';
 }
 function mini(ns){const min=ns.length?Math.min(...ns.map(n=>n.p)):60,max=ns.length?Math.max(...ns.map(n=>n.p)):72;return `<svg viewBox="0 0 240 55" aria-hidden="true">${[0,1,2,3].map(i=>`<line x1="${i*60}" x2="${i*60}" y1="0" y2="55" stroke="#e1e4d8"/>`).join('')}${ns.map(n=>`<rect x="${n.t/8*240}" y="${40-(n.p-min)/Math.max(1,max-min)*34}" width="${Math.max(3,n.d/8*240)}" height="5" rx="1.5" fill="${n.locked?'#d68c6f':'#839d60'}"/>`).join('')}</svg>`;}
 function renderVariants(){const names=['A different pocket','A melodic turn','A new way home'],descs=['Same pitch order. A different placement of attacks.','Same timing and lengths. Selected pitches take a turn.','The opening stays. The ending finds another answer.'];$('variantCards').innerHTML=variants.map((v,i)=>`<article class="variant-card ${audition===i?'auditioning':''}"><div class="variant-head"><span class="variant-num">0${i+1}</span><h3>${names[i]}</h3></div>${mini(v.notes)}<p>${descs[i]}${F.signature(v.notes)===F.signature(S.motif)?' Protected notes leave no change here.':''}</p><div class="variant-actions"><button data-audition="${i}">${audition===i?'■ Stop':'▶ Listen'}</button><button class="use" data-use="${i}">Use this ↗</button></div></article>`).join('');}
 function renderSelection(){const n=S.motif.find(n=>n.id===selected);$('selectionText').textContent=n?`${noteName(n.p)}${n.locked?' · protected':' · source motif'}`:'Select a note to make it yours.';for(const [id,key] of [['notePitch','p'],['noteTime','t'],['noteLength','d'],['noteVelocity','v']]){$(id).disabled=!n||S.view!=='motif';$(id).value=n?Math.round(n[key]*1000)/1000:'';}$('protect').disabled=!n;$('deleteNote').disabled=!n;$('protect').textContent=n?.locked?'Unprotect':'Protect';}
 function activeRoles(){if(S.listen==='solo')return ['melody'];if(S.listen==='groove')return ['melody',...['bass','drums'].filter(r=>S.mix[r].enabled)];const solos=roles.filter(r=>S.mix[r].solo);return solos.length?solos:roles.filter(r=>S.mix[r].enabled);}
 function stop(){playRequest++;playing=false;clearInterval(clockTimer);cancelAnimationFrame(frame);engine?.stop();engine=null;audition=-1;$('play').textContent='▶ Play';$('position').textContent='01 : 01';const line=$('playhead');if(line)line.setAttribute('visibility','hidden');if(variants.length)renderVariants();}
 async function start(candidate=null,index=-1){
  stop();const request=playRequest;try{
   ac=ac||new (window.AudioContext||window.webkitAudioContext)();await ac.resume();if(request!==playRequest)return;
   const ns=candidate||S.motif,tr=F.accompaniment(ns,S.c);playBeats=S.view==='motif'?8:S.c.bars*4;
   playNotes=activeRoles().flatMap(role=>F.performed(tr[role],S.c,role).filter(n=>n.t<playBeats).map(n=>({...n,d:Math.min(n.d,playBeats-n.t),role}))).sort((a,b)=>a.t-b.t);
   if(!playNotes.length){toast('Enable a part to hear this idea.');return;}
   engine=createSoundEngine(ac,S.mix,S.c.bpm,.6);playStart=ac.currentTime+.07;scheduled=0;playing=true;audition=index;$('play').textContent='■ Stop';renderVariants();
   const seconds=60/S.c.bpm,loop=playBeats*seconds;
   function schedule(){if(!playing)return;while(true){const i=scheduled%playNotes.length,cycle=Math.floor(scheduled/playNotes.length),n=playNotes[i],t=playStart+cycle*loop+n.t*seconds;if(t>ac.currentTime+.15)break;if(t>=ac.currentTime-.02)engine.note(n.role,n,Math.max(t,ac.currentTime+.001),seconds,S.mix[n.role]);scheduled++;if(scheduled>1e8){stop();break;}}}
   function animate(){if(!playing)return;const beat=((ac.currentTime-playStart)/seconds%playBeats+playBeats)%playBeats,line=$('playhead');if(line){const x=rollGeometry.left+beat/playBeats*rollGeometry.width;line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('visibility','visible');}$('position').textContent=String(Math.floor(beat/4)+1).padStart(2,'0')+' : '+String(Math.floor(beat%4)+1).padStart(2,'0');frame=requestAnimationFrame(animate);}
   schedule();clockTimer=setInterval(schedule,25);animate();
  }catch(e){stop();toast('Audio could not start: '+e.message);}
 }
 function download(bytes,name,type){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function fileStem(){return `Fieldwork-V3_${S.c.style}_${NOTE_NAMES[S.c.root]}-${S.c.mode}_${S.c.bpm}bpm_${S.c.seed}`;}
 function exportMidi(all=false){const tr=F.accompaniment(S.motif,S.c),chosen=all?Object.fromEntries(roles.filter(r=>S.mix[r].enabled).map(r=>[r,tr[r]])):{melody:tr.melody};if(!Object.keys(chosen).length){toast('Enable at least one part to export.');return;}download(F.midi(chosen,S.c,fileStem()),fileStem()+(all?'_parts':'_melody')+'.mid','audio/midi');toast(`${S.c.bars}-bar MIDI exported with timing, note lengths and velocity.`);}
 async function exportWav(){
  const button=$('exportWav'),renderName=fileStem(),Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline){toast('Audio rendering is unavailable in this browser. MIDI export is ready.');return;}button.disabled=true;button.textContent='Rendering…';stop();
  try{const sr=44100,seconds=S.c.bars*4*60/S.c.bpm+2,ctx=new Offline(2,Math.ceil(seconds*sr),sr),tr=F.accompaniment(S.motif,S.c),eng=createSoundEngine(ctx,S.mix,S.c.bpm,.6,Infinity),events=activeRoles().flatMap(role=>F.performed(tr[role],S.c,role).map(n=>({...n,role}))).sort((a,b)=>a.t-b.t);
   // Offline events are scheduled in advance; future notes must not evict earlier voices.
   for(const n of events)eng.note(n.role,n,n.t*60/S.c.bpm+.03,60/S.c.bpm,S.mix[n.role]);
   const buffer=await ctx.startRendering();eng.stop();
   const bytes=new ArrayBuffer(44+buffer.length*4),dv=new DataView(bytes),str=(at,s)=>{for(let j=0;j<s.length;j++)dv.setUint8(at+j,s.charCodeAt(j));};str(0,'RIFF');dv.setUint32(4,bytes.byteLength-8,true);str(8,'WAVEfmt ');dv.setUint32(16,16,true);dv.setUint16(20,1,true);dv.setUint16(22,2,true);dv.setUint32(24,sr,true);dv.setUint32(28,sr*4,true);dv.setUint16(32,4,true);dv.setUint16(34,16,true);str(36,'data');dv.setUint32(40,buffer.length*4,true);
   const channels=[buffer.getChannelData(0),buffer.getChannelData(1)];for(let n=0;n<buffer.length;n++)for(let ch=0;ch<2;ch++)dv.setInt16(44+(n*2+ch)*2,Math.round(F.bound(channels[ch][n],-1,1)*32767),true);
   download(bytes,renderName+'_preview.wav','audio/wav');toast('Full phrase WAV exported, with a two-second effect tail.');
  }catch(e){toast('Audio export failed: '+e.message);}finally{button.disabled=false;button.textContent='↓ Preview · WAV';}
 }
 function validateSession(input){
  if(!input||input.version!==3)throw Error('Choose a Fieldwork V3 session file.');
  const one=value=>{const c=value?.c;if(!c||!F.D.styles.some(s=>s.id===c.style)||!Object.hasOwn(MODES,c.mode)||!Number.isInteger(c.root)||c.root<0||c.root>11||!Number.isFinite(c.bpm)||c.bpm<60||c.bpm>190||![8,16].includes(c.bars)||!Number.isInteger(c.seed)||c.seed<0||c.seed>999999999)throw Error('Invalid musical settings.');
   for(const [key,max] of [['space',75],['life',100],['swing',60],['span',9],['harmony',2]])if(!Number.isFinite(c[key])||c[key]<0||c[key]>max)throw Error('Invalid '+key+' setting.');
   if(!Number.isInteger(c.harmony)||!Number.isInteger(c.span)||c.span<2)throw Error('Invalid harmony or pitch reach.');
   if(!['AAA′B','AAAA','AABA','ABAB'].includes(c.form)||!['keep','land'].includes(c.relation)||!['native','yearning','bright','suspended','restless'].includes(c.emotion))throw Error('Invalid phrase settings.');
   if(c.artist&&!F.getArtist(c.artist))throw Error('Unknown artist perspective.');
   if(!Array.isArray(value.motif)||value.motif.length>256)throw Error('The motif is too large.');
   const ids=new Set();for(const n of value.motif){if(!n||typeof n.id!=='string'||n.id.length>100||ids.has(n.id)||!Number.isFinite(n.t)||n.t<0||n.t>=8||!Number.isFinite(n.d)||n.d<=0||n.d>8||n.t+n.d>8.003||!Number.isInteger(n.p)||n.p<0||n.p>127||!Number.isInteger(n.v)||n.v<1||n.v>127)throw Error('Invalid motif note.');ids.add(n.id);}
   const mix=value.mix;if(!mix)throw Error('Missing preview settings.');for(const role of roles){const p=mix[role];if(!p||!soundById(p.sound,role)||typeof p.enabled!=='boolean'||typeof p.solo!=='boolean'||!p.mix)throw Error('Invalid preview part.');for(const [key,min,max] of [['level',0,100],['tone',-36,36],['space',0,100],['pan',-100,100]])if(!Number.isFinite(p.mix[key])||p.mix[key]<min||p.mix[key]>max)throw Error('Invalid preview mix.');}
   return {c:F.copy(c),motif:F.clean(value.motif),mix:F.copy(mix)};
  };
  const validated=one(input);if(!Array.isArray(input.shelf)||input.shelf.length>30)throw Error('Invalid idea shelf.');return {version:3,...validated,view:input.view==='phrase'?'phrase':'motif',listen:['groove','solo','mix'].includes(input.listen)?input.listen:'groove',shelf:input.shelf.map(item=>({...one(item),name:String(item.name||'Saved idea').slice(0,100)}))};
 }
 $('styleList').onclick=e=>{const el=e.target.closest('[data-style]');if(!el)return;change(()=>{const root=S.c.root,seed=S.c.seed;S.c=F.config(el.dataset.style);S.c.root=root;S.c.seed=seed;S.motif=F.melody(S.c);S.mix=initialMix(S.c.style);},'A fresh writing direction. Your previous idea is one undo away.');};
 $('search').oninput=renderStyles;
 $('familyFilter').onclick=e=>{const el=e.target.closest('[data-family]');if(!el)return;familyFilter=el.dataset.family;renderStyles();};
 $('artist').onchange=()=>chooseArtist($('artist').value);
 $('artistChips').onclick=e=>{const el=e.target.closest('[data-artist]');if(el&&el.dataset.artist!==S.c.artist)chooseArtist(el.dataset.artist);};
 $('newIdea').onclick=()=>change(()=>{S.c.seed=(S.c.seed+7919)%1000000000;S.motif=newProtected();},'New motif. Protected notes stay in place.');
 for(const id of ['space','span','emotion'])$(id).onchange=()=>change(()=>{S.c[id]=id==='emotion'?$(id).value:Number($(id).value);S.motif=newProtected();},'The source motif was rewritten within your selected constraints.');
 for(const id of ['space','span','swing','life'])$(id).oninput=()=>{$(id+'Value').textContent=$(id).value+(id==='span'?' steps':'%');};
 for(const id of ['swing','life','bpm','bars','form','harmony','relation','seed'])$(id).onchange=()=>{
  const value=['form','relation'].includes(id)?$(id).value:Number($(id).value);if(typeof value==='number'&&(!Number.isFinite(value)||(id==='bpm'&&(value<60||value>190))||(id==='seed'&&(!Number.isInteger(value)||value<0||value>999999999)))){toast('Enter a valid '+id+'.');render();return;}
  change(()=>{S.c[id]=value;if(id==='seed')S.motif=newProtected();},id==='relation'?'The source stays intact; only unprotected phrase landings may adapt.':id==='seed'?'Reproduced the idea from this seed.':'Phrase and performance updated. The source pitches stay yours.',id==='seed');
 };
 $('root').onchange=()=>change(()=>{const root=Number($('root').value),shift=root-S.c.root;S.motif=S.motif.map(n=>({...n,p:F.bound(n.p+shift,0,127)}));S.c.root=root;},'Transposed the complete motif, including protected notes.');
 $('mode').onchange=()=>change(()=>{S.c.mode=$('mode').value;S.motif=S.motif.map(n=>({...n,p:nearestScale(n.p,S.c.root,S.c.mode)}));},'Moved the motif into the selected scale.');
 $('undo').onclick=()=>{if(!history.length)return;stop();future.push(snapshot());S=history.pop();selected=null;refreshVariants();render();$('changeNote').textContent='Previous idea restored.';};
 $('redo').onclick=()=>{if(!future.length)return;stop();history.push(snapshot());S=future.pop();selected=null;refreshVariants();render();};
 $('play').onclick=()=>playing?stop():start();
 for(const [id,view] of [['viewMotif','motif'],['viewPhrase','phrase']])$(id).onclick=()=>{const resume=playing;stop();S.view=view;selected=null;render();if(resume)start();};
 $('listen').onchange=()=>{const resume=playing;stop();S.listen=$('listen').value;if(resume)start();};
 $('refreshVariants').onclick=()=>{stop();refreshVariants();renderVariants();};
 $('variantCards').onclick=e=>{const listen=e.target.closest('[data-audition]'),use=e.target.closest('[data-use]');if(listen){const i=Number(listen.dataset.audition);if(audition===i)stop();else start(variants[i].notes,i);}if(use){const v=variants[Number(use.dataset.use)];change(()=>{S.motif=F.copy(v.notes);},v.kind==='rhythm'?'Kept the pitch order and changed the rhythm.':v.kind==='pitch'?'Kept the timing and note lengths; selected pitches changed.':'Kept the opening and developed the ending.');}};
 function editSelected(fn,msg){if(!selected)return;const id=selected;change(()=>{const n=S.motif.find(n=>n.id===id);if(n)fn(n);S.motif=F.clean(S.motif);},msg);selected=S.motif.some(n=>n.id===id)?id:null;renderRoll();renderSelection();}
 for(const [id,key] of [['notePitch','p'],['noteTime','t'],['noteLength','d'],['noteVelocity','v']])$(id).onchange=()=>{let v=Number($(id).value);if(!Number.isFinite(v))return;v=F.bound(v,key==='d'?.01:0,key==='t'?7.99:key==='d'?8:127);if(key==='p'||key==='v')v=Math.round(v);editSelected(n=>{n[key]=key==='v'?Math.max(1,v):v;},'Edited the source motif. Repeated blocks follow your change.');};
 $('protect').onclick=()=>editSelected(n=>{n.locked=!n.locked;},'Protected notes survive new ideas and all three development tools.');
 $('deleteNote').onclick=()=>{if(!selected)return;const id=selected;change(()=>{S.motif=S.motif.filter(n=>n.id!==id);},'A little more space in the phrase.');};
 function point(e){const rect=$('roll').getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*960,y=(e.clientY-rect.top)/rect.height*290,g=rollGeometry;return {x,y,t:F.bound(Math.round((x-g.left)/g.width*g.beats*4)/4,0,7.75),p:F.bound(g.high-Math.floor((y-g.top)/g.row),0,127)};}
 $('roll').onpointerdown=e=>{if(S.view!=='motif')return;const hit=e.target.closest('[data-note]'),pt=point(e);if(hit){selected=hit.dataset.note;const n=S.motif.find(n=>n.id===selected);if(e.shiftKey){editSelected(n=>{n.locked=!n.locked;},'Note protection updated.');return;}drag={id:n.id,pt,original:F.copy(n),moved:false};$('roll').setPointerCapture(e.pointerId);renderRoll();renderSelection();}else if(pt.x>=rollGeometry.left&&pt.y>=rollGeometry.top&&pt.y<259){const id='user'+Date.now();change(()=>{S.motif=F.clean([...S.motif,{id,t:pt.t,p:pt.p,d:.5,v:94,locked:false}]);},'Added a note to your source motif.');selected=id;renderRoll();renderSelection();}};
 $('roll').onpointermove=e=>{if(!drag)return;const pt=point(e);if(Math.abs(pt.x-drag.pt.x)>3||Math.abs(pt.y-drag.pt.y)>3){drag.moved=true;const el=Array.from($('roll').querySelectorAll('[data-note]')).find(n=>n.dataset.note===drag.id);if(el)el.setAttribute('transform',`translate(${(pt.t-drag.pt.t)/8*rollGeometry.width},${(drag.pt.p-pt.p)*rollGeometry.row})`);}};
 $('roll').onpointerup=e=>{if(!drag)return;const d=drag;drag=null;if(d.moved){const pt=point(e);selected=d.id;editSelected(n=>{n.t=F.bound(d.original.t+pt.t-d.pt.t,0,7.75);n.p=F.bound(d.original.p+pt.p-d.pt.p,0,127);},'Moved a note. The repeated hook follows.');}else renderRoll();};
 $('roll').onpointercancel=()=>{drag=null;renderRoll();};
 $('roll').onkeydown=e=>{const hit=e.target.closest('[data-note]');if(hit&&['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();selected=hit.dataset.note;renderSelection();renderRoll();}};
 $('parts').onchange=e=>{const role=e.target.dataset.enable||e.target.dataset.sound||e.target.dataset.volume;if(!role)return;change(()=>{if(e.target.dataset.enable)S.mix[role].enabled=e.target.checked;if(e.target.dataset.sound)S.mix[role].sound=e.target.value;if(e.target.dataset.volume)S.mix[role].mix.level=Number(e.target.value);},'Preview mix updated. MIDI notes are unchanged.',false);};
 $('parts').onclick=e=>{const el=e.target.closest('[data-solo]');if(!el)return;change(()=>{const role=el.dataset.solo;S.mix[role].solo=!S.mix[role].solo;S.listen='mix';},'Solo audition uses the Enabled parts listening mode.',false);};
 $('saveBranch').onclick=()=>{if(S.shelf.length>=30){toast('Your shelf holds 30 ideas. Save the session, then remove one to make room.');return;}change(()=>{S.shelf.unshift({name:(F.getArtist(S.c.artist)?.name||F.getStyle(S.c.style).name)+' / '+(S.shelf.length+1),c:F.copy(S.c),motif:F.copy(S.motif),mix:F.copy(S.mix)});},'Idea kept on your shelf. Save the session file to keep it between visits.',false);};
 $('shelf').onclick=e=>{const restore=e.target.closest('[data-restore]'),remove=e.target.closest('[data-remove]');if(restore){const item=S.shelf[Number(restore.dataset.restore)];change(()=>{S.c=F.copy(item.c);S.motif=F.copy(item.motif);S.mix=F.copy(item.mix);},'Saved idea restored.');}if(remove)change(()=>S.shelf.splice(Number(remove.dataset.remove),1),'Removed from the shelf. Undo restores it.',false);};
 $('saveSession').onclick=()=>download(JSON.stringify(S,null,2),fileStem()+'.json','application/json');$('loadSession').onclick=()=>$('sessionFile').click();
 $('sessionFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5e6)throw Error('Choose a session smaller than 5 MB.');const state=validateSession(JSON.parse(await file.text()));change(()=>{S=state;},'Your complete V3 session is restored.');}catch(err){toast(err.message);}e.target.value='';};
 $('importMidi').onclick=()=>$('midiFile').click();$('midiFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>4e6)throw Error('Choose a MIDI file smaller than 4 MB.');imported=F.parseMidi(new Uint8Array(await file.arrayBuffer()));$('importTrack').innerHTML=options(imported.tracks.map((tr,i)=>[i,tr.name+' / '+tr.notes.length+' notes']),0);$('importRoot').innerHTML=options(NOTE_NAMES.map((n,i)=>[i,n]),S.c.root);$('importMode').innerHTML=options(Object.entries(MODE_NAMES),S.c.mode);$('importDialog').showModal();}catch(err){toast(err.message);}e.target.value='';};
 $('cancelImport').onclick=()=>$('importDialog').close();$('confirmImport').onclick=()=>{const motif=F.importMotif(imported.tracks[Number($('importTrack').value)]);change(()=>{S.motif=motif;S.c.root=Number($('importRoot').value);S.c.mode=$('importMode').value;S.c.bpm=F.bound(Math.round(imported.tempo),60,190);S.view='motif';},'Imported the first two bars. Your pitches stay intact; the chosen key guides the supporting parts.');$('importDialog').close();};
 $('exportMelody').onclick=()=>exportMidi();$('exportSketch').onclick=()=>exportMidi(true);$('exportFamily').onclick=()=>{download(zipBytes(F.familyFiles(S.motif,S.c)),fileStem()+'_family.zip','application/zip');toast('Exported the two-bar motif, five full parts and the complete sketch.');};$('exportWav').onclick=exportWav;
 $('packText').textContent=`${F.D.styles.length} styles. ${F.D.artists.length} artist perspectives. Original motifs and complete MIDI sketches.`;
 for(const [id,artists] of [['stylePack',false],['artistPack',true]]){$(id).textContent=`↓ ${F.pack(artists).midi.toLocaleString('en')} ${artists?'artist':'style'} MIDIs`;$(id).onclick=async()=>{const b=$(id),label=b.textContent;b.disabled=true;b.textContent='Building your collection…';await new Promise(resolve=>setTimeout(resolve,30));try{download(zipBytes(F.library(artists)),F.pack(artists).name,'application/zip');toast('Collection exported with recipes, seeds and Ableton notes.');}catch(err){toast(err.message);}finally{b.disabled=false;b.textContent=label;}};}
 $('helpButton').onclick=()=>$('help').showModal();$('closeHelp').onclick=()=>$('help').close();
 document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();playing?stop():start();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?$('redo').click():$('undo').click();}if(e.key==='Delete'||e.key==='Backspace'){if(selected){e.preventDefault();$('deleteNote').click();}}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
 refreshVariants();render();$('changeNote').textContent='Your hook stays recognisable as the harmony changes. Start with Play.';
 // Exposed only to the source-level test harness when it explicitly supplies the hook.
 if(typeof V3_TEST_HOOK==='function')V3_TEST_HOOK({getState:()=>S,validateSession,activeRoles,stop,exportWav,approaches,exercises,initialMix,fold});
})();

