/* Creates an isolated, instrumented copy for local headless browser QA. Never changes the delivered page. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.dirname(here),qa=path.join(here,'qa');fs.mkdirSync(qa,{recursive:true});
const setup=`var qaHooks; function V3_TEST_HOOK(h){qaHooks=h;} var qaDownloads=[],qaBlobs=new Map(); const qaCreate=URL.createObjectURL.bind(URL); URL.createObjectURL=function(blob){const url=qaCreate(blob);qaBlobs.set(url,blob);return url;}; HTMLAnchorElement.prototype.click=function(){qaDownloads.push({name:this.download,blob:qaBlobs.get(this.href)});};`;
const tests=async()=>{
 const results=[],errors=[],$=id=>document.getElementById(id),assert=(yes,label)=>{if(!yes)throw Error(label);results.push(label)},sleep=ms=>new Promise(r=>setTimeout(r,ms)),change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new Event('change',{bubbles:true}));},click=id=>$(id).click();
 const heartbeat=setInterval(()=>{document.body.dataset.qaProgress=String(results.length);},1);
 window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
 try{
  assert(!!document.querySelector('#roll [data-note]'),'Piano roll renders real SVG notes');
  const before=V3.signature(qaHooks.getState().motif);click('newIdea');assert(V3.signature(qaHooks.getState().motif)!==before,'New idea changes the motif');click('undo');assert(V3.signature(qaHooks.getState().motif)===before,'Undo restores the exact motif');
  const first=document.querySelector('#roll [data-note]'),rect=first.getBoundingClientRect();first.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:rect.x+3,clientY:rect.y+3,shiftKey:true,pointerId:1}));
  assert(qaHooks.getState().motif[0].locked,'Shift-click protects a note');const protectedNote=JSON.stringify(qaHooks.getState().motif[0]);click('newIdea');assert(qaHooks.getState().motif.some(n=>JSON.stringify(n)===protectedNote),'New idea preserves the protected event');
  document.querySelector('[data-audition="0"]').click();await sleep(100);assert($('play').textContent.includes('Stop'),'Variant audio preview starts');click('play');assert($('play').textContent.includes('Play'),'Audio stops');document.querySelector('[data-use="1"]').click();
  click('viewPhrase');assert(document.querySelectorAll('#roll [data-note]').length>qaHooks.getState().motif.length,'Full phrase displays repeated development');
  click('saveBranch');click('saveSession');const session=qaDownloads.at(-1);assert(session.name.endsWith('.json'),'Session download');const saved=JSON.parse(await session.blob.text());assert(saved.shelf.length===1,'Shelf persists in the session');
  change('artist','massano');assert($('styleTitle').textContent==='Cinematic melodic','Artist perspective selects its writing family');change('artist','indira');assert(qaHooks.getState().c.style==='psytech','Psy-techno artist direction');
  const soundBefore=V3.signature(qaHooks.getState().motif),select=document.querySelector('[data-sound="melody"]');select.value='dry-triangle';select.dispatchEvent(new Event('change',{bubbles:true}));assert(V3.signature(qaHooks.getState().motif)===soundBefore,'Preview sound preserves the MIDI');
  click('exportMelody');const mid=qaDownloads.at(-1);const parsed=V3.parseMidi(new Uint8Array(await mid.blob.arrayBuffer()));assert(parsed.tracks[0].notes.length>0,'Real browser MIDI export round-trips');
  click('exportFamily');const zip=qaDownloads.at(-1),zb=new Uint8Array(await zip.blob.arrayBuffer());assert(zb[0]===80&&zb[1]===75,'Real browser family ZIP export');
  const dt=new DataTransfer();dt.items.add(new File([await mid.blob.arrayBuffer()],'original.mid',{type:'audio/midi'}));$('midiFile').files=dt.files;$('midiFile').dispatchEvent(new Event('change'));await sleep(50);assert($('importDialog').open,'MIDI import opens track selection');click('confirmImport');assert(!$('importDialog').open&&qaHooks.getState().view==='motif','Imported melody becomes the source motif');
  const dt2=new DataTransfer();dt2.items.add(new File([session.blob],'session.json',{type:'application/json'}));$('sessionFile').files=dt2.files;$('sessionFile').dispatchEvent(new Event('change'));await sleep(50);assert(qaHooks.getState().c.style===saved.c.style&&qaHooks.getState().shelf.length===1,'Saved session restores through the file input');
  // Render an actual Web Audio graph, then measure the resulting PCM rather than just mocking the API.
  change('listen','solo');await qaHooks.exportWav();const wav=qaDownloads.at(-1);assert(wav.name.endsWith('.wav'),'WAV export completes in the browser');const wb=await wav.blob.arrayBuffer(),view=new DataView(wb);assert(String.fromCharCode(...new Uint8Array(wb,0,4))==='RIFF','WAV has a RIFF header');let peak=0,energy=0,count=0;for(let i=44;i<wb.byteLength;i+=2){const sample=view.getInt16(i,true)/32768;peak=Math.max(peak,Math.abs(sample));energy+=sample*sample;count++;}assert(peak>.01&&peak<.999,'Rendered audio is audible and not hard-clipped');results.push('PCM peak '+peak.toFixed(4)+'; RMS '+Math.sqrt(energy/count).toFixed(4));
  change('listen','mix');for(const role of ['melody','bass','chords','arp','drums']){const enabled=document.querySelector('[data-enable="'+role+'"]');if(!enabled.checked)enabled.click();}
  await qaHooks.exportWav();const fullWav=await qaDownloads.at(-1).blob.arrayBuffer(),fullView=new DataView(fullWav);let fullPeak=0;for(let i=44;i<fullWav.byteLength;i+=2)fullPeak=Math.max(fullPeak,Math.abs(fullView.getInt16(i,true)/32768));assert(fullPeak>.01&&fullPeak<.999,'Five-part WAV renders without hard clipping');
  let renderedVoices=0;for(const patch of SOUNDS){const audioCtx=new OfflineAudioContext(1,22050,22050),mix=V3.copy(qaHooks.getState().mix);mix.melody.sound=patch.id;const audioEngine=createSoundEngine(audioCtx,mix,126,.6,Infinity);audioEngine.note('melody',{p:69,v:100,d:.5},.01,60/126,mix.melody);const buf=await audioCtx.startRendering();audioEngine.stop();let p=0;for(const x of buf.getChannelData(0))p=Math.max(p,Math.abs(x));if(!Number.isFinite(p)||p<.00001)throw Error('Silent or invalid preview patch: '+patch.id);renderedVoices++;}assert(renderedVoices===59&&SOUNDS.length===59,'All 59 tonal preview patches render audible PCM');
  let renderedKits=0;for(const kit of DRUM_KITS){const audioCtx=new OfflineAudioContext(1,22050,22050),mix=V3.copy(qaHooks.getState().mix);mix.drums.sound=kit.id;const audioEngine=createSoundEngine(audioCtx,mix,126,.6,Infinity);for(const [p,t] of [[36,.01],[39,.12],[46,.22]])audioEngine.note('drums',{p,v:100,d:.1},t,60/126,mix.drums);const buf=await audioCtx.startRendering();audioEngine.stop();let p=0;for(const x of buf.getChannelData(0))p=Math.max(p,Math.abs(x));if(!Number.isFinite(p)||p<.00001)throw Error('Silent kit: '+kit.id);renderedKits++;}assert(renderedKits===19,'All 19 drum kits render kick, clap and open hat');
  for(const style of V3.D.styles){document.querySelector('[data-style="'+style.id+'"]').click();assert(qaHooks.getState().c.style===style.id,'Style opens: '+style.id);assert([...document.querySelectorAll('[data-sound]')].every(s=>s.value===qaHooks.getState().mix[s.dataset.sound].sound),'Every part shows its preview sound: '+style.id);}
  document.querySelector('[data-family="House"]').click();assert([...document.querySelectorAll('[data-style]')].every(b=>V3.getStyle(b.dataset.style).family==='House')&&document.querySelectorAll('[data-style]').length===25,'Family filter shows the 25 house styles');document.querySelector('[data-family="All"]').click();
  let artistCount=0;for(const artist of V3.D.artists){change('artist',artist.id);const s=qaHooks.getState();if(s.c.artist!==artist.id||s.c.style!==artist.style||!document.querySelector('#artistChips [data-artist="'+artist.id+'"].active'))throw Error('Artist does not open: '+artist.id);artistCount++;}assert(artistCount===120,'All 120 artist perspectives open with an active chip');
  document.querySelector('[data-style="chicago"]').click();document.querySelector('#artistChips [data-artist="greenvelvet"]').click();assert(qaHooks.getState().c.artist==='greenvelvet'&&qaHooks.getState().c.bpm===126,'Artist chip applies its perspective');document.querySelector('#artistChips [data-artist=""]').click();assert(qaHooks.getState().c.artist===''&&qaHooks.getState().c.bpm===124,'Style chip restores the style perspective');
  $('search').value='hardfloor';$('search').dispatchEvent(new Event('input'));assert(document.querySelectorAll('[data-style]').length===1&&document.querySelector('[data-style="acidhouse"]'),'Search finds a style by artist');$('search').value='';$('search').dispatchEvent(new Event('input'));
  assert($('stylePack').textContent.includes('1,104')&&$('artistPack').textContent.includes('960'),'Collection buttons show current counts');
  document.querySelector('[data-style="singable"]').click();click('viewMotif');$('helpButton').click();assert($('help').open,'Help dialog opens');$('closeHelp').click();
  assert(document.documentElement.scrollWidth<=window.innerWidth+1,'Page fits the viewport horizontally at '+window.innerWidth+'px');assert(errors.length===0,'No uncaught browser exceptions');
  document.body.dataset.qa='passed';
 }catch(e){errors.push(e.stack||String(e));document.body.dataset.qa='failed';}
 clearInterval(heartbeat);const report=document.createElement('pre');report.id='qa-report';report.textContent=JSON.stringify({status:document.body.dataset.qa,results,errors},null,2);report.style.cssText='white-space:pre-wrap;padding:20px;background:#fff';document.body.appendChild(report);document.title='QA '+document.body.dataset.qa;
};
const html=fs.readFileSync(path.join(root,'fieldwork-v3.html'),'utf8').replace('<script>','<script>'+setup+'\n').replace('</body>','<script>('+tests.toString()+')();</script></body>');fs.writeFileSync(path.join(qa,'browser-check.html'),html);
console.log('Created v3-src/qa/browser-check.html for an isolated headless run.');
