/* Fieldwork V3: original writing studies, never transcriptions. Rhythm positions are sixteenths over two bars. */
const V3_DATA = (() => {
 const rhythms = {
  hook:[[0,2,4,7,12,16,18,20,23,28],[2,4,6,12,16,20,22,27],[0,3,4,10,12,18,20,26,28],[0,4,6,8,15,16,20,24],[1,4,7,8,14,17,20,23,28],[0,2,6,8,12,16,18,22,24,29]],
  rave:[[0,2,4,4.5,6,10,12,14,16,18,20,22,26,28,30],[0,0.5,2,6,8,10,14,16,18,22,24,26,30],[2,4,6,8,11,14,18,20,22,24,27,30],[0,2,3,6,8,12,14,16,18,19,22,24,28],[0,4,5,6,10,12,16,20,21,22,26,30]],
  hypnotic:[[0,3,7,10,16,19,23,26],[1,6,9,14,17,22,25,30],[0,5,10,15,20,25,30],[2,4,9,12,18,20,25,28],[0,2,7,8,16,18,23,24],[3,8,11,16,19,24,27]],
  percussion:[[1,4,6,11,14,17,20,22,27,30],[0,3,5,9,12,15,16,19,21,25,28],[2,5,8,10,13,18,21,24,26,29],[0,7,10,12,16,19,23,26,28,31],[1,3,8,9,14,17,19,24,25,30]],
  cinematic:[[0,4,7,12,16,18,22,28],[2,6,8,15,18,22,24],[0,3,8,12,16,19,24,27],[0,6,10,16,20,23,28],[1,4,8,14,17,20,24,30]],
  rolling:[[1,2,3,5,6,7,9,10,11,13,14,15,17,18,19,21,22,23,25,26,27,29,30,31],[0,2,4,6,7,8,10,12,14,16,18,20,22,23,24,26,28,30],[0,1,4,7,8,9,12,15,16,17,20,23,24,25,28,31],[0,3,6,9,12,15,18,21,24,27,30]],
  broken:[[0,3,7,10,14,16,19,22,27,30],[2,5,8,11,15,18,21,24,28],[0,6,7,10,16,18,23,26,31],[1,4,7,12,15,17,20,23,28],[0,2,7,9,14,16,22,23,26]],
  disco:[[0,2,5,7,10,12,14,16,18,21,23,26,28,30],[2,4,7,8,11,14,18,20,23,24,27,30],[0,3,4,6,10,12,15,16,19,20,22,26,28],[1,4,6,9,12,14,17,20,22,25,28,30]],
  // Expanded edition approaches. Existing approaches above are unchanged, so their seeds still reproduce.
  stab:[[2,6,10,14,18,22,26,30],[3,6,10,13,19,22,26,29],[0,3,6,10,12,16,19,22,26,28],[2,5,8,14,18,21,24,30],[1,4,10,12,17,20,26,28],[0,2,6,11,14,16,18,22,27,30]],
  piano:[[0,3,6,8,11,14,16,19,22,24,27,30],[0,3,6,10,12,16,19,22,26,28],[2,4,7,10,12,18,20,23,26,28],[0,3,4,7,10,12,16,19,20,23,26,28],[1,4,6,9,12,14,17,20,22,25,28,30]],
  vocal:[[0,1,2,6,8,9,10,14,16,17,18,22,24,28],[2,3,6,10,11,14,18,19,22,26,27,30],[0,0.5,1,4,7,8,12,12.5,13,16,20,23,24,28],[1,2,6,7,10,14,17,18,22,23,26,30],[0,2,2.5,3,8,10,11,16,18,18.5,19,24,27]],
  sequence:[[0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30],[0,3,6,8,11,14,16,19,22,24,27,30],[0,2,3,6,8,10,11,14,16,18,19,22,24,26,27,30],[0,1,2,4,6,8,9,10,12,14,16,17,18,20,22,24,25,26,28,30],[2,4,6,8,10,12,14,18,20,22,24,26,28,30]],
  acid:[[0,1,3,4,6,8,9,11,12,14,16,17,19,20,22,24,26,27,30],[0,2,3,5,6,8,10,11,13,14,16,18,19,21,22,24,26,28,29],[0,1,2,4,5,7,8,10,12,13,15,16,18,20,21,23,24,26,28,30],[0,3,4,6,7,10,12,14,15,16,19,20,22,23,26,28,31]],
  jack:[[0,3,6,7,10,14,16,19,22,23,26,30],[2,3,6,10,11,14,18,19,22,26,27,30],[0,3,4,7,10,12,15,16,19,22,26,28],[0,2,3,6,9,12,14,16,18,19,22,25,28],[1,3,6,8,11,14,17,19,22,24,27,30]]
 };
 const shapes={
  hook:[[0,0,1,2,4,4,2,1,0],[2,2,1,0,0,1,2,4,2],[4,4,3,2,2,1,0,2,0],[0,2,2,1,0,0,4,2,1],[2,1,0,0,1,2,2,4,2]],
  rave:[[0,0,0,2,2,4,4,2,1,0],[4,4,4,2,2,1,0,0,2,4],[0,0,2,2,0,0,4,4,2,1],[2,2,2,4,5,4,2,2,1,0]],
  hypnotic:[[0,0,0,1,0,0,0,2],[0,0,2,0,0,2,0,0],[2,2,2,1,2,2,0,2],[0,0,0,0,0,1,0,0]],
  percussion:[[0,0,2,0,0,4,0,2],[2,0,0,2,0,0,1,0],[0,0,0,2,0,0,4,2]],
  cinematic:[[0,1,2,4,4,3,2,1,0],[2,2,4,5,4,2,1,0],[4,3,2,2,1,0,1,2],[0,0,2,4,5,4,2,0]],
  rolling:[[0,0,0,1,0,0,2,0],[0,0,2,0,0,4,2,0],[2,2,1,0,0,1,2,0]],
  broken:[[0,2,2,1,0,0,4,2],[2,2,4,2,1,0,1,2],[4,2,1,0,0,2,2,1]],
  disco:[[0,0,2,4,4,2,1,0],[2,2,1,0,0,2,4,2],[0,2,4,4,5,4,2,1]],
  stab:[[0,0,2,0,0,4,0,2],[4,4,2,4,4,0,2,4],[0,0,0,3,0,0,0,4],[2,2,0,2,2,4,2,0]],
  piano:[[4,2,4,2,0,4,2,4],[0,2,4,4,2,4,5,4],[4,4,5,4,2,2,0,2],[2,4,2,0,2,4,6,4]],
  vocal:[[2,2,2,4,2,2,2,0],[4,4,5,4,2,2,0,2],[0,0,2,2,4,4,2,0],[2,2,4,2,1,1,0,1]],
  sequence:[[0,2,4,7,4,2],[0,4,2,7,4,2,0,4],[7,4,2,0,2,4],[0,2,4,2,5,4,2,4],[0,4,7,9,7,4]],
  acid:[[0,0,0,1,0,2,0,0],[0,0,3,0,0,4,2,0],[0,2,0,0,1,0,4,0],[0,0,4,0,3,0,0,2]],
  jack:[[0,0,4,0,2,0,0,4],[0,2,0,0,4,3,2,0],[4,2,0,0,2,0,5,4],[0,0,0,2,0,0,4,2]]
 };
 // Writing behaviour for the expanded approaches: repetition, reach, leap size, octave jumps and default contours.
 const kinds={
  stab:{repeat:.5,reach:5,contours:['flat','bounce','rise','answer']},
  piano:{repeat:.3,leap:5,top:6,contours:['zigzag','arch','bounce','fall']},
  vocal:{repeat:.45,reach:6,top:5,contours:['bounce','arch','zigzag','fall']},
  sequence:{repeat:.12,step:.1,leap:9,top:7,contours:['pedal','climb','arch','zigzag','fall']},
  acid:{repeat:.5,reach:4,oct:.2,step:.2,contours:['flat','zigzag','rise','bounce']},
  jack:{repeat:.45,reach:5,oct:.12,contours:['flat','bounce','answer','zigzag']}
 };
 // Explicit musical differences: family, writing approach, rhythm, harmony, groove and instrumentation.
 const rows=[
 ['singable','Big melodic hooks','Techno','hook',126,'minor',8,'soft-mono','Kölsch · Paul Kalkbrenner','A memorable crest, a pause, then a familiar answer.'],
 ['rave','Rave / trance techno','Techno','rave',145,'minor',0,'supersaw','I Hate Models · Marlon Hoffstadt','Repeated attacks and short pickups frame a longer landing.'],
 ['afterlife','Cinematic melodic','Techno','cinematic',126,'minor',0,'resonant-lead','Innellea · Mind Against · Massano','A compact lead holds its identity while the harmony changes.'],
 ['driving','Peak-time / driving','Techno','percussion',132,'minor',0,'short-saw','Adam Beyer · Karla Blum','A clipped riff makes room for the low-end pulse.'],
 ['hypnotic','Hypnotic / raw','Techno','hypnotic',136,'minor',8,'hollow-square','Ben Klock · Rødhåd · Oscar Mulero','Small pitch changes and displaced accents sustain the tension.'],
 ['minimaltech','Minimal techno','Techno','hypnotic',128,'minor',12,'digital-pluck','Richie Hawtin · Plastikman','Silence and a tiny recurring interval carry the idea.'],
 ['hardgroove','Hardgroove','Techno','percussion',142,'dorian',20,'marimba','Ben Sims · Chlär · DJ Rush','Pitched percussion and answering bass form an interlocking groove.'],
 ['industrial','Industrial / EBM','Techno','hypnotic',138,'phrygian',0,'drive-bass','Perc · VTSS · SNTS','A narrow, insistent bass-register motif with modal bite.'],
 ['hardtech','Hard techno','Techno','rave',150,'minor',0,'detuned-saw','Klangkuenstler · Sara Landry','Repeated notes and abrupt spaces focus the energy.'],
 ['psytech','Psy-techno','Techno','rolling',142,'phrygian',0,'acid-sequence','Indira Paganotto','Rolling repetition opens into a brief modal response.'],
 ['acid','Acid / live sequences','Techno','rolling',138,'dorian',8,'acid-sequence','Reinier Zonneveld · Acid Arab','Repeated anchors, short articulations and occasional higher notes.'],
 ['schranz','Schranz','Techno','percussion',155,'minor',0,'short-saw','Chris Liebing · early hard-techno studies','A sparse pitched hook sits against a relentless percussion frame.'],
 ['bleep','Bleep / UK techno','Techno','hypnotic',128,'minor',14,'hollow-square','LFO · early UK bleep studies','A small electronic call and a spacious low answer.'],
 ['tribal','Tribal techno','Techno','percussion',134,'dorian',24,'marimba','Percussion-led techno studies','Accents pass between the motif, toms and bass.'],
 ['ambient','Ambient techno','Techno','cinematic',116,'dorian',6,'glass-pluck','Atmospheric techno studies','Longer notes, ample silence and gentle harmonic movement.'],
 ['detroit','Detroit techno','Techno','disco',128,'dorian',14,'electric-keys','Derrick May · Carl Craig','A syncopated melodic turn with warm harmonic colour.'],
 ['dub','Dub techno','Techno','hypnotic',122,'minor',12,'organ-stab','Basic Channel · dub chord studies','Few notes and long spaces invite delay and texture.'],
 ['progressive','Progressive house','House','hook',124,'minor',6,'analog-pluck','deadmau5 · Eric Prydz','A repeating melodic cell grows through phrasing and harmony.'],
 ['melodic','Melodic house','House','cinematic',122,'major',8,'soft-pluck','Lane 8 · Ben Böhmer','Patient movement, sustained landings and a gentle answer.'],
 ['deep','Deep house','House','disco',122,'dorian',30,'electric-keys','Kerri Chandler · Larry Heard','Offbeat phrasing and softer connecting notes.'],
 ['micro','Minimal / microhouse','House','percussion',126,'dorian',28,'digital-pluck','Ricardo Villalobos · microhouse studies','Dry, irregular little calls with a loose rhythmic pocket.'],
 ['techhouse','Tech house','House','percussion',128,'minor',18,'vocalish-pluck','Chris Lake · FISHER','A compact repeated hook with a deliberate bass response.'],
 ['afro','Afro house','House','percussion',122,'dorian',24,'kalimba','Black Coffee · percussion-led house','A recurring melodic call moves around layered percussion.'],
 ['stutter','Stutter house','House','broken',130,'major',12,'soft-pluck','Contemporary chopped-house studies','Small repeated fragments alternate with an open landing.'],
 ['disco','Disco / French house','House','disco',123,'dorian',20,'clav-keys','Daft Punk · Purple Disco Machine','A rhythmic motif and octave bass make a repeating conversation.'],
 ['indie','Indie dance / dark disco','Disco','disco',120,'minor',10,'hollow-square','Damon Jee · dark-disco studies','A bass-led figure with a terse upper reply.'],
 ['italo','Italo disco','Disco','disco',118,'minor',4,'short-saw','Italo synth and octave-bass studies','A clear melodic shape above a moving octave pulse.'],
 ['trance','Classic trance','Trance','rave',138,'minor',0,'wide-pluck','Tiësto / classic · Paul van Dyk · Chicane','An insistent repeated cell resolves into a held phrase ending.'],
 ['hardtrance','Hard trance','Trance','rave',145,'harmonic',0,'supersaw','Hard-trance riff studies','A forceful repeating hook with a sharper leading-tone colour.'],
 ['futurerave','Big room / future rave','Trance','rave',128,'minor',0,'anthem-saws','Festival lead and stab studies','A broad landing surrounded by short, repeated attacks.'],
 ['psy','Psytrance','Trance','rolling',145,'phrygian',0,'acid-sequence','Astrix · rolling modal studies','A tight rolling grid with selective modal deviations.'],
 ['breaks','Melodic breaks','Broken beat','broken',132,'minor',16,'wide-pluck','Bicep · Bonobo','An exposed melodic phrase crosses a broken drum pattern.'],
 ['garage','UK garage','Broken beat','broken',132,'dorian',38,'organ-lead','Disclosure · UK garage studies','Offbeat notes and short answers ride a shuffled pocket.'],
 ['electro','Electro','Broken beat','hypnotic',132,'minor',12,'hollow-square','Drexciya · electro sequence studies','An angular small motif meets a syncopated bassline.'],
 ['dnb','Liquid drum & bass','Broken beat','cinematic',172,'dorian',8,'soft-pluck','Liquid melodic studies','A spacious melodic phrase above a fast broken rhythm.'],
 ['amapiano','Amapiano','Broken beat','percussion',112,'dorian',30,'fm-pluck','Log-drum and piano studies','A pitched low response and a spacious, syncopated upper motif.'],
 // Expanded edition. Appended rows keep the original seeds and collection recipes stable.
 // Options: register, sparse, beat (broken/threestep), hat (open/roll), bassline (rolling/octave/syncopated), chords (pad/piano/offbeat), preview sounds and kit.
 ['melodicseq','Melodic techno sequences','Techno','sequence',124,'minor',0,'wide-pluck','Tale Of Us · Anyma · ARTBAT','A chord-tone arpeggio cycles while one note shifts the colour.',{bassline:'rolling',chords:'pad',chordSound:'cinema-pad'}],
 ['acidtechno','Acid techno / 303','Techno','acid',136,'minor',6,'acid-squelch','Emmanuel Top · Amelie Lens','Accents, octave jumps and legato slides turn one note into a line.',{kit:'hard-909',bassSound:'soft-sub',hat:'roll'}],
 ['darkstab','Dark stab techno','Techno','stab',132,'phrygian',0,'chord-stab','Dax J · warehouse stab studies','A minor-chord stab answers itself across the bar.',{kit:'rumble-techno',chords:'offbeat',chordSound:'dark-stab'}],
 ['bigroomtechno','Big-room techno','Techno','stab',130,'minor',0,'brass-stab','Enrico Sangiuliano · Space 92','One huge stab note repeats until the drop makes it massive.',{kit:'rumble-techno',hat:'open'}],
 ['loop','Swedish loop techno','Techno','stab',131,'dorian',14,'fm-pluck','Cari Lekebusch · Joel Mull','A tiny looped figure gets its lift from swing and percussion.',{hat:'roll'}],
 ['birmingham','Birmingham / raw loop','Techno','jack',138,'phrygian',6,'dark-stab','Surgeon · Regis','A stripped pitched loop with a mechanical funk.',{register:48,kit:'warehouse',hat:'roll'}],
 ['ukbass','UK bass techno','Techno','jack',132,'minor',12,'drive-bass','Blawan · Pariah · Batu','A swung low figure pushes against a broken kick.',{register:48,beat:'broken',kit:'bass-breaks'}],
 ['groovetech','Groovy / Latin techno','Techno','vocal',128,'dorian',16,'vocalish-pluck','Joseph Capriati · Paco Osuna','A short chanted fragment trades places with the percussion.',{hat:'open',kit:'punchy-house'}],
 ['modular','Modular / hypnotic sequences','Techno','sequence',128,'dorian',0,'analog-pluck','Donato Dozzy · Colyn','A small sequence rotates and gradually shifts its accent.',{bassline:'rolling',span:5}],
 ['deeptechno','Deep / atmospheric techno','Techno','hypnotic',130,'phrygian',6,'dub-chord','Lucy · deep-space techno studies','Slowly phasing tones sit inside a dark, deep pulse.',{sparse:true,chords:'offbeat',chordSound:'dub-chord',kit:'rumble-techno'}],
 ['trancetechno','Trance-techno','Techno','sequence',140,'minor',0,'hollow-square','Trym · SPFDJ · neo-trance studies','A fast arpeggio climbs toward a sustained trance landing.',{kit:'hard-909',chords:'pad',chordSound:'anthem-saws',hat:'roll'}],
 ['eurobounce','Neo-rave / euro bounce','Techno','stab',142,'minor',0,'rave-organ','DJ Heartstring · eurodance studies','Bouncy offbeat notes set up one big, simple answer.',{hat:'open',kit:'hard-909',bassline:'octave'}],
 ['ghettotech','Ghettotech','Techno','vocal',146,'minor',8,'vocal-chop','DJ Godfather · DJ Assault','Chopped repeated syllables race over a jacking 808 floor.',{kit:'long-808',hat:'open'}],
 ['gabber','Gabber / hardcore','Techno','rave',175,'minor',0,'hoover','Rotterdam hardcore studies · Angerfist','Short distorted repeats land on a sweeping hoover note.',{kit:'hard-909',bassSound:'drive-bass'}],
 ['chicago','Chicago jack','House','jack',124,'minor',18,'jack-bass','Marshall Jefferson · Green Velvet','A raw bass-register riff jacks against open hats and claps.',{register:48,kit:'chicago-808',hat:'open'}],
 ['acidhouse','Acid house','House','acid',122,'minor',16,'acid-sequence','Phuture · DJ Pierre · Hardfloor','A squelching 303 line with swing, rests and octave accents.',{kit:'chicago-808',hat:'open',bassSound:'soft-sub'}],
 ['pianohouse','90s piano house','House','piano',124,'major',12,'house-piano','Italo-house piano studies · Marshall Jefferson','Offbeat piano chords rock between close inversions.',{chords:'piano',chordSound:'house-piano',hat:'open',kit:'punchy-house',bassline:'octave'}],
 ['soulful','Soulful / NY garage house','House','piano',122,'dorian',26,'electric-keys','Masters At Work · Louie Vega · Joey Negro','A gospel-leaning keys riff with a warm syncopated lift.',{chords:'piano',chordSound:'electric-keys',hat:'open',kit:'deep-house'}],
 ['organhouse','90s organ house','House','stab',124,'minor',14,'organ-stab','Todd Terry · MK','A punchy organ riff doubles as the bassline.',{register:48,hat:'open',kit:'punchy-house',bassSound:'organ-bass'}],
 ['vocalhouse','Vocal / diva house','House','vocal',124,'major',12,'vowel-lead','Honey Dijon · MK · diva-house studies','Short sung syllables climb into an open, held vowel.',{hat:'open',kit:'punchy-house',chords:'piano',chordSound:'house-piano'}],
 ['lofi','Lo-fi house','House','piano',120,'dorian',28,'felt-keys','DJ Seinfeld · Ross From Friends · Mall Grab','A dusty keys phrase loops with a lazy swing.',{chords:'piano',chordSound:'felt-keys',kit:'soft-organic'}],
 ['deeptech','Deep tech','House','vocal',124,'minor',14,'talkbox-lead','Hot Since 82 · Jamie Jones · Rossko','A murmured vocal-style fragment rides a rolling low groove.',{bassline:'rolling',kit:'tech-house',hat:'open'}],
 ['rominimal','Rominimal','House','jack',125,'dorian',34,'rubber-bass','Rhadoo · Petre Inspirescu · Raresh','A long, wandering low line breathes around tiny percussion.',{register:48,sparse:true,kit:'minimal-click'}],
 ['basshouse','Bass house','House','jack',126,'minor',8,'fm-growl','AC Slater · Jauz · Chris Lorenzo','A growling bass hook replies to a short vocal-like stab.',{register:48,kit:'tech-house',hat:'open'}],
 ['speedgarage','Speed garage','House','jack',132,'minor',30,'reese-bass','Armand Van Helden · 187 Lockdown','A Reese riff and shuffled hats carry the hook.',{register:48,kit:'uk-garage',hat:'open'}],
 ['futurehouse','Future house','House','vocal',125,'minor',6,'vocal-chop','Oliver Heldens · Tchami','A metallic, bouncing chop with an octave reply.',{hat:'open',kit:'tech-house',bassline:'syncopated',oct:.15}],
 ['electrohouse','Electro house','House','stab',128,'minor',0,'detuned-saw','Justice · Boys Noize · Wolfgang Gartner','A clipped, detuned riff punches up an octave.',{kit:'punchy-house',bassline:'octave',oct:.18}],
 ['hardhouse','Hard house','House','stab',145,'minor',0,'hoover','BK · UK hard-house studies','Pumping offbeat stabs, a hoover answer and no let-up.',{hat:'open',kit:'hard-909',bassline:'octave',bassSound:'donk-bass'}],
 ['organic','Organic house','House','cinematic',118,'phrygian',14,'kalimba','Bedouin · Monolink · Sabo','Modal colour and a slow, hand-played line.',{kit:'organic-percussion'}],
 ['afrotech','Afro tech / 3-step','House','sequence',122,'minor',18,'marimba','Caiiro · Enoo Napa · Da Capo','A three-step kick leaves room for a cycling melodic call.',{beat:'threestep',kit:'organic-percussion',bassline:'syncopated'}],
 ['progseq','Progressive sequences','House','sequence',126,'minor',0,'hollow-square','Sasha · John Digweed · Hernán Cattáneo','A long, patient sequence gains weight through its harmony.',{bassline:'rolling',chords:'pad',chordSound:'slow-strings'}],
 ['nudisco','Nu-disco / cosmic','Disco','sequence',116,'major',16,'electric-keys','Todd Terje · Lindstrøm','A sparkling arpeggio over a galloping octave bass.',{kit:'disco-707',bassSound:'disco-bass',bassline:'octave'}],
 ['uplifting','Uplifting trance','Trance','sequence',138,'minor',0,'supersaw','Armin van Buuren · Above & Beyond','A soaring arpeggio resolves into a wide, held landing.',{kit:'trance-909',chords:'pad',chordSound:'anthem-saws',hat:'open'}]
 ];
 const families=['Techno','House','Disco','Trance','Broken beat'];
 // Expanded rows carry a seed salt so styles sharing an approach still write different motifs at the same seed. Original rows keep salt 0.
 const salt=(id,o)=>o?[...id].reduce((h,ch)=>Math.imul(h^ch.charCodeAt(0),16777619)>>>0,2166136261)%1000003:0;
 const styles=rows.map(([id,name,family,kind,bpm,mode,swing,sound,refs,lesson,options],i)=>{const o=options||{};return {id,name,family,kind,bpm,mode,swing,sound,refs,lesson,salt:salt(id,options),rhythmOffset:i%rhythms[kind].length,register:o.register??(['industrial','indie'].includes(id)?48:60),sparse:o.sparse??['minimaltech','dub','ambient','bleep'].includes(id),progressions:o.progressions||(kind==='hypnotic'||kind==='rolling'?[[0,0,0,0],[0,0,1,0],[0,3,0,0]]:kind==='acid'||kind==='jack'?[[0,0,0,0],[0,0,3,0],[0,0,5,6]]:mode==='major'?[[0,4,5,3],[3,0,5,4],[0,0,3,4]]:mode==='dorian'?[[0,3,0,3],[0,6,3,0],[0,0,3,4]]:[[0,5,2,6],[0,3,5,6],[0,0,5,3]]),beat:o.beat,hat:o.hat,bassline:o.bassline,chords:o.chords,chordSound:o.chordSound,bassSound:o.bassSound,kit:o.kit,span:o.span,oct:o.oct};});
 const artists=[
 ['kolsch','Kölsch','singable','A sustained crest','arch',.27],['kalkbrenner','Paul Kalkbrenner','singable','A small, singable answer','fall',.35],
 ['ihm','I Hate Models','rave','Repeated emotional lead','rise',.38],['hoffstadt','Marlon Hoffstadt','rave','Bouncy repeated calls','bounce',.5],['klang','Klangkuenstler','hardtech','Insistent short attacks','flat',.6],
 ['innellea','Innellea','afterlife','A sculpted contour','arch',.2],['devries','Kevin de Vries','afterlife','A patient high landing','rise',.35],['mindagainst','Mind Against','afterlife','A restrained answer','fall',.32],['massano','Massano','afterlife','Repeated centre, one crest','arch',.55],
 ['beyer','Adam Beyer','driving','A compact stab hook','flat',.6],['karla','Karla Blum','driving','A clipped rhythmic reply','bounce',.45],
 ['klock','Ben Klock','hypnotic','One anchor, changing accents','flat',.78],['rodhad','Rødhåd','hypnotic','A slow interval turn','fall',.65],['mulero','Oscar Mulero','hypnotic','A displaced small cell','flat',.8],['hawtin','Richie Hawtin / Plastikman','minimaltech','Negative space and repetition','flat',.85],
 ['sims','Ben Sims','hardgroove','Percussive call and response','bounce',.6],['chlar','Chlär','hardgroove','A skipping two-bar pocket','bounce',.55],['rush','DJ Rush','hardgroove','An emphatic low hook','flat',.65],
 ['perc','Perc','industrial','A low repeated interval','flat',.8],['vtss','VTSS','industrial','An angular EBM response','bounce',.55],['snts','SNTS','industrial','A dark central anchor','flat',.85],
 ['indira','Indira Paganotto','psytech','Rolling modal motion','bounce',.55],['reinier','Reinier Zonneveld','acid','An accented acid cell','rise',.55],
 ['deadmau5','deadmau5','progressive','A patient recurring motif','arch',.4],['prydz','Eric Prydz','progressive','A repeated high anchor','rise',.48],['lane8','Lane 8','melodic','A warm falling reply','fall',.28],['bohmer','Ben Böhmer','melodic','Small moves and open landings','arch',.32],
 ['tiesto','Tiësto / classic trance','trance','Repeated pluck and release','rise',.5],['tiestoclub','Tiësto / club','futurerave','Short call, broad answer','bounce',.5],['pvd','Paul van Dyk','trance','A driving repeated cell','rise',.55],['chicane','Chicane','trance','A spacious melodic landing','fall',.3],
 ['bicep','Bicep','breaks','A recurring offbeat phrase','arch',.4],['bonobo','Bonobo','breaks','Small melodic connections','fall',.25],['disclosure','Disclosure','garage','A short shuffled response','bounce',.45],['fred','Fred again..','stutter','Fragment, repeat, release','arch',.65],
 ['daft','Daft Punk','disco','A repeated rising cell','bounce',.5],['peggy','Peggy Gou','italo','A light octave-aware reply','arch',.4],['kerri','Kerri Chandler','deep','A soulful rhythmic turn','fall',.35],['blackcoffee','Black Coffee','afro','A recurring percussive call','bounce',.6],
 ['boris','Boris Brejcha','minimaltech','A playful interval answer','bounce',.4],['bodzin','Stephan Bodzin','afterlife','A longer expressive landing','arch',.25],['charlotte','Charlotte de Witte','acid','A narrow insistent figure','flat',.7],['astrix','Astrix','psy','An anchor with modal pickups','bounce',.7],
 // Expanded edition perspectives. Options shape the writing: echo (bar-two call and answer), oct (octave-jump chance), reg (register shift),
 // len (articulation), leap (largest step), density (attack density), plus tempo, scale, swing, pitch reach and preview sound.
 // Techno
 ['amelie','Amelie Lens','acidtechno','A rising acid call with rave pressure','rise',.55,{oct:.14,density:.85}],['emmanueltop','Emmanuel Top','acidtechno','An acid line that never lets go','flat',.62,{oct:.28,len:1.1}],
 ['sangiuliano','Enrico Sangiuliano','bigroomtechno','A huge single-note stab statement','flat',.72,{len:.8}],['dax','Dax J','darkstab','A relentless stab with rave urgency','bounce',.6,{bpm:140,density:.75,oct:.1}],
 ['taleofus','Tale Of Us','melodicseq','A melancholic, slowly turning sequence','fall',.3,{mode:'harmonic',span:7}],['anyma','Anyma','melodicseq','A futuristic arpeggio with an octave lift','climb',.25,{oct:.12,bpm:125}],
 ['artbat','ARTBAT','melodicseq','A bold riff answered in bar two','pedal',.35,{echo:true,oct:.15}],['mathame','Mathame','melodicseq','A spacey sequence with a sudden crest','climb',.3,{leap:5,sound:'resonant-lead'}],
 ['colyn','Colyn','modular','An arpeggio that keeps resolving upward','climb',.35,{span:7}],['dozzy','Donato Dozzy','modular','A soft, endlessly rotating sequence','zigzag',.5,{density:.85,sound:'glass-pluck'}],
 ['lucy','Lucy','deeptechno','Slowly phasing tones in deep space','arch',.7,{density:.8}],
 ['trym','Trym','trancetechno','A sharp, driving trance-techno arp','pedal',.45,{bpm:150}],['spfdj','SPFDJ','trancetechno','A fast, dark trance-techno cell','flat',.6,{bpm:145,mode:'phrygian',len:.8}],
 ['heartstring','DJ Heartstring','eurobounce','Euphoric eurodance hooks at pace','arch',.4,{echo:true}],['godfather','DJ Godfather','ghettotech','A rapid-fire chopped hook','flat',.55,{len:.8}],
 ['sara','Sara Landry','hardtech','A hard, ritualistic repeated attack','flat',.7,{bpm:155,oct:.1}],['blawan','Blawan','ukbass','A dented, swung low-register motif','flat',.65,{len:.7}],
 ['surgeon','Surgeon','birmingham','A mechanical loop with a sly swing','flat',.75,{len:.75}],['regis','Regis','industrial','A cold, looping post-punk pulse','fall',.7,{len:.75,density:1.15}],['liebing','Chris Liebing','schranz','A grinding, repeated low loop','flat',.8,{reg:-12}],
 ['cari','Cari Lekebusch','loop','A crunchy, looping percussive cell','bounce',.6,{density:.8,len:.7}],['joelmull','Joel Mull','loop','A warm melodic loop with Swedish swing','arch',.45,{sound:'electric-keys',len:1.4}],
 ['capriati','Joseph Capriati','groovetech','A funky, chant-like groove','bounce',.5,{len:1.2}],['osuna','Paco Osuna','groovetech','A tight, playful vocal-chop game','zigzag',.5,{len:.75}],
 ['mills','Jeff Mills','detroit','A futurist, rapidly looping tonal figure','pedal',.55,{bpm:134,sound:'metal-bell'}],['derrickmay','Derrick May','detroit','A syncopated, strings-like romance','arch',.3,{sound:'slow-strings',len:1.2}],
 ['carlcraig','Carl Craig','detroit','A cosmic, slowly evolving phrase','climb',.35,{len:1.35}],['hood','Robert Hood','minimaltech','A funky, stripped-back minimal loop','bounce',.6,{swing:14,len:.7,density:1.2}],
 ['anfisa','Anfisa Letyago','driving','A dark, vocal-like riff with punch','bounce',.5,{swing:6,len:1.3,oct:.1}],['adriatique','Adriatique','afterlife','A velvet, suspended melodic call','arch',.3,{bpm:122,len:1.15}],
 // House
 ['solomun','Solomun','melodic','A dramatic, deep melodic hook','arch',.35,{mode:'minor',echo:true}],['ame','Âme','melodic','A hypnotic riff that slowly brightens','climb',.45,{mode:'dorian',len:.8}],
 ['joris','Joris Voorn','progseq','A tender riff repeating over shifting chords','arch',.35,{echo:true}],['sasha','Sasha','progseq','A lush sequence with an emotional crest','climb',.3],
 ['digweed','John Digweed','progseq','A tough, hypnotic progressive loop','flat',.55,{density:.9}],['cattaneo','Hernán Cattáneo','progseq','A slowly blooming progressive journey','arch',.35,{len:1.15,bpm:122}],
 ['frankie','Frankie Knuckles','chicago','A soulful, uplifting jack riff','arch',.35,{mode:'dorian',sound:'electric-keys',reg:12}],['greenvelvet','Green Velvet','chicago','A quirky, jacking low hook','flat',.6,{bpm:126,len:.8}],
 ['marshall','Marshall Jefferson','pianohouse','A rolling piano call from the jack era','bounce',.4,{bpm:122,echo:true}],
 ['djpierre','DJ Pierre','acidhouse','A slow-opening acid squelch','rise',.5,{oct:.22,len:1.2}],['hardfloor','Hardfloor','acidhouse','A 303 line twisting into octaves','zigzag',.45,{oct:.3,bpm:128}],
 ['mau','Masters At Work','soulful','A Latin-soul keys phrase with space','arch',.35,{swing:30,density:.85}],
 ['larryheard','Larry Heard','deep','A dreamy, sustained deep-house melody','fall',.3,{len:1.3,sound:'soft-mono'}],['moodymann','Moodymann','deep','A dusty soulful loop with a lazy swing','bounce',.45,{swing:40,len:.8}],
 ['toddterry','Todd Terry','organhouse','A punchy organ-and-drum hook','bounce',.55,{oct:.15}],
 ['mk','MK','vocalhouse','Chopped vocal phrases in a bouncy dub','bounce',.45,{sound:'vocal-chop',len:.7}],['honey','Honey Dijon','vocalhouse','A glamorous vocal hook with a club snap','arch',.4,{echo:true}],
 ['avh','Armand Van Helden','speedgarage','A pitched bass riff with swagger','bounce',.5,{len:1.25}],['toddedwards','Todd Edwards','garage','Scattered, pitched vocal fragments','zigzag',.35,{len:.6,sound:'vocal-chop'}],
 ['chrislake','Chris Lake','techhouse','A cheeky, sparse low hook','bounce',.55,{reg:-12,density:.9}],['fisher','FISHER','techhouse','A big, simple, repeated party hook','flat',.65,{echo:true}],
 ['johnsummit','John Summit','techhouse','A punchy riff with a vocal edge','bounce',.5,{sound:'vocal-chop',len:.75,oct:.1}],
 ['hotsince82','Hot Since 82','deeptech','A deep, rolling vocal-style groove','fall',.45,{len:1.2}],['jamiejones','Jamie Jones','deeptech','A playful synth hook over a deep groove','arch',.45,{sound:'digital-pluck',oct:.12}],
 ['heldens','Oliver Heldens','futurehouse','A bouncy lead with a quick reply','bounce',.45,{echo:true,oct:.15}],['tchami','Tchami','futurehouse','A darker, gospel-tinted chop','fall',.4,{mode:'dorian',len:1.2}],
 ['acslater','AC Slater','basshouse','A snarling bass-house call','bounce',.55,{oct:.22,len:.8}],
 ['justice','Justice','electrohouse','A distorted, operatic riff with punch','arch',.4,{oct:.2,len:1.3}],['boysnoize','Boys Noize','electrohouse','A raw, acid-tinged electro riff','flat',.6,{oct:.15,len:.7,sound:'acid-squelch'}],
 ['seinfeld','DJ Seinfeld','lofi','A wistful, washed-out keys phrase','fall',.35,{len:1.2}],['rff','Ross From Friends','lofi','A nostalgic, broken-up melodic loop','zigzag',.4,{density:.9}],
 ['rhadoo','Rhadoo','rominimal','A long, wandering low groove','bounce',.55,{density:.85,len:1.3}],['petre','Petre Inspirescu','rominimal','A delicate, jazzy minimal line','arch',.4,{len:1.2,reg:12,sound:'electric-keys'}],
 ['villalobos','Ricardo Villalobos','micro','A loose, wandering micro-melody','zigzag',.45],
 ['andme','&ME','afro','A spacious, hypnotic afro-house call','arch',.45,{density:1.25,len:1.2}],['rampa','Rampa','afro','A deep, low-slung melodic groove','fall',.5,{reg:-12,sound:'rubber-bass'}],
 ['adamport','Adam Port','afro','A catchy, vocal-like afro hook','bounce',.4,{echo:true}],
 ['caiiro','Caiiro','afrotech','A dark three-step melodic cycle','pedal',.5],['enoonapa','Enoo Napa','afrotech','A tribal, rolling melodic sequence','zigzag',.45],
 ['bedouin','Bedouin','organic','A desert-toned modal phrase','arch',.3,{mode:'harmonic',len:1.1}],['monolink','Monolink','organic','A plaintive, sung line with long landings','fall',.25,{len:1.2,sound:'soft-mono'}],
 ['bk','BK','hardhouse','Pumping hard-house stabs','bounce',.55,{oct:.12,len:.8}],
 // Disco and trance
 ['purpledisco','Purple Disco Machine','disco','A sunny, funky disco hook','bounce',.45,{mode:'major',echo:true}],
 ['terje','Todd Terje','nudisco','A playful cosmic arpeggio','climb',.3],['lindstrom','Lindstrøm','nudisco','A long, spiralling space-disco line','zigzag',.35],
 ['armin','Armin van Buuren','uplifting','A soaring uplifting arpeggio','climb',.3],['abgt','Above & Beyond','uplifting','An emotional, singable trance phrase','arch',.3,{echo:true}]
 ].map(([id,name,style,focus,contour,repeat,o={}])=>({id,name,style,focus,contour,repeat,...o}));
 return {rhythms,shapes,kinds,families,styles,artists};
})();
