import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.dirname(here);
const core=['catalog.js','artists.js','sounds.js','engine.js','artist-engine.js'].map(f=>fs.readFileSync(path.join(root,'v2-src',f),'utf8')).join('\n')+'\n'+['audio.js','sounds.js','catalog.js','engine.js'].map(f=>fs.readFileSync(path.join(here,f),'utf8')).join('\n');
const ctx={TextEncoder,Uint8Array,DataView,module:{exports:{}}};vm.createContext(ctx);vm.runInContext(core+'\nthis.V=V3;this.Z=zipBytes;this.sound=soundById;',ctx);const F=ctx.V,plain=x=>JSON.parse(JSON.stringify(x));
function parseMidi(bytes){const b=Buffer.from(bytes);let p=0;const str=n=>{const s=b.toString('ascii',p,p+n);p+=n;return s},u16=()=>{const n=b.readUInt16BE(p);p+=2;return n},u32=()=>{const n=b.readUInt32BE(p);p+=4;return n},vlq=()=>{let n=0,c=0,x;do{x=b[p++];n=n*128+(x&127);assert.ok(++c<=4)}while(x&128);return n};assert.equal(str(4),'MThd');assert.equal(u32(),6);const format=u16(),count=u16(),ppq=u16(),tracks=[];assert.equal(ppq,480);for(let tr=0;tr<count;tr++){assert.equal(str(4),'MTrk');const size=u32(),end=p+size;let tick=0,eot=false,on=0;const active=new Map();while(p<end){tick+=vlq();const status=b[p++];if(status===255){const type=b[p++],len=vlq();if(type===47){eot=true;assert.equal(active.size,0);assert.equal(len,0)}p+=len;}else{assert.ok([128,144].includes(status&240));const note=b[p++],vel=b[p++],key=(status&15)+':'+note;assert.ok(note<=127&&vel<=127);if((status&240)===144&&vel>0){assert.ok(!active.has(key));active.set(key,tick);on++;}else{assert.ok(active.has(key));assert.ok(tick>active.get(key));active.delete(key);}}}assert.equal(p,end);assert.ok(eot);tracks.push({tick,on});}assert.equal(p,b.length);return {format,count,tracks};}
function validateNotes(ns,beats){for(const n of ns){assert.ok(Number.isFinite(n.t)&&n.t>=0&&n.t<beats);assert.ok(n.d>0&&n.t+n.d<=beats+.003);assert.ok(Number.isInteger(n.p)&&n.p>=0&&n.p<=127);assert.ok(Number.isInteger(n.v)&&n.v>0&&n.v<=127);}}
assert.equal(F.D.styles.length,69);assert.equal(F.D.artists.length,120);
assert.equal(new Set(F.D.styles.map(s=>s.id)).size,69);assert.equal(new Set(F.D.artists.map(a=>a.id)).size,120);
// The expanded edition appends to the catalog. The original 36 styles and 43 artists must still reproduce every seed exactly.
{const hash=x=>crypto.createHash('sha1').update(JSON.stringify(x)).digest('hex').slice(0,16),legacy=JSON.parse(fs.readFileSync(path.join(here,'legacy-fingerprints.json'),'utf8'));
 const run=c=>{const m=F.melody(c),tr=F.accompaniment(m,c);return hash([F.signature(m),Object.fromEntries(Object.entries(tr).map(([k,v])=>[k,F.signature(v)])),['rhythm','pitch','ending'].map(k=>F.signature(F.mutate(m,c,k,c.seed+5))),F.signature(F.performed(tr.melody,c,'melody')),F.progression(c),c]);};
 for(const [id,expected] of Object.entries(legacy.styles)){const hs=[];for(let i=0;i<25;i++)for(const emotion of ['native','yearning','restless']){const c=F.config(id);c.seed=1000+i*7919;c.emotion=emotion;c.space=[0,22,35,60,75][i%5];hs.push(run(c));}assert.equal(hash(hs),expected,'original style changed: '+id);}
 for(const [id,expected] of Object.entries(legacy.artists)){const hs=[];for(let i=0;i<25;i++){const c=F.config(F.getArtist(id).style,id);c.seed=2000+i*7919;c.space=[0,22,35,60,75][i%5];hs.push(run(c));}assert.equal(hash(hs),expected,'original artist changed: '+id);}
 assert.equal(Object.keys(legacy.styles).length,36);assert.equal(Object.keys(legacy.artists).length,43);}
console.log('PASS: the original 36 styles and 43 artist perspectives reproduce every fingerprinted seed exactly.');
let cases=0,distinctCounts=[],stats=[],heldHook=0;const kindStats={};
for(const s of F.D.styles){assert.ok(ctx.sound(s.sound,'melody'),s.id+' sound');for(const id of [s.bassSound,s.chordSound].filter(Boolean))assert.ok(ctx.sound(id,'melody'),s.id+' support sound '+id);if(s.kit)assert.ok(ctx.sound(s.kit,'drums'),s.id+' kit');assert.ok(F.D.families.includes(s.family),s.id+' family');assert.ok(F.D.rhythms[s.kind]&&F.D.shapes[s.kind],s.id+' approach');const signatures=new Set();for(let i=0;i<60;i++){
 const c=F.config(s.id);c.seed=482731+i*7919;const m=F.melody(c);validateNotes(m,8);assert.ok(m.length>=3);assert.equal(F.signature(m),F.signature(F.melody(c)));signatures.add(F.signature(m));
 const phrase=F.phrase(m,c);validateNotes(phrase,c.bars*4);const first=phrase.filter(n=>n.t<8),second=phrase.filter(n=>n.t>=8&&n.t<16).map(n=>({...n,t:n.t-8}));assert.equal(F.signature(first),F.signature(second),s.id+' repeat identity');
 const pitches=ns=>ns.map(n=>n.p).join(',');const locked=m.map((n,j)=>({...n,locked:j%3===0}));for(const kind of ['rhythm','pitch','ending']){const changed=F.mutate(locked,c,kind,c.seed+19);validateNotes(changed,8);for(const n of locked.filter(n=>n.locked))assert.deepEqual(plain(changed.find(x=>x.id===n.id)),plain(n),s.id+' protected '+kind);if(kind==='rhythm')assert.equal(pitches(changed),pitches(locked),s.id+' rhythm preserves pitch order');if(kind==='pitch')assert.deepEqual(changed.map(n=>[n.t,n.d]),locked.map(n=>[n.t,n.d]));if(kind==='ending')assert.deepEqual(plain(changed.filter(n=>n.t<4)),plain(locked.filter(n=>n.t<4)));}
 const tr=F.accompaniment(m,c);for(const ns of Object.values(tr))validateNotes(ns,32);assert.equal(F.signature(tr.melody),F.signature(phrase));
 const mi=parseMidi(F.midi(tr,c));assert.equal(mi.format,1);assert.equal(mi.count,6);assert.ok(mi.tracks.every(t=>t.tick===15360));cases++;
 const met=F.metrics(m);stats.push(met);if(['hook','cinematic'].includes(s.kind)&&met.held)heldHook++;
 const k=kindStats[s.kind]??={motifs:0,range:0,repeat:0,notes:0};k.motifs++;k.range+=met.range;k.repeat+=met.repeat;k.notes+=met.notes;
 }distinctCounts.push({style:s.id,count:signatures.size});assert.ok(signatures.size>=55,s.id+' needs broad seed variation');}
console.log('PASS:',cases,'style/seed cases; motif identity, determinism, protected notes, selective operations and multitrack MIDI.');
let artistCases=0;const artistDistinct=[];
for(const a of F.D.artists){
 const s=F.getStyle(a.style),c0=F.config(a.style,a.id);assert.ok(['arch','fall','rise','bounce','flat','zigzag','pedal','climb','answer'].includes(a.contour),a.id+' contour');
 if(a.sound)assert.ok(ctx.sound(a.sound,'melody'),a.id+' sound');for(const key of ['bpm','mode','swing','span'])if(a[key]!==undefined)assert.equal(c0[key],a[key],a.id+' applies '+key);
 if(a.mode)assert.ok(Object.hasOwn(ctx.module.exports.MODES,a.mode),a.id+' mode');assert.ok(c0.bpm>=60&&c0.bpm<=190);
 const signatures=new Set();for(let i=0;i<24;i++){const c={...c0,seed:900001+i*7919,space:[22,35,48,60][i%4]},m=F.melody(c);validateNotes(m,8);assert.ok(m.length>=2,a.id+' motif');signatures.add(F.signature(m));
  const tr=F.accompaniment(m,c);for(const ns of Object.values(tr))validateNotes(ns,32);
  if(a.echo){const bar1=m.filter(n=>n.t<4),bar2=m.filter(n=>n.t>=4);if(bar1.length>=4&&bar2.length===bar1.length)assert.deepEqual(bar2.slice(0,-2).map(n=>[n.t-4,n.p]),bar1.slice(0,-2).map(n=>[n.t,n.p]),a.id+' call and answer');}
  if(i<2){const mi=parseMidi(F.midi(tr,c));assert.equal(mi.count,6);}artistCases++;}
 artistDistinct.push({artist:a.id,count:signatures.size});assert.ok(signatures.size>=20,a.id+' needs seed variation');
}
// New perspectives must write differently from their siblings and from the plain style at the same seed (the app keeps the seed when switching).
// Original pairs are reported, not asserted: changing them would break their seed reproduction.
const legacyArtists=new Set(Object.keys(JSON.parse(fs.readFileSync(path.join(here,'legacy-fingerprints.json'),'utf8')).artists));let newSame=0,newTotal=0,legacySame=0,legacyTotal=0;
for(const s of F.D.styles){const ids=['',...F.D.artists.filter(a=>a.style===s.id).map(a=>a.id)];if(ids.length<2)continue;let same=0,total=0;
 for(let i=0;i<12;i++){const seen=ids.map(id=>{const c=F.config(s.id,id);c.seed=77001+i*104729;return F.signature(F.melody(c));});for(let x=0;x<seen.length;x++)for(let y=x+1;y<seen.length;y++){const legacyPair=[ids[x],ids[y]].every(id=>!id||legacyArtists.has(id));if(legacyPair){legacyTotal++;if(seen[x]===seen[y])legacySame++;continue;}total++;if(seen[x]===seen[y])same++;}}
 newSame+=same;newTotal+=total;if(total)assert.ok(same<=Math.max(1,Math.floor(total*.05)),s.id+' new perspectives are too similar ('+same+'/'+total+')');}
assert.ok(newSame/newTotal<.01,'new perspectives overall too similar');
// New styles that share a writing approach must not write the same motif at the same seed (the app keeps the seed when switching styles).
{let same=0,total=0;const fresh=F.D.styles.filter(s=>s.salt);assert.equal(fresh.length,33);assert.ok(F.D.styles.filter(s=>!s.salt).length===36);
 for(const s of fresh)for(const t of F.D.styles.filter(t=>t.kind===s.kind&&t.id!==s.id))for(let i=0;i<10;i++){const a=F.config(s.id),b=F.config(t.id);a.seed=b.seed=31337+i*7919;const pa=F.melody(a),pb=F.melody(b);total++;if(JSON.stringify(pa.map(n=>[n.t,n.d]))===JSON.stringify(pb.map(n=>[n.t,n.d])))same++;}
 assert.ok(same/total<.03,'new styles share rhythms with same-approach styles ('+same+'/'+total+')');}
// Distinctive expanded-edition traits are audible in the notes, not only labels.
const octaveHits=F.D.artists.filter(a=>a.oct>=.2).map(a=>{let jumps=0;for(let i=0;i<20;i++){const c=F.config(a.style,a.id);c.seed=5000+i*7919;const m=F.melody(c);jumps+=m.slice(1).filter((n,j)=>Math.abs(n.p-m[j].p)>=12).length;}return jumps;});assert.ok(octaveHits.length>=4&&octaveHits.every(j=>j>0),'octave perspectives produce octave leaps');
{const acid=[],seq=[];for(let i=0;i<40;i++){const c=F.config('acidtechno');c.seed=6000+i*7919;const m=F.melody(c);acid.push(m.some((n,j)=>m[j+1]&&Math.abs(n.t+n.d-m[j+1].t)<.003&&m[j+1].t-n.t>.2));const q=F.config('melodicseq');q.seed=6000+i*7919;seq.push(F.metrics(F.melody(q)).range);}
 assert.ok(acid.filter(Boolean).length>=20,'acid lines include legato slides');assert.ok(seq.reduce((a,b)=>a+b,0)/seq.length>=7,'melodic sequences use a wider chord-tone range');}
{const house=F.accompaniment(F.melody(F.config('pianohouse')),F.config('pianohouse'));assert.ok(house.drums.some(n=>n.p===46),'house styles use open hats');assert.ok(house.chords.filter(n=>n.t<8).length>=24,'piano house chords rock in a syncopated pocket');
 const three=F.accompaniment(F.melody(F.config('afrotech')),F.config('afrotech'));assert.deepEqual(plain(three.drums.filter(n=>n.p===36&&n.t<4).map(n=>n.t)),[0,1.5,3],'afro tech uses a three-step kick');}
console.log('PASS:',artistCases,'artist/seed cases across',F.D.artists.length,'perspectives; overrides, call-and-answer, distinct siblings, octave, slide and groove traits.');
for(const mode of Object.keys(ctx.module.exports.MODES))for(const rootNote of [0,6,11])for(const bars of [8,16])for(const space of [0,75]){
 const c={...F.config('singable'),mode,root:rootNote,bars,space,life:100,swing:60},m=F.melody(c);for(const role of Object.keys(F.accompaniment(m,c))){const ns=F.performed(F.accompaniment(m,c)[role],c,role);validateNotes(ns,bars*4);}const mi=parseMidi(F.midi(F.accompaniment(m,c),c));assert.ok(mi.tracks.every(t=>t.tick===bars*4*480));}
console.log('PASS: all modes, root extremes, phrase lengths and performance extremes.');
let packCount=0;for(const artists of [false,true]){const files=F.library(artists),info=F.pack(artists);let count=0;for(const file of files.filter(f=>f.name.endsWith('.mid'))){const parsed=parseMidi(file.bytes);assert.ok(parsed.tracks.every(t=>t.tick===15360));count++;}assert.equal(count,info.midi);packCount+=count;assert.deepEqual(Buffer.from(ctx.Z(files)),fs.readFileSync(path.join(root,info.name)));}
assert.equal(packCount,2064);console.log('PASS: all',packCount,'delivered MIDI files; archives exactly reproduce from the generator.');
const imported=F.parseMidi(F.midi({melody:F.phrase(F.melody(F.config()),F.config())},F.config()));assert.equal(imported.tracks.length,1);validateNotes(F.importMotif(imported.tracks[0]),8);assert.throws(()=>F.parseMidi(new Uint8Array([1,2,3])));
// Running-status input, two simultaneous pitches, explicit end of track, and a non-default PPQ.
const fixture=Uint8Array.from([77,84,104,100,0,0,0,6,0,0,0,1,0,96,77,84,114,107,0,0,0,19,0,144,60,90,0,64,80,96,128,60,0,0,64,0,0,255,47,0]);
// Correct track length is calculated from the event payload.
fixture[21]=fixture.length-22;const parsed=F.parseMidi(fixture);assert.equal(parsed.tracks[0].notes.length,2);const imp=F.importMotif(parsed.tracks[0]);assert.equal(imp.length,1);assert.equal(imp[0].p,64);assert.equal(imp[0].d,1);assert.throws(()=>F.parseMidi(fixture.subarray(0,fixture.length-1)));
console.log('PASS: MIDI import, running status, polyphonic reduction and malformed-file rejection.');
// UI smoke tests execute the actual app with a minimal DOM. They are not browser/listening QA.
const elements=new Map();function el(id){if(!elements.has(id))elements.set(id,{id,value:'',textContent:'',innerHTML:'',disabled:false,checked:false,files:[],dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},querySelectorAll(){return[]},matches(){return false},click(){this.onclick?.({target:this})},showModal(){this.open=true},close(){this.open=false},appendChild(){},remove(){}});return elements.get(id);}
let hooks;const ui={TextEncoder,Uint8Array,DataView,module:{exports:{}},document:{getElementById:el,querySelector(){return null},addEventListener(){},body:{appendChild(){}},createElement(){return el('download')}},window:{addEventListener(){}},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame:()=>0,cancelAnimationFrame(){},Blob,URL,V3_TEST_HOOK:h=>hooks=h};vm.createContext(ui);vm.runInContext(core+'\n'+fs.readFileSync(path.join(here,'app.js'),'utf8'),ui);
const before=JSON.stringify(hooks.getState().motif);el('newIdea').click();assert.notEqual(JSON.stringify(hooks.getState().motif),before);el('undo').click();assert.equal(JSON.stringify(hooks.getState().motif),before);el('redo').click();assert.notEqual(JSON.stringify(hooks.getState().motif),before);
el('saveBranch').click();assert.equal(hooks.getState().shelf.length,1);const valid=hooks.validateSession(plain(hooks.getState()));assert.equal(valid.version,3);const bad=plain(valid);bad.shelf[0].motif[0].p=300;assert.throws(()=>hooks.validateSession(bad));
const current=hooks.getState();current.motif[0].locked=true;const protectedNote=JSON.stringify(current.motif[0]);el('newIdea').click();assert.ok(hooks.getState().motif.some(n=>JSON.stringify(n)===protectedNote));
const beforeSound=JSON.stringify(hooks.getState().motif);el('parts').onchange({target:{dataset:{sound:'melody'},value:'soft-pluck'}});assert.equal(JSON.stringify(hooks.getState().motif),beforeSound);
el('viewPhrase').click();assert.equal(hooks.getState().view,'phrase');assert.ok(el('roll').innerHTML.includes('data-note'));assert.ok(el('variantCards').innerHTML.includes('Use this'));assert.ok(el('styleList').innerHTML.includes('Big melodic hooks'));
const target=value=>({closest:()=>({dataset:value})});
for(const s of F.D.styles){el('styleList').onclick({target:target({style:s.id})});const state=hooks.getState();assert.equal(state.c.style,s.id);assert.equal(el('approachTitle').textContent,hooks.approaches[s.kind][0]);assert.ok(el('exercise').textContent.length>20,s.id+' exercise');for(const role of ['melody','bass','chords','arp','drums'])assert.ok(ctx.sound(state.mix[role].sound,role),s.id+' '+role+' preview sound');}
for(const a of F.D.artists){el('artist').value=a.id;el('artist').onchange();const state=hooks.getState();assert.equal(state.c.artist,a.id);assert.equal(state.c.style,a.style);if(a.sound)assert.equal(state.mix.melody.sound,a.sound);for(const role of ['melody','bass','chords','arp','drums'])assert.ok(ctx.sound(state.mix[role].sound,role),a.id+' '+role+' preview sound');assert.ok(el('artistChips').innerHTML.includes('data-artist="'+a.id+'"'),a.id+' chip');}
assert.ok(el('artist').innerHTML.includes('<optgroup label="House'),'artist menu is grouped by family');
el('artistChips').onclick({target:target({artist:''})});assert.equal(hooks.getState().c.artist,'');assert.equal(hooks.getState().c.bpm,F.getStyle(hooks.getState().c.style).bpm,'returning to the style perspective restores style defaults');
el('familyFilter').onclick({target:target({family:'House'})});const houseList=el('styleList').innerHTML;assert.ok(houseList.includes('Chicago jack')&&!houseList.includes('Dark stab techno'),'family filter');el('familyFilter').onclick({target:target({family:'All'})});
el('search').value='kolsch';renderSearch();assert.ok(el('styleList').innerHTML.includes('Big melodic hooks'),'accent-insensitive artist search');el('search').value='';renderSearch();
function renderSearch(){el('search').oninput();}
assert.ok(el('packText').textContent.startsWith('69 styles. 120 artist'));assert.ok(el('stylePack').textContent.includes('1,104'));
console.log('PASS: UI bootstrap, generation, undo/redo, shelf, session validation, protected generation, sound/MIDI separation, every style and artist in the UI, family filter and search.');
const report={cases,artistCases,sameSeedIdenticalMotifs:{pairsWithNewPerspectives:`${newSame}/${newTotal}`,originalPairs:`${legacySame}/${legacyTotal}`},distinctSeeds:distinctCounts,distinctArtistSeeds:artistDistinct,byApproach:Object.fromEntries(Object.entries(kindStats).map(([k,v])=>[k,{motifs:v.motifs,meanNotes:+(v.notes/v.motifs).toFixed(2),meanRange:+(v.range/v.motifs).toFixed(2),meanAdjacentRepeatPercent:+(v.repeat/v.motifs).toFixed(1)}])),meanRange:stats.reduce((s,x)=>s+x.range,0)/stats.length,meanAdjacentRepeatPercent:stats.reduce((s,x)=>s+x.repeat,0)/stats.length,hookAndCinematicWithHolds:heldHook,note:'Structural diagnostics, not a musical quality score. No claim of actual Ableton audition.'};fs.writeFileSync(path.join(here,'validation.json'),JSON.stringify(report,null,2));console.log('Diagnostics:',JSON.stringify({meanRange:report.meanRange,meanAdjacentRepeatPercent:report.meanAdjacentRepeatPercent,minimumDistinctSeeds:Math.min(...distinctCounts.map(s=>s.count)),minimumDistinctArtistSeeds:Math.min(...artistDistinct.map(s=>s.count))}));
console.table(report.byApproach);
