const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={id:'source-1',variant:'original',shift:0,bpm:138,voice:'anthem',chordMode:'sustain',roll:'melody',source:'all',style:'all',artistStyle:'all',sound:'supersaw',artist:null,arrangement:'uplifting',arrangementIndex:0,volume:.55,mutes:{melody:true,chords:true,bass:true,drums:true},favorites:[]};
let sketch,toastTimer,soundTimer,previewGraph=null,previewNodes=new Set(),previewToken=0;
function notify(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3600);}
function save(){try{localStorage.setItem('fieldwork-trance-v1',JSON.stringify({id:state.id,variant:state.variant,shift:state.shift,bpm:state.bpm,voice:state.voice,chordMode:state.chordMode,volume:state.volume,mutes:state.mutes,favorites:state.favorites}));}catch{}}
function restore(){try{const s=JSON.parse(localStorage.getItem('fieldwork-trance-v1'));if(!s||typeof s!=='object')return;if(library.some(x=>x.id===s.id))state.id=s.id;if(TREATMENTS.some(t=>t[0]===s.variant))state.variant=s.variant;if(Number.isInteger(s.shift)&&s.shift>=-5&&s.shift<=6)state.shift=s.shift;if(Number.isFinite(s.bpm)&&s.bpm>=100&&s.bpm<=170)state.bpm=s.bpm;if(SOUNDS.some(x=>x.id===s.voice))state.voice=s.voice;if(['sustain','pulse','arp'].includes(s.chordMode))state.chordMode=s.chordMode;if(Number.isFinite(s.volume)&&s.volume>=0&&s.volume<=1)state.volume=s.volume;if(s.mutes)for(const p of Object.keys(state.mutes))if(typeof s.mutes[p]==='boolean')state.mutes[p]=s.mutes[p];state.favorites=Array.isArray(s.favorites)?s.favorites.filter(id=>library.some(x=>x.id===id)):[];}catch{}}
const current=()=>library.find(x=>x.id===state.id);
function syncPressed(selector,key,value){document.querySelectorAll(selector).forEach(b=>{const on=b.dataset[key]===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
function renderLibrary(){const q=$('search').value.trim().toLowerCase(),items=library.filter(s=>(state.source==='all'||s.source===(state.source==='source'))&&(state.style==='all'||s.style===state.style)&&[s.name,s.file||'',s.style,...(s.source?[]:['original study'])].join(' ').toLowerCase().includes(q));$('libraryCount').textContent=items.length+' STUDIES';$('melodyList').innerHTML=items.length?items.map(s=>`<button class="melody-item ${state.id===s.id?'active':''}" data-study="${s.id}" aria-pressed="${state.id===s.id}"><span class="num">${String(library.indexOf(s)+1).padStart(2,'0')}</span><span><strong>${esc(s.name)}${state.favorites.includes(s.id)?' ★':''}</strong><small>${s.source?'YOUR MIDI':'NEW STUDY'} · ${s.beats/4} BARS · ${s.style.toUpperCase()}</small></span><span class="mini-wave" aria-hidden="true"><i></i><i></i><i></i><i></i></span></button>`).join(''):'<p class="empty">No melodies match. Try another search or style.</p>';syncPressed('#sourceTabs button','source',state.source);}
function renderRoll(){const notes=sketch[state.roll],low=Math.floor(Math.min(...notes.map(n=>n.n))-2),high=Math.ceil(Math.max(...notes.map(n=>n.n))+2),range=high-low+1,W=900,H=227,left=43,top=23,innerW=W-left-9,row=(H-top-8)/range,x=t=>left+t/sketch.beats*innerW,y=n=>top+(high-n)*row;
 let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="${state.roll} piano roll: ${notes.length} notes over ${sketch.beats/4} bars"><title>${state.roll} notes — ${esc(current().name)}</title><rect width="${W}" height="${H}" fill="#100b10"/>`;
 for(let n=low;n<=high;n++){const black=[1,3,6,8,10].includes(mod(n,12));svg+=`<rect x="${left}" y="${y(n)}" width="${innerW}" height="${row}" fill="${black?'#180e16':'#100b10'}"/><line x1="0" x2="${W}" y1="${y(n)}" y2="${y(n)}" stroke="#34202a" stroke-width=".4"/>`;if(mod(n,12)===0||range<=18&&mod(n,12)%2===0)svg+=`<text x="6" y="${y(n)+row*.75}" fill="#a38291" font-family="Consolas,monospace" font-size="${Math.min(10,row*.8)}">${noteName(n)}</text>`;}
 for(let t=0;t<=sketch.beats;t+=.25){const bar=t%4===0,beat=t%1===0;svg+=`<line x1="${x(t)}" x2="${x(t)}" y1="${top}" y2="${H}" stroke="${bar?'#6e3544':beat?'#38212c':'#24141e'}" stroke-width="${bar?1:.5}"/>`;if(bar&&t<sketch.beats)svg+=`<text x="${x(t)+5}" y="14" fill="#a97887" font-size="9" font-family="Consolas,monospace">${String(t/4+1).padStart(2,'0')}</text>`;}
 notes.forEach(n=>{svg+=`<rect x="${x(n.t)+.6}" y="${y(n.n)+.8}" width="${Math.max(2,n.d/sketch.beats*innerW-1.2)}" height="${Math.max(2,row-1.6)}" rx="1" fill="${state.roll==='melody'?'#f55c56':state.roll==='chords'?'#c685ac':'#e7a15f'}" opacity="${.5+n.v/254}"><title>${noteName(n.n)} · beat ${(n.t+1).toFixed(2)} · ${n.d.toFixed(2)} beats · velocity ${n.v}</title></rect>`;});
 svg+=`<line id="playhead" class="playhead" x1="${left}" x2="${left}" y1="${top}" y2="${H}" opacity="0"/></svg>`;$('pianoRoll').innerHTML=svg;$('rollMeta').textContent=`${sketch.beats/4} BARS · ${notes.length} NOTES`;$('rollCaption').textContent=state.roll==='melody'&&current().source&&state.variant==='original'&&state.shift===0?'Every note from your original MIDI':state.roll==='chords'?'The actual voiced chord notes':state.roll==='bass'?'Bass follows the suggested chord roots':'The current melody treatment';syncPressed('[data-roll]','roll',state.roll);
}
function renderStudio(){const item=current(),style=STYLES.find(x=>x.id===item.style);sketch=makeSketch(item,state);$('studyMeta').textContent=`${item.source?'YOUR MIDI / '+item.file:'ORIGINAL STUDY / '+style.name} · ${item.beats/4} BARS`;$('studyName').textContent=item.name;$('studyDescription').textContent=item.source?item.explain:style.desc;
 $('keySelect').innerHTML=Array.from({length:12},(_,pc)=>{let shift=mod(pc-item.root,12);if(shift>6)shift-=12;return `<option value="${shift}">${PITCHES[pc]} ${item.mode}</option>`;}).join('');$('keySelect').value=state.shift;$('bpm').value=state.bpm;$('voiceSelect').value=state.voice;$('chordMode').value=state.chordMode;$('volume').value=state.volume*100;
 $('variations').innerHTML=TREATMENTS.map(([id,name])=>`<button data-variant="${id}" class="${state.variant===id?'active':''}" aria-pressed="${state.variant===id}">${name}</button>`).join('');$('variationHint').textContent=TREATMENTS.find(t=>t[0]===state.variant)[2];$('variationNumber').textContent=String(TREATMENTS.findIndex(t=>t[0]===state.variant)+1).padStart(2,'0')+' / 06';
 $('chordCards').innerHTML=sketch.harmony.map((c,i)=>`<div class="chord-card"><small>BAR ${String(i+1).padStart(2,'0')}</small><strong>${c.label}</strong><span>${c.notes.map(noteName).join(' · ')}</span><span>TOP ${noteName(c.notes.at(-1))} / ROOT ${pitch(c.root)}</span></div>`).join('');$('harmonyHint').textContent='Suggested harmony · close voice leading · top-line melody: '+sketch.harmony.map(c=>noteName(c.notes.at(-1))).join(' → ')+'.';
 const fav=state.favorites.includes(item.id);$('favorite').textContent=fav?'★':'☆';$('favorite').setAttribute('aria-pressed',String(fav));$('favorite').setAttribute('aria-label',fav?'Remove this study from favourites':'Save this study as a favourite');$('exportSource').hidden=!item.source;$('nowPlaying').textContent=item.name;$('transportInfo').textContent=`${state.bpm} BPM · ${pitch(item.root+state.shift)} ${item.mode.toUpperCase()}`;
 $('delayMath').textContent=`At ${state.bpm} BPM: quarter note = ${Math.round(60000/state.bpm)} ms, eighth = ${Math.round(30000/state.bpm)} ms, dotted eighth = ${Math.round(45000/state.bpm)} ms, sixteenth = ${Math.round(15000/state.bpm)} ms.`;
 document.querySelectorAll('[data-part]').forEach(b=>{b.classList.toggle('on',state.mutes[b.dataset.part]);b.setAttribute('aria-pressed',String(state.mutes[b.dataset.part]));});$('artistExercise').hidden=state.artist===null;if(state.artist!==null){const a=ARTISTS[state.artist];$('artistExercise').innerHTML='<b>'+esc(a[0])+' / Writing exercise.</b> '+esc(a[4]);}renderRoll();renderPosition();save();}
function stopPreview(){previewToken++;clearTimeout(soundTimer);for(const n of previewNodes)try{n.stop();}catch{}previewNodes.clear();previewGraph?.dispose();previewGraph=null;document.querySelector('[data-audition]')?.setAttribute('aria-pressed','false');const b=document.querySelector('[data-audition]');if(b)b.textContent='▷ Audition sound';}
function stopAll(){AudioStudio.stop();stopPreview();updatePlayState();renderPosition();}
function updatePlayState(){$('play').textContent=AudioStudio.playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',AudioStudio.playing?'Stop studio loop':'Play studio loop');$('heroPlay').textContent=AudioStudio.playing?'Ⅱ Stop the signal':'▷ Hear the first signal';document.body.classList.toggle('playing',AudioStudio.playing);}
async function startPlayback(){stopPreview();try{await AudioStudio.start(sketch,state.voice,state.mutes,state.volume);updatePlayState();}catch(error){AudioStudio.stop();updatePlayState();notify('Audio could not start. Press Play to retry in a browser with Web Audio.');console.error(error);}}
function changeStudy(id,scroll=false,voice=null,artist=null){const item=library.find(x=>x.id===id);if(!item)return;const playing=AudioStudio.playing;stopAll();state.artist=artist;state.id=id;state.variant='original';state.shift=0;state.bpm=item.bpm;state.voice=voice||STYLES.find(x=>x.id===item.style).voice;renderStudio();renderLibrary();renderArrangement();if(playing)startPlayback();if(scroll)$('studio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
function updateComposition(){const playing=AudioStudio.playing;stopAll();renderStudio();renderArrangement();if(playing)startPlayback();}
function renderWorlds(){$('worldGrid').innerHTML=STYLES.map((s,i)=>`<article class="world-card"><span class="world-number">0${i+1} / ${esc(s.tag.toUpperCase())}</span><h3>${s.name}</h3><span class="world-bpm">${s.range} BPM / SUGGESTED RANGE</span><p>${s.desc}</p><button class="text-btn" data-world="${s.id}">Explore ${s.name.split(' / ')[0]} <span>↗</span></button></article>`).join('');}
function renderArtists(){const q=$('artistSearch').value.trim().toLowerCase(),items=ARTISTS.map((a,i)=>({a,i})).filter(({a})=>(state.artistStyle==='all'||a[1]===state.artistStyle)&&a.join(' ').toLowerCase().includes(q));$('artistGrid').innerHTML=items.length?items.map(({a,i})=>`<article class="artist-card"><span class="tiny">${a[1].toUpperCase()} / PERSPECTIVE ${String(i+1).padStart(2,'0')}</span><h3>${esc(a[0])}</h3><div class="reference">LISTEN FOR THE IDEA · ${esc(a[2])}</div><p>${esc(a[3])}</p><p class="exercise">${esc(a[4])}</p><button class="text-btn" data-artist="${i}">Open a writing exercise <span>↗</span></button></article>`).join(''):'<p class="empty">No artist perspectives match. Try a different name or style.</p>';syncPressed('[data-artist-filter]','artistFilter',state.artistStyle);}
function renderSounds(){const s=SOUNDS.find(s=>s.id===state.sound);$('soundList').innerHTML=SOUNDS.map((p,i)=>`<button class="sound-choice ${p.id===s.id?'active':''}" data-sound="${p.id}" aria-pressed="${p.id===s.id}"><span class="tiny">${String(i+1).padStart(2,'0')} / ${p.type.toUpperCase()}</span><strong>${p.name}</strong><small>${p.tag}</small></button>`).join('');$('soundRecipe').innerHTML=`<div class="eyebrow red">${s.type.toUpperCase()} / ${s.tag.toUpperCase()}</div><h3>${s.name}</h3><p>${s.desc}</p><ol>${s.steps.map(t=>`<li>${t}</li>`).join('')}</ol><div class="sound-tip"><b>Make it move.</b> ${s.move}</div><div class="sound-tip"><b>If it is not working.</b> ${s.fix}</div><div class="sound-actions"><button class="btn primary" data-audition aria-pressed="false">▷ Audition sound</button><button class="btn secondary" data-use-sound>Use as melody voice ↗</button></div>`;}
async function audition(){if(previewGraph){stopPreview();return;}stopAll();const token=++previewToken;try{AudioStudio.ctx ||= new (window.AudioContext||window.webkitAudioContext)();const ctx=AudioStudio.ctx;await ctx.resume();if(token!==previewToken)return;previewGraph=audioGraph(ctx,ctx.destination,state.bpm,state.volume);const s=SOUNDS.find(s=>s.id===state.sound),low=s.type==='Bass',notes=low?[45,45,45,45]:s.type==='Atmosphere'?[57,60,64,67]:[69,72,76,79,76,72,71,69],beat=60/state.bpm;
 notes.forEach((n,i)=>playTone(ctx,previewGraph.lanes.melody,{n,t:i*.5,d:s.type==='Atmosphere'?3.5:.35,v:94},ctx.currentTime+.04+(s.type==='Atmosphere'?0:i*.5*beat),beat,s.id,previewNodes));const button=document.querySelector('[data-audition]');if(button){button.textContent='■ Stop audition';button.setAttribute('aria-pressed','true');}soundTimer=setTimeout(stopPreview,Math.max(notes.length*.5*beat,3.5*beat)*1000+1200);
 }catch(error){stopPreview();notify('Audio could not start. Please retry with the sound audition button.');console.error(error);}}
function renderArrangement(){const items=ARRANGEMENTS[state.arrangement],total=items.reduce((sum,s)=>sum+s[1],0),seconds=Math.round(total*4*60/state.bpm);$('arrangementLength').textContent=`${total} BARS · ${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,'0')} AT ${state.bpm} BPM`;let start=1;$('energyChart').innerHTML=items.map((s,i)=>{const html=`<button class="energy-block ${state.arrangementIndex===i?'active':''}" data-stage="${i}" style="flex:${s[1]};--energy:${s[2]}%" aria-pressed="${state.arrangementIndex===i}" aria-label="${s[0]}, bars ${start} to ${start+s[1]-1}"><span class="bar-start">${String(start).padStart(3,'0')}</span><span class="bar"></span><span class="energy-label">${s[0].toUpperCase()}<br>${s[1]} BARS</span></button>`;start+=s[1];return html;}).join('');const chosen=items[state.arrangementIndex];$('arrangementDetail').innerHTML=`<h3>${chosen[0]}</h3><p>${chosen[3]}</p>`;syncPressed('[data-arrangement]','arrangement',state.arrangement);}
function renderPosition(){const pos=AudioStudio.position(),bar=Math.floor(pos/4)+1;$('beatDisplay').innerHTML=String(bar).padStart(2,'0')+`<span> / ${String(sketch.beats/4).padStart(2,'0')}</span>`;const line=$('playhead');if(line){const x=43+pos/sketch.beats*848;line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('opacity',AudioStudio.playing?'1':'0');}}
function download(bytes,name,type){const blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function exportPart(part){const parts=part==='full'?['melody','chords','bass','drums']:[part],name=current().id+'-'+state.variant+'-'+pitch(current().root+state.shift).replace('♯','sharp').replace('♭','flat')+'-'+state.bpm+'bpm-'+part+'.mid';download(midiBytes(sketch,parts),name,'audio/midi');notify(part==='full'?'Four MIDI parts exported with tempo and chord voicings.':part[0].toUpperCase()+part.slice(1)+' MIDI exported.');}
async function exportLibrary(){const button=$('downloadLibrary');button.disabled=true;button.textContent='Building your library…';try{await new Promise(resolve=>setTimeout(resolve,40));const files=[];for(const item of library)for(const [variant]of TREATMENTS){files.push({name:`${item.source?'Your-MIDI':'Original-studies'}/${item.id}-${variant}.mid`,bytes:midiBytes(makeSketch(item,{variant,bpm:item.bpm,chordMode:'sustain'}))});}files.push({name:'README.txt',bytes:new TextEncoder().encode('FIELDWORK / TRANCE\n168 arranged MIDI sketches. Each contains melody, suggested chord voicings, bass and drums plus tempo.\n12 supplied melodies x 6 treatments + 16 original studies x 6 treatments.\nSource melodies have no embedded tempo; style tempos are suggestions. Added harmony is an interpretation.\nOriginal treatment preserves melody notes, timing and velocity at the original pitch.\nArtist exercises are original writing prompts, not transcriptions. MIDI contains no synth sounds or effects.\nThe pack uses each study\'s default tempo, original pitch and sustained chords; current studio changes are exported with the individual buttons.\nC4 = MIDI 60; drum map: kick 36, clap 39, closed hat 42.\n')});download(zipBytes(files),'Fieldwork-Trance-168-Sketches.zip','application/zip');notify('168 arranged sketches exported. Each has four separate MIDI parts.');}catch(error){notify('Could not build the library. Individual MIDI exports are still available.');console.error(error);}finally{button.disabled=false;button.textContent='Download all 168 sketches ↓';}}
function init(){restore();$('styleFilter').innerHTML+=[...STYLES].map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('voiceSelect').innerHTML=SOUNDS.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('artistFilters').innerHTML=[['all','All perspectives'],...STYLES.map(s=>[s.id,s.name.split(' / ')[0]])].map(([id,name])=>`<button data-artist-filter="${id}" aria-pressed="${id==='all'}" class="${id==='all'?'active':''}">${name}</button>`).join('');
 renderLibrary();renderStudio();renderWorlds();renderArtists();renderSounds();renderArrangement();
 $('search').addEventListener('input',renderLibrary);$('artistSearch').addEventListener('input',renderArtists);$('styleFilter').addEventListener('change',e=>{state.style=e.target.value;renderLibrary();});
 $('keySelect').addEventListener('change',e=>{state.shift=Number(e.target.value);updateComposition();});$('bpm').addEventListener('change',e=>{const v=Number(e.target.value);if(!Number.isFinite(v)||v<100||v>170){e.target.value=state.bpm;notify('Choose a tempo between 100 and 170 BPM.');return;}state.bpm=Math.round(v);updateComposition();});$('voiceSelect').addEventListener('change',e=>{state.voice=e.target.value;updateComposition();});$('chordMode').addEventListener('change',e=>{state.chordMode=e.target.value;updateComposition();});
 $('volume').addEventListener('input',e=>{state.volume=Number(e.target.value)/100;AudioStudio.volume(state.volume);if(previewGraph)previewGraph.master.gain.setTargetAtTime(state.volume,AudioStudio.ctx.currentTime,.02);save();});
 $('play').addEventListener('click',()=>AudioStudio.playing?stopAll():startPlayback());$('heroPlay').addEventListener('click',()=>AudioStudio.playing?stopAll():startPlayback());$('stop').addEventListener('click',stopAll);
 $('favorite').addEventListener('click',()=>{const index=state.favorites.indexOf(state.id);if(index===-1)state.favorites.push(state.id);else state.favorites.splice(index,1);renderStudio();renderLibrary();notify(index===-1?'Study starred. Your favourites are marked in the library.':'Study removed from favourites.');});
 for(const [id,part]of [['exportSketch','full'],['exportMelody','melody'],['exportChords','chords'],['exportBass','bass']])$(id).addEventListener('click',()=>exportPart(part));$('exportSource').addEventListener('click',()=>{const item=current();if(item.source){download(Uint8Array.from(atob(item.original),c=>c.charCodeAt(0)),item.file,'audio/midi');notify('Original MIDI downloaded without modification.');}});$('downloadLibrary').addEventListener('click',exportLibrary);
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.study)changeStudy(d.study);if(d.source){state.source=d.source;renderLibrary();}if(d.variant){state.variant=d.variant;updateComposition();}if(d.roll){state.roll=d.roll;renderRoll();}if(d.part){state.mutes[d.part]=!state.mutes[d.part];AudioStudio.updateMutes(state.mutes);b.classList.toggle('on',state.mutes[d.part]);b.setAttribute('aria-pressed',String(state.mutes[d.part]));save();}if(d.world){state.source='study';state.style=d.world;$('search').value='';$('styleFilter').value=d.world;changeStudy(d.world+'-0',true);}if(d.artistFilter){state.artistStyle=d.artistFilter;renderArtists();}if(d.artist!==undefined){const a=ARTISTS[Number(d.artist)];state.source='all';state.style='all';$('styleFilter').value='all';$('search').value='';changeStudy(a[1]+'-'+(Number(d.artist)%2),true,a[5],Number(d.artist));notify(a[0]+': '+a[4]);}if(d.sound){stopPreview();state.sound=d.sound;renderSounds();}if('audition'in d)audition();if('useSound'in d){state.voice=state.sound;updateComposition();$('studio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});notify('Melody voice set to '+SOUNDS.find(s=>s.id===state.voice).name+'.');}if(d.arrangement){state.arrangement=d.arrangement;state.arrangementIndex=0;renderArrangement();}if(d.stage!==undefined){state.arrangementIndex=Number(d.stage);renderArrangement();}});
 document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!/INPUT|SELECT|TEXTAREA|BUTTON|A|SUMMARY/.test(e.target.tagName)&&!e.target.isContentEditable){e.preventDefault();AudioStudio.playing?stopAll():startPlayback();}if(e.code==='Escape')stopAll();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAll();});window.addEventListener('pagehide',stopAll);setInterval(()=>{if(AudioStudio.playing)renderPosition();},70);
}
init();
