const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={dev:{},hear:'full',viewStart:0,viewBars:'4',loop:false,id:'example-12-answer',variant:'original',shift:0,bpm:138,voice:'supersaw',chordMode:'sustain',roll:'topline',source:'all',style:'all',artistStyle:'all',sound:'supersaw',artist:null,arrangement:'uplifting',arrangementIndex:0,volume:.55,mutes:{melody:true,chords:true,bass:true,drums:true},favorites:[]};
let sketch,toastTimer,soundTimer,previewGraph=null,previewNodes=new Set(),previewToken=0;
function notify(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3600);}
function save(){try{localStorage.setItem('fieldwork-trance-v2',JSON.stringify({dev:state.dev,hear:state.hear,id:state.id,variant:state.variant,shift:state.shift,bpm:state.bpm,voice:state.voice,chordMode:state.chordMode,volume:state.volume,mutes:state.mutes,favorites:state.favorites}));}catch{}}
function restore(){try{const s=JSON.parse(localStorage.getItem('fieldwork-trance-v2'));if(!s||typeof s!=='object')return;if(['full','upper','chordTop'].includes(s.hear))state.hear=s.hear;if(s.dev&&typeof s.dev==='object'){const d=s.dev;if([8,16].includes(d.bars))state.dev.bars=d.bars;if(['arch','ascent','valley'].includes(d.arc))state.dev.arc=d.arc;if([4,7,10].includes(d.motion))state.dev.motion=d.motion;if(['source','flow','drive'].includes(d.density))state.dev.density=d.density;if(Number.isInteger(d.seed)&&d.seed>=0&&d.seed<10000)state.dev.seed=d.seed;}if(library.some(x=>x.id===s.id))state.id=s.id;if(TREATMENTS.some(t=>t[0]===s.variant))state.variant=s.variant;if(Number.isInteger(s.shift)&&s.shift>=-5&&s.shift<=6)state.shift=s.shift;if(Number.isFinite(s.bpm)&&s.bpm>=100&&s.bpm<=170)state.bpm=s.bpm;if(SOUNDS.some(x=>x.id===s.voice))state.voice=s.voice;if(['sustain','pulse','arp'].includes(s.chordMode))state.chordMode=s.chordMode;if(Number.isFinite(s.volume)&&s.volume>=0&&s.volume<=1)state.volume=s.volume;if(s.mutes)for(const p of Object.keys(state.mutes))if(typeof s.mutes[p]==='boolean')state.mutes[p]=s.mutes[p];state.favorites=Array.isArray(s.favorites)?s.favorites.filter(id=>library.some(x=>x.id===id)):[];}catch{}}
const current=()=>currentV2();
function syncPressed(selector,key,value){document.querySelectorAll(selector).forEach(b=>{const on=b.dataset[key]===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
function renderLibrary(){renderLibraryV2();}
function renderRoll(){renderRollV2();}
function renderStudio(){renderStudioV2();}
function stopPreview(){previewToken++;clearTimeout(soundTimer);for(const n of previewNodes)try{n.stop();}catch{}previewNodes.clear();previewGraph?.dispose();previewGraph=null;document.querySelector('[data-audition]')?.setAttribute('aria-pressed','false');const b=document.querySelector('[data-audition]');if(b)b.textContent='▷ Audition sound';}
function stopAll(){AudioStudio.stop();stopPreview();updatePlayState();renderPosition();}
function updatePlayState(){$('play').textContent=AudioStudio.playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',AudioStudio.playing?'Stop studio loop':'Play studio loop');$('heroPlay').textContent=AudioStudio.playing?'Ⅱ Stop the signal':'▷ Hear the first signal';document.body.classList.toggle('playing',AudioStudio.playing);}
async function startPlayback(){stopPreview();try{await AudioStudio.start(activeListening(),state.voice,listenMutes(),state.volume);updatePlayState();}catch(error){AudioStudio.stop();updatePlayState();notify('Audio could not start. Press Play to retry in a browser with Web Audio.');console.error(error);}}
function changeStudy(id,scroll=false,voice=null,artist=null){const item=library.find(x=>x.id===id);if(!item)return;const playing=AudioStudio.playing;stopAll();state.dev={};devHistory.length=0;state.viewStart=0;state.artist=artist;state.id=id;state.variant='original';state.shift=0;state.bpm=item.bpm;state.voice=voice||STYLES.find(x=>x.id===item.style).voice;renderStudio();renderLibrary();renderArrangement();if(playing)startPlayback();if(scroll)$('studio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
function updateComposition(){const playing=AudioStudio.playing;stopAll();renderStudio();renderArrangement();if(playing)startPlayback();}
function renderWorlds(){$('worldGrid').innerHTML=STYLES.map((s,i)=>`<article class="world-card"><span class="world-number">0${i+1} / ${esc(s.tag.toUpperCase())}</span><h3>${s.name}</h3><span class="world-bpm">${s.range} BPM / SUGGESTED RANGE</span><p>${s.desc}</p><button class="text-btn" data-world="${s.id}">Explore ${s.name.split(' / ')[0]} <span>↗</span></button></article>`).join('');}
function renderArtists(){const q=$('artistSearch').value.trim().toLowerCase(),items=ARTISTS.map((a,i)=>({a,i})).filter(({a})=>(state.artistStyle==='all'||a[1]===state.artistStyle)&&a.join(' ').toLowerCase().includes(q));$('artistGrid').innerHTML=items.length?items.map(({a,i})=>`<article class="artist-card"><span class="tiny">${a[1].toUpperCase()} / PERSPECTIVE ${String(i+1).padStart(2,'0')}</span><h3>${esc(a[0])}</h3><div class="reference">LISTEN FOR THE IDEA · ${esc(a[2])}</div><p>${esc(a[3])}</p><p class="exercise">${esc(a[4])}</p><button class="text-btn" data-artist="${i}">Open a writing exercise <span>↗</span></button></article>`).join(''):'<p class="empty">No artist perspectives match. Try a different name or style.</p>';syncPressed('[data-artist-filter]','artistFilter',state.artistStyle);}
function renderSounds(){const s=SOUNDS.find(s=>s.id===state.sound);$('soundList').innerHTML=SOUNDS.map((p,i)=>`<button class="sound-choice ${p.id===s.id?'active':''}" data-sound="${p.id}" aria-pressed="${p.id===s.id}"><span class="tiny">${String(i+1).padStart(2,'0')} / ${p.type.toUpperCase()}</span><strong>${p.name}</strong><small>${p.tag}</small></button>`).join('');$('soundRecipe').innerHTML=`<div class="eyebrow red">${s.type.toUpperCase()} / ${s.tag.toUpperCase()}</div><h3>${s.name}</h3><p>${s.desc}</p><ol>${s.steps.map(t=>`<li>${t}</li>`).join('')}</ol><div class="sound-tip"><b>Make it move.</b> ${s.move}</div><div class="sound-tip"><b>If it is not working.</b> ${s.fix}</div><div class="sound-actions"><button class="btn primary" data-audition aria-pressed="false">▷ Audition sound</button><button class="btn secondary" data-use-sound>Use as melody voice ↗</button></div>`;}
async function audition(){if(previewGraph){stopPreview();return;}stopAll();const token=++previewToken;try{AudioStudio.ctx ||= new (window.AudioContext||window.webkitAudioContext)();const ctx=AudioStudio.ctx;await ctx.resume();if(token!==previewToken)return;previewGraph=audioGraph(ctx,ctx.destination,state.bpm,state.volume);const s=SOUNDS.find(s=>s.id===state.sound),low=s.type==='Bass',notes=low?[45,45,45,45]:s.type==='Atmosphere'?[57,60,64,67]:[69,72,76,79,76,72,71,69],beat=60/state.bpm;
 notes.forEach((n,i)=>playTone(ctx,previewGraph.lanes.melody,{n,t:i*.5,d:s.type==='Atmosphere'?3.5:.35,v:94},ctx.currentTime+.04+(s.type==='Atmosphere'?0:i*.5*beat),beat,s.id,previewNodes));const button=document.querySelector('[data-audition]');if(button){button.textContent='■ Stop audition';button.setAttribute('aria-pressed','true');}soundTimer=setTimeout(stopPreview,Math.max(notes.length*.5*beat,3.5*beat)*1000+1200);
 }catch(error){stopPreview();notify('Audio could not start. Please retry with the sound audition button.');console.error(error);}}
function renderArrangement(){const items=ARRANGEMENTS[state.arrangement],total=items.reduce((sum,s)=>sum+s[1],0),seconds=Math.round(total*4*60/state.bpm);$('arrangementLength').textContent=`${total} BARS · ${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,'0')} AT ${state.bpm} BPM`;let start=1;$('energyChart').innerHTML=items.map((s,i)=>{const html=`<button class="energy-block ${state.arrangementIndex===i?'active':''}" data-stage="${i}" style="flex:${s[1]};--energy:${s[2]}%" aria-pressed="${state.arrangementIndex===i}" aria-label="${s[0]}, bars ${start} to ${start+s[1]-1}"><span class="bar-start">${String(start).padStart(3,'0')}</span><span class="bar"></span><span class="energy-label">${s[0].toUpperCase()}<br>${s[1]} BARS</span></button>`;start+=s[1];return html;}).join('');const chosen=items[state.arrangementIndex];$('arrangementDetail').innerHTML=`<h3>${chosen[0]}</h3><p>${chosen[3]}</p>`;syncPressed('[data-arrangement]','arrangement',state.arrangement);}
function renderPosition(){renderPositionV2();}
function download(bytes,name,type){const blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function exportPart(part){const parts=part==='full'?['melody','chords','bass','drums']:[part],name=current().id+'-'+state.variant+'-'+pitch(current().root+state.shift).replace('♯','sharp').replace('♭','flat')+'-'+state.bpm+'bpm'+(current().source?'':'-take'+(current().settings.seed+1))+'-'+part+'.mid';download(midiBytes(sketch,parts),name,'audio/midi');notify(part==='full'?'Four MIDI parts exported with tempo and chord voicings.':part[0].toUpperCase()+part.slice(1)+' MIDI exported.');}
async function exportLibrary(){const button=$('downloadLibrary');button.disabled=true;button.textContent='Building your library...';try{await new Promise(resolve=>setTimeout(resolve,40));const files=[];for(let i=0;i<library.length;i++){const item=library[i];for(const [variant]of TREATMENTS)files.push({name:(item.source?'Source-arrangements':'Melodic-developments')+'/'+item.id+'-'+variant+'.mid',bytes:midiBytes(makeSketch(item,{variant,bpm:item.bpm,chordMode:'sustain'}))});if(i%10===0){button.textContent='Building '+Math.round(i/library.length*100)+'%...';await new Promise(resolve=>setTimeout(resolve,0));}}for(const source of SOURCES)files.push({name:'Untouched-sources/'+source.file,bytes:Uint8Array.from(atob(source.original),c=>c.charCodeAt(0))});files.push({name:'README.txt',bytes:new TextEncoder().encode(packReadme())});download(zipBytes(files),'Fieldwork-Trance-God-Mode-'+LIBRARY_COUNTS.treatments+'-Sketches.zip','application/zip');notify(LIBRARY_COUNTS.treatments+' sketches + '+LIBRARY_COUNTS.sources+' untouched sources exported.');}catch(error){notify('Could not build the library. Individual MIDI exports are still available.');console.error(error);}finally{button.disabled=false;button.textContent='Download all '+LIBRARY_COUNTS.treatments+' sketches \u2193';}}
function init(){restore();$('styleFilter').innerHTML+=[...STYLES].map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('voiceSelect').innerHTML=SOUNDS.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('artistFilters').innerHTML=[['all','All perspectives'],...STYLES.map(s=>[s.id,s.name.split(' / ')[0]])].map(([id,name])=>`<button data-artist-filter="${id}" aria-pressed="${id==='all'}" class="${id==='all'?'active':''}">${name}</button>`).join('');
 renderLibrary();renderStudio();renderWorlds();renderArtists();renderSounds();renderArrangement();initLab();
 $('search').addEventListener('input',renderLibrary);$('artistSearch').addEventListener('input',renderArtists);$('styleFilter').addEventListener('change',e=>{state.style=e.target.value;renderLibrary();});
 $('keySelect').addEventListener('change',e=>{state.shift=Number(e.target.value);updateComposition();});$('bpm').addEventListener('change',e=>{const v=Number(e.target.value);if(!Number.isFinite(v)||v<100||v>170){e.target.value=state.bpm;notify('Choose a tempo between 100 and 170 BPM.');return;}state.bpm=Math.round(v);updateComposition();});$('voiceSelect').addEventListener('change',e=>{state.voice=e.target.value;updateComposition();});$('chordMode').addEventListener('change',e=>{state.chordMode=e.target.value;updateComposition();});
 $('volume').addEventListener('input',e=>{state.volume=Number(e.target.value)/100;AudioStudio.volume(state.volume);if(previewGraph)previewGraph.master.gain.setTargetAtTime(state.volume,AudioStudio.ctx.currentTime,.02);save();});
 $('play').addEventListener('click',()=>AudioStudio.playing?stopAll():startPlayback());$('heroPlay').addEventListener('click',()=>AudioStudio.playing?stopAll():startPlayback());$('stop').addEventListener('click',stopAll);
 $('favorite').addEventListener('click',()=>{const index=state.favorites.indexOf(state.id);if(index===-1)state.favorites.push(state.id);else state.favorites.splice(index,1);renderStudio();renderLibrary();notify(index===-1?'Study starred. Your favourites are marked in the library.':'Study removed from favourites.');});
 for(const [id,part]of [['exportSketch','full'],['exportMelody','melody'],['exportChords','chords'],['exportBass','bass']])$(id).addEventListener('click',()=>exportPart(part));$('exportSource').addEventListener('click',()=>{const item=current();if(item.source){download(Uint8Array.from(atob(item.original),c=>c.charCodeAt(0)),item.file,'audio/midi');notify('Original MIDI downloaded without modification.');}});$('downloadLibrary').addEventListener('click',exportLibrary);
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.study)changeStudy(d.study);if(d.source){state.source=d.source;renderLibrary();}if(d.variant){state.variant=d.variant;updateComposition();}if(d.roll){state.roll=d.roll;renderRoll();}if(d.part){state.mutes[d.part]=!state.mutes[d.part];AudioStudio.updateMutes(state.mutes);b.classList.toggle('on',state.mutes[d.part]);b.setAttribute('aria-pressed',String(state.mutes[d.part]));save();}if(d.world){state.source='study';state.style=d.world;$('search').value='';$('styleFilter').value=d.world;changeStudy(library.find(x=>!x.source&&x.style===d.world).id,true);}if(d.artistFilter){state.artistStyle=d.artistFilter;renderArtists();}if(d.artist!==undefined){const a=ARTISTS[Number(d.artist)];state.source='all';state.style='all';$('styleFilter').value='all';$('search').value='';changeStudy(library.filter(x=>!x.source&&x.style===a[1])[Number(d.artist)%library.filter(x=>!x.source&&x.style===a[1]).length].id,true,a[5],Number(d.artist));notify(a[0]+': '+a[4]);}if(d.sound){stopPreview();state.sound=d.sound;renderSounds();}if('audition'in d)audition();if('useSound'in d){state.voice=state.sound;updateComposition();$('studio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});notify('Melody voice set to '+SOUNDS.find(s=>s.id===state.voice).name+'.');}if(d.arrangement){state.arrangement=d.arrangement;state.arrangementIndex=0;renderArrangement();}if(d.stage!==undefined){state.arrangementIndex=Number(d.stage);renderArrangement();}});
 document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!/INPUT|SELECT|TEXTAREA|BUTTON|A|SUMMARY/.test(e.target.tagName)&&!e.target.isContentEditable){e.preventDefault();AudioStudio.playing?stopAll():startPlayback();}if(e.code==='Escape')stopAll();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAll();});window.addEventListener('pagehide',stopAll);setInterval(()=>{if(AudioStudio.playing)renderPosition();},70);
}
init();
