// Local Web Audio sketches. All voices are synthesized; no reference recordings or external samples.
function audioGraph(ctx,destination,bpm,volume=.55){
 const master=ctx.createGain(),limiter=ctx.createDynamicsCompressor();master.gain.value=volume;limiter.threshold.value=-12;limiter.knee.value=12;limiter.ratio.value=8;limiter.attack.value=.003;limiter.release.value=.16;master.connect(limiter);limiter.connect(destination);
 const delay=ctx.createDelay(2),feedback=ctx.createGain(),dark=ctx.createBiquadFilter(),wet=ctx.createGain();delay.delayTime.value=60/bpm*.75;feedback.gain.value=.25;dark.type='lowpass';dark.frequency.value=3600;wet.gain.value=.16;delay.connect(dark);dark.connect(feedback);feedback.connect(delay);dark.connect(wet);wet.connect(master);
 const lanes={};for(const part of ['melody','chords','bass','drums']){const gain=ctx.createGain();gain.gain.value=1;gain.connect(master);lanes[part]=gain;if(part==='melody'||part==='chords')gain.connect(delay);}return {master,lanes,delay,dispose(){master.disconnect();limiter.disconnect();delay.disconnect();feedback.disconnect();dark.disconnect();wet.disconnect();Object.values(lanes).forEach(n=>n.disconnect());}};
}
function playTone(ctx,out,event,start,beat,voice,active){
 const freq=440*2**((event.n-69)/12),duration=event.d*beat,preset=SOUNDS.find(s=>s.id===voice)||SOUNDS[0],amp=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type=voice==='squelch'?'bandpass':'lowpass';filter.Q.value=preset.q||.65;filter.frequency.setValueAtTime(Math.min(preset.cut,ctx.sampleRate*.44),start);filter.frequency.exponentialRampToValueAtTime(Math.max(130,preset.cut*(preset.s<.3?.19:.72)),start+Math.max(.03,duration));filter.connect(amp);amp.connect(out);
 const gain=.15*(event.v/127)/(preset.voices**.6),attack=Math.min(preset.a,duration*.4),decay=Math.min(.13,duration*.45),release=preset.r; amp.gain.setValueAtTime(0,start);amp.gain.linearRampToValueAtTime(gain,start+attack);amp.gain.linearRampToValueAtTime(gain*preset.s,start+attack+decay);amp.gain.setValueAtTime(gain*preset.s,start+duration);amp.gain.linearRampToValueAtTime(0,start+duration+release);
 const nodes=[],oscs=[];for(let i=0;i<preset.voices;i++){const osc=ctx.createOscillator(),pan=ctx.createStereoPanner();osc.type=preset.wave;osc.frequency.value=freq;osc.detune.value=(i-(preset.voices-1)/2)*preset.detune;pan.pan.value=preset.voices===1?0:(i/(preset.voices-1)-.5)*1.2;osc.connect(pan);pan.connect(filter);nodes.push(pan);oscs.push(osc);if(preset.fm){const modulator=ctx.createOscillator(),depth=ctx.createGain();modulator.frequency.value=freq*preset.fm;depth.gain.setValueAtTime(freq*.6,start);depth.gain.exponentialRampToValueAtTime(1,start+.12);modulator.connect(depth);depth.connect(osc.frequency);nodes.push(depth);oscs.push(modulator);}}
 for(const osc of oscs){active?.add(osc);osc.start(start);osc.stop(start+duration+release+.03);}oscs[0].onended=()=>{for(const osc of oscs){active?.delete(osc);osc.disconnect();}nodes.forEach(n=>n.disconnect());filter.disconnect();amp.disconnect();};
}
function playDrum(ctx,out,event,start,active){
 const gain=ctx.createGain();gain.connect(out);const amp=(event.v/127)*(event.n===36?.55:.14);gain.gain.setValueAtTime(amp,start);gain.gain.exponentialRampToValueAtTime(.0001,start+(event.n===36?.28:.13));let source,filter;
 if(event.n===36){source=ctx.createOscillator();source.frequency.setValueAtTime(145,start);source.frequency.exponentialRampToValueAtTime(48,start+.065);source.connect(gain);}else{source=ctx.createBufferSource();const buf=ctx.createBuffer(1,Math.floor(ctx.sampleRate*.15),ctx.sampleRate),data=buf.getChannelData(0);let seed=139;for(let i=0;i<data.length;i++){seed=(seed*16807)%2147483647;data[i]=(seed/2147483647*2-1);}source.buffer=buf;filter=ctx.createBiquadFilter();filter.type=event.n===42?'highpass':'bandpass';filter.frequency.value=event.n===42?8000:1600;source.connect(filter);filter.connect(gain);}
 active?.add(source);source.start(start);source.stop(start+.3);source.onended=()=>{active?.delete(source);source.disconnect();filter?.disconnect();gain.disconnect();};
}
const AudioStudio={ctx:null,graph:null,active:new Set(),playing:false,timer:null,token:0,
 async start(sketch,voice,mutes,volume){this.stop();const token=++this.token;this.ctx ||= new (window.AudioContext||window.webkitAudioContext)();await this.ctx.resume();if(token!==this.token)return;this.graph=audioGraph(this.ctx,this.ctx.destination,sketch.bpm,volume);this.playing=true;this.epoch=this.ctx.currentTime+.08;this.sketch=sketch;this.voice=voice;this.mutes={...mutes};this.events=Object.entries(sketch).filter(([p])=>['melody','chords','bass','drums'].includes(p)).flatMap(([part,events])=>events.map(event=>({part,event}))).sort((a,b)=>a.event.t-b.event.t);this.cursor=0;this.cycle=0;this.updateMutes(mutes);this.schedule();this.timer=setInterval(()=>this.schedule(),25);},
 schedule(){if(!this.playing)return;const beat=60/this.sketch.bpm;while(true){const {part,event}=this.events[this.cursor],time=this.epoch+(this.cycle*this.sketch.beats+event.t)*beat;if(time>this.ctx.currentTime+.15)break;if(time>=this.ctx.currentTime-.02){if(part==='drums')playDrum(this.ctx,this.graph.lanes.drums,event,Math.max(time,this.ctx.currentTime),this.active);else playTone(this.ctx,this.graph.lanes[part],event,Math.max(time,this.ctx.currentTime),beat,part==='melody'?this.voice:part==='chords'?'pad':'bass',this.active);}this.cursor++;if(this.cursor===this.events.length){this.cursor=0;this.cycle++;}}},
 updateMutes(mutes){this.mutes={...mutes};if(this.graph)for(const [p,on]of Object.entries(mutes))this.graph.lanes[p].gain.setTargetAtTime(on?1:0,this.ctx.currentTime,.015);},
 volume(v){if(this.graph)this.graph.master.gain.setTargetAtTime(v,this.ctx.currentTime,.02);},
 stop(){this.token++;this.playing=false;clearInterval(this.timer);for(const node of this.active)try{node.stop();}catch{}this.active.clear();this.graph?.dispose();this.graph=null;},
 position(){return this.playing?mod((this.ctx.currentTime-this.epoch)/(60/this.sketch.bpm),this.sketch.beats):0;}
};
