const STYLES=[
 {id:'uplifting',name:'Uplifting',bpm:138,range:'136–142',tag:'Lift / release / euphoria',desc:'A small motif becomes a horizon-wide hook. Let a repeated rhythm bind the changing chords together.',prog:[0,5,2,6],motif:[0,4,7,6,4,2,4,1],rh:[0,.5,1,1.5,2,2.5,3,3.5],voice:'supersaw',bass:'offbeat',lesson:'Save the highest note for the answer. Move the bass underneath the same opening gesture.',mix:'High-pass the wide lead layer; leave a centred voice carrying the melody. Duck the pad and delay return around the kick.'},
 {id:'classic',name:'Classic / anthem',bpm:138,range:'134–142',tag:'Simple motif / enormous payoff',desc:'Memorable interval shapes, singing supersaws and long harmonic tension. Restraint gives the big moment its scale.',prog:[0,3,5,6],motif:[0,4,0,7,6,4,2,1],rh:[0,.75,1.5,2,2.75,3.5],voice:'anthem',bass:'offbeat',lesson:'Write a hook you can hum with the synth switched off. Repeat it once before changing its ending.',mix:'Keep the rhythmic centre dry enough to punch. Automate the effects send into the breakdown rather than washing out the whole track.'},
 {id:'progressive',name:'Progressive',bpm:128,range:'124–134',tag:'Patience / detail / slow motion',desc:'A pluck, a changing bass note and carefully rationed brightness can carry a long phrase.',prog:[0,5,2,3],motif:[0,2,4,6,4,2,1,4],rh:[0,.75,1.75,2.5,3.25],voice:'pluck',bass:'rolling',lesson:'Keep the notes stable for eight bars; make the second pass feel new by opening the filter.',mix:'Shorten the bass release before adding compression. Give the pluck a filtered dotted-eighth echo.'},
 {id:'balearic',name:'Balearic / dream',bpm:132,range:'126–138',tag:'Air / warmth / wistfulness',desc:'Open chords, bell-like attacks and generous space. Let a passing note resolve without hurrying it.',prog:[5,2,6,0],motif:[4,2,0,6,4,7,6,2],rh:[0,1,1.75,2.5,3.5],voice:'bell',bass:'offbeat',lesson:'Leave one full beat of silence. Try a ninth above a warm major chord for suspended, sunlit colour.',mix:'Separate the soft attack from the long atmosphere. Cut low frequencies from reverb and keep the bass mono.'},
 {id:'tech',name:'Tech trance',bpm:140,range:'136–145',tag:'Pressure / percussion / impact',desc:'Tight rhythmic cells, metallic edges and short melodic reveals. The bass and kick are the main conversation.',prog:[0,0,5,6],motif:[0,0,4,1,0,7,4,0],rh:[0,.25,.75,1.5,2,2.25,3,3.75],voice:'metal',bass:'rolling',lesson:'Use the same three pitches with two different rhythms. Keep the full hook for a single eight-bar reveal.',mix:'Distort the mid layer in parallel. Keep a clean low-frequency anchor beneath the abrasive sound.'},
 {id:'hard',name:'Hard trance',bpm:145,range:'140–150',tag:'Attack / tension / velocity',desc:'Forceful offbeats, sharp saws and bold octave jumps. A dry transient keeps the riff legible at speed.',prog:[0,6,5,6],motif:[0,7,0,4,1,0,6,4],rh:[0,.5,1,1.5,2,2.5,3,3.5],voice:'rave',bass:'offbeat',lesson:'Anchor the first half with the root; answer an octave higher. A short gap before the repeat makes it hit harder.',mix:'Reduce overlapping releases as the tempo rises. Let the lead occupy the upper mids without doubling the bass octave.'},
 {id:'goa',name:'Goa',bpm:144,range:'138–150',tag:'Interlocking lines / acid colour',desc:'Evolving sequences create a psychedelic conversation. Change accents and filter movement before adding another voice.',prog:[0,0,3,0],motif:[0,1,4,7,6,4,2,1,0,4,6,2],rh:[0,.25,.5,.75,1,1.5,1.75,2,2.5,2.75,3,3.5],voice:'acid',bass:'rolling',lesson:'Set a three-note accent cycle against the four-beat bar. Keep one stable anchor while the other line moves.',mix:'Separate interlocking lines by register and pan. Resonance needs headroom; tame peaks before raising the channel.'},
 {id:'psy',name:'Psytrance',bpm:145,range:'138–150',tag:'Precision / mutation / hypnosis',desc:'A clean kick–bass engine under compact, changing upper sequences. Silence is a rhythmic ingredient.',prog:[0,0,0,0],motif:[0,1,4,0,7,3,1,0],rh:[0,.25,.75,1.25,1.5,2.25,2.75,3.5,3.75],voice:'squelch',bass:'psy',lesson:'Keep the bass root stable. Alternate a short lead fragment with a filtered echo; avoid filling every gap.',mix:'Check kick tail and bass attack together at the intended tempo. Keep delay and unison away from the lowest octave.'}
];
const SOURCE_INFO=[
 ['Signal / release','classic',0,'major',[[0,4,7],[9,0,4],[7,11,2],[5,9,0]],'C → Am → G → F','The B over Am is a ninth. Hear it as a colour tone, then resolve into the G chord.'],
 ['Two-note gravity','progressive',0,'major',[[0,4,7],[7,0,2],[9,0,4,7],[5,9,0,7]],'C → Gsus4 → Am7 → Fadd9','Only C and G occur in the source: the mode is ambiguous. These changing chords are one way to create movement.'],
 ['Wide awake','hard',0,'major',[[0,4,7],[0,4,7],[5,9,0,7],[7,0,2]],'C → C → Fadd9 → Gsus4','The low C/high G contrast is the hook. Leave room for its two-octave span.'],
 ['Changing skies','uplifting',0,'major',[[0,4,7],[2,5,9],[9,0,4],[7,11,2,0]],'C → Dm → Am → G(add11)','The final C rubs against B in the G chord. Use it as a brief suspension resolving when the loop returns.'],
 ['Lydian afterglow','balearic',5,'lydian',[[5,9,0,7],[5,9,0,4],[5,9,0,11],[5,9,0,7]],'Fadd9 → Fmaj7 → F(add♯11) → Fadd9','F remains the pedal. B is the raised fourth, giving the third bar its Lydian light.'],
 ['Under the surface','progressive',0,'major',[[0,4,7],[0,4,7],[0,4,7,11],[0,4,7]],'C → C → Cmaj7 → C','The source alternates C and E across registers. Root-position C voicings are suggested; try E in the bass in your DAW.'],
 ['Beautiful friction','tech',0,'major',[[0,4,7,11],[0,4,7,2],[9,0,4,11],[2,5,9,4]],'Cmaj7 → Cadd9 → Am(add9) → Dm(add9)','B against C is intentional tension. The added-ninth chords frame these close intervals rather than removing them.'],
 ['Orbiting midnight','goa',9,'minor',[[9,0,4,7,11],[9,0,4,7,11],[5,9,0,4,7],[9,0,4,7,11]],'Am9 → Am9 → Fmaj9 → Am9','A, B, C and G suggest an A-minor palette without fixing a unique harmony. The held voicings turn the loop into a floating ostinato.'],
 ['First light','uplifting',9,'minor',[[9,0,4],[5,9,0,4],[9,0,4],[9,0,4]],'Am → Fmaj7 → Am → Am','The melody touches F then E. Let the F harmony bloom in bar two and bring the bass home afterward.'],
 ['Rooted in motion','psy',9,'minor',[[9,0,4],[9,0,4],[9,0,4],[9,0,4]],'Am pedal','The A/C pair implies a minor third. A stable A pedal makes this a useful bass-and-sequence study.'],
 ['Falling satellites','classic',9,'minor',[[9,0,4],[0,4,7],[5,9,0,4],[9,0,4]],'Am → C → Fmaj7 → Am','Follow the descending low notes with economical chord movement; the repeated high C ties the first two bars together.'],
 ['The last horizon','balearic',9,'minor',[[5,9,0],[9,0,4],[2,5,9,7],[9,0,4,11]],'F → Am → Dm(add11) → Am(add9)','The last B is a ninth above A. Keep it light, or resolve it to A in a variation.']
];
const ORIGINAL_NAMES=['Event horizon','A thousand suns','Terminal velocity','The return','Redshift','After the rain','Saltwater memory','Somewhere, forever','Pressure system','Cold transmission','Rave architecture','Beyond the strobe','Spiral language','Ancient circuitry','Organism','Parallel consciousness'];
const TREATMENTS=[
 ['original','Original','The source notes, timings and velocities are preserved. New studies use their written motif.'],
 ['lift','Octave lift','Raise the answer by an octave while keeping the first half familiar.'],
 ['space','Call & response','Remove alternating beats in the answer and lengthen what remains.'],
 ['triplet','Triplet orbit','Re-space each bar into an even triplet grid. Hear the same pitches with a different forward pull.'],
 ['slow','Slow burn','Keep every fourth note and lengthen it: a breakdown seed with room for atmosphere.'],
 ['weave','Chord weave','Write a new sixteenth-note line from the displayed chord tones, alternating direction each bar.']
];
const SOUNDS=[
 {id:'supersaw',name:'Horizon supersaw',type:'Lead',tag:'Wide / euphoric',wave:'sawtooth',voices:5,detune:13,cut:6500,a:.012,r:.20,s:.65,desc:'The expansive lead: a centred saw surrounded by quieter detuned voices.',steps:['Start with a saw, 7 unison voices and modest detune (about 8–18 cents). Keep a solid centre voice.','Use a low-pass around 5–9 kHz. Amp: attack 5–15 ms, decay 400 ms, sustain 65%, release 150–250 ms.','High-pass the stereo support layer near 180 Hz; add filtered dotted-eighth delay and a long, quiet reverb.'],move:'Open the filter over 16 bars. Increase reverb in the break, then pull it back for the drop.',fix:'If the hook feels blurry, reduce detune and release before adding another layer.'},
 {id:'anthem',name:'Glass-front anthem',type:'Lead',tag:'Focused / singing',wave:'sawtooth',voices:3,detune:7,cut:4200,a:.008,r:.18,s:.8,desc:'A compact saw stack with a clear attack that carries a hummable hook.',steps:['Layer one centred saw with two quieter detuned saws. Add a very quiet square an octave down.','Amp: attack 8 ms, decay 250 ms, sustain 80%, release 180 ms. Keep filter resonance restrained.','Separate the dry centre from the wet stereo return; add a short plate before a longer hall.'],move:'Make the answer brighter without changing the opening notes.',fix:'If it competes with a vocal, lower the lead register or remove notes during the vocal phrase.'},
 {id:'pluck',name:'Dotted-light pluck',type:'Pluck',tag:'Precise / luminous',wave:'sawtooth',voices:2,detune:5,cut:4800,a:.003,r:.10,s:.1,desc:'A snappy filter envelope turns a small motif into a moving web of echoes.',steps:['Use two saw voices with very little detune. Amp: attack 2 ms, decay 220 ms, sustain 10%, release 100 ms.','Low-pass starts around 700 Hz; a positive envelope opens it by 2–4 octaves, then decays in 180–300 ms.','Set a dotted-eighth delay with 20–30% feedback; filter its lows below 300 Hz and darken its highs.'],move:'Lengthen the filter decay through the build; shorten it again at the drop.',fix:'If echoes obscure the rhythm, turn down feedback rather than lowering the dry attack.'},
 {id:'bell',name:'Coastal FM bell',type:'Pluck',tag:'Glass / air',wave:'sine',voices:1,detune:0,cut:10000,a:.002,r:.35,s:.12,fm:2,desc:'A clean fundamental with a brief metallic overtone. Use sparingly above warm chords.',steps:['Use a sine carrier and a sine modulator at a 2:1 frequency ratio. Start with moderate FM depth.','Decay the FM depth faster than the amplitude. Amp: 2 ms attack, 700 ms decay, zero sustain, 300 ms release.','Add a high-passed stereo delay and diffuse reverb; keep the dry bell audible.'],move:'Reduce FM depth for the breakdown, restore the bright transient on the answer.',fix:'If it sounds like a mallet rather than a bell, lengthen the decay and gently raise FM depth.'},
 {id:'metal',name:'Chrome stab',type:'Lead',tag:'Metal / impact',wave:'square',voices:1,detune:0,cut:3400,a:.003,r:.07,s:.25,fm:1.414,desc:'An inharmonic attack for percussive tech-trance punctuation.',steps:['FM a sine or square with a non-integer ratio such as 1.41:1. Keep the depth moderate.','Use a short amplitude envelope: 3 ms attack, 150 ms decay, low sustain, 70 ms release.','Band-limit the result, saturate in parallel and feed a small amount to a short room.'],move:'Use velocity to drive FM depth so accents change colour as well as loudness.',fix:'If the note loses its pitch, reduce FM and reinforce it with a quiet sine fundamental.'},
 {id:'rave',name:'Redline saw',type:'Lead',tag:'Hard / cutting',wave:'sawtooth',voices:3,detune:19,cut:7600,a:.002,r:.08,s:.7,desc:'A sharper, wider saw for hard offbeat riffs and octave answers.',steps:['Start with three detuned saws and an octave layer mixed about 12 dB quieter.','Amp: 2 ms attack, 160 ms decay, 70% sustain, 80 ms release. Cut low frequencies that belong to the bass.','Use modest distortion before the final EQ. Add a short stereo slap with little feedback.'],move:'Automate the octave layer into the last four bars of a phrase.',fix:'If distortion makes the hook smaller, level-match the bypass and keep more dry signal.'},
 {id:'acid',name:'Liquid circuitry',type:'Sequence',tag:'Resonant / restless',wave:'sawtooth',voices:1,detune:0,cut:2500,a:.003,r:.065,s:.15,q:8,desc:'A resonant saw sequence that comes alive through accents and filter movement.',steps:['Choose a mono saw. Use a resonant low-pass, starting near 400 Hz, with a short positive filter envelope.','Set amp decay around 140 ms and a short release. Use velocity to increase both brightness and level.','In your synth, add legato slide on selected overlaps; drive the filter gently.'],move:'Open cutoff and vary decay on every fourth repeat; leave some notes unaccented.',fix:'If resonance removes the weight, blend a quieter unfiltered fundamental. Browser preview does not model slide.'},
 {id:'squelch',name:'Alien vowel',type:'Sequence',tag:'Psychedelic / elastic',wave:'sawtooth',voices:1,detune:0,cut:1900,a:.002,r:.04,s:.1,q:12,desc:'Short resonant bursts create an upper-register answer to a precise bass engine.',steps:['Start with a saw into a resonant band-pass. Keep the fundamental in a comfortable mid register.','Use a very short envelope: attack 2 ms, decay 90 ms, no sustain, release 40 ms.','Move the filter with a stepped LFO; use a second parallel band-pass for vowel-like movement.'],move:'Alternate two filter positions as a call and response rather than sweeping continuously.',fix:'If peaks jump out, lower resonance first and control the remaining peaks after filtering.'},
 {id:'pad',name:'Afterimage pad',type:'Atmosphere',tag:'Slow / weightless',wave:'sawtooth',voices:3,detune:9,cut:1700,a:.22,r:.7,s:.6,desc:'A dark, slow layer that makes chord changes feel larger.',steps:['Use a warm saw/triangle blend with gentle unison and a low-pass near 1.5–3 kHz.','Amp: 300–800 ms attack, long decay, 60% sustain, 1–3 second release.','High-pass around 180–300 Hz, add slow stereo movement and a dark hall.'],move:'Keep the filter closed under the lead; open it during the breakdown.',fix:'If chord changes smear, shorten release or change the pad slightly before the bass.'},
 {id:'gate',name:'Gated velvet',type:'Atmosphere',tag:'Pulse / suspension',wave:'triangle',voices:3,detune:7,cut:3200,a:.01,r:.09,s:.65,desc:'Soft chord colour cut into a precise rhythmic gate.',steps:['Build a warm pad with a triangle/saw blend and modest detune.','After the synth, add a tempo-synced amplitude gate at eighth notes. Use a small fade at both ends.','Try a 50–65% gate length, then feed the gated result into a quiet stereo delay.'],move:'Mute one gate per bar to create a recognisable pattern. Use Pulsed chords in this studio.',fix:'If the gate clicks, lengthen its attack and release by a few milliseconds.'},
 {id:'organ',name:'Dream organ',type:'Pluck',tag:'Rounded / nostalgic',wave:'triangle',voices:1,detune:0,cut:5200,a:.005,r:.14,s:.4,desc:'A rounded, simple tone that reveals whether the melody works without spectacle.',steps:['Mix a sine fundamental with quieter sine harmonics at +12 and +19 semitones.','Use a 5 ms attack, 300 ms decay, 40% sustain and 140 ms release.','Add a small chorus and short plate; keep the first transient dry.'],move:'Use it to sketch the breakdown before replacing or layering the main lead.',fix:'If it lacks definition, raise the second harmonic rather than brightening every frequency.'},
 {id:'air',name:'Polar shimmer',type:'Atmosphere',tag:'High / fragile',wave:'sine',voices:3,detune:12,cut:9000,a:.07,r:.5,s:.5,desc:'A thin upper layer that adds height without another full saw stack.',steps:['Layer two quiet sine voices one octave above the hook with slight detune.','Soften the attack to 50–100 ms; use a 500 ms release. Remove low frequencies.','Add a wide chorus and diffuse, high-passed reverb. Mix it beneath the main lead.'],move:'Bring it in only on the final repetition to create an emotional lift.',fix:'If it sounds disconnected, shorten the attack and keep it quieter than the centre lead.'},
 {id:'bass',name:'Offbeat anchor',type:'Bass',tag:'Mono / spring-loaded',wave:'sawtooth',voices:1,detune:0,cut:650,a:.004,r:.045,s:.25,desc:'A short, rounded low note placed halfway between kick drums.',steps:['Use one mono saw and a quiet sine at the same pitch. Start around A1–A2.','Low-pass around 500–900 Hz, short filter decay, amp release under 80 ms.','Place eighth notes on each offbeat; shorten them until the next kick is clear.'],move:'Introduce a fifth or octave only in the last bar of the phrase.',fix:'If the low end swells unevenly, check note lengths and kick tail before adding compression.'},
 {id:'rolling',name:'Rolling engine',type:'Bass',tag:'Tight / continuous',wave:'sawtooth',voices:1,detune:0,cut:950,a:.002,r:.025,s:.1,desc:'Fast bass repetitions with consistent envelopes and clear gaps.',steps:['Use one saw with oscillator phase reset. Disable unison in the low register.','Set a 2 ms attack, 70–110 ms decay, very low sustain and 20–40 ms release.','Sequence three sixteenths after each kick. Adjust each note length to leave a tiny gap.'],move:'Change one velocity or remove the last hit every fourth bar.',fix:'If the groove flams, align oscillator starts and inspect the kick/bass transition together.'},
 {id:'sub',name:'Sine foundation',type:'Bass',tag:'Pure / centred',wave:'sine',voices:1,detune:0,cut:400,a:.006,r:.05,s:.7,desc:'A clean reference for checking roots and the space left by the kick.',steps:['Use one sine oscillator with phase reset and no unison.','Amp: 5–10 ms attack, medium sustain and 40–80 ms release.','Keep it mono and dry. Add a very quiet harmonic layer if small speakers need help.'],move:'Follow chord roots with simple lengths; do not copy every lead note.',fix:'If notes disappear on headphones, check octave and level before boosting the lowest frequencies.'},
 {id:'pulse',name:'Neon square',type:'Sequence',tag:'Hollow / nimble',wave:'square',voices:2,detune:4,cut:3800,a:.004,r:.08,s:.3,desc:'A hollow counter-sequence that contrasts with a dense saw lead.',steps:['Choose a pulse wave around 35–45% width; add a second voice only if needed.','Amp: 4 ms attack, 180 ms decay, 30% sustain, 80 ms release.','Use slow pulse-width modulation, a moderate low-pass and a short filtered echo.'],move:'Place it between lead phrases in a different octave.',fix:'If it masks the main hook, remove notes before reaching for EQ.'}
];
const ARTISTS=[
 ['Ferry Corsten / System F','classic','Out Of The Blue','A direct, singing hook and a bright saw centre.','Write a two-bar motif; repeat the rhythm over four roots. Let the final answer rise.','anthem'],
 ['Tiësto · classic era','classic','Suburban Train','Patient development, driving sequences and a long emotional reveal.','Delay the full lead until the harmony has already established its pull.','supersaw'],
 ['Paul van Dyk','classic','For An Angel','A rhythmic melodic identity with strong forward momentum.','Keep a repeated offbeat figure; change one ending note every fourth bar.','anthem'],
 ['Rank 1','classic','Airwave','Broad chord colour and economical melodic movement.','Hold an upper common tone while the bass changes beneath it.','pad'],
 ['Armin van Buuren','uplifting','Communication','An insistent motif that grows through arrangement and sound.','Use a short pattern, then widen its register only at the phrase peak.','supersaw'],
 ['Aly & Fila','uplifting','We Control The Sunlight','Soaring melodic release and expressive breakdown space.','Leave space for a vocal-shaped phrase; answer with a brighter octave.','supersaw'],
 ['Sean Tyas','uplifting','Lift','Fast, clear melodic movement with a powerful rhythmic foundation.','Keep the lead envelope short enough that rapid notes remain distinct.','anthem'],
 ['Giuseppe Ottaviani','uplifting','Through Your Eyes','A clear melodic centre and purposeful phrase development.','Play the motif on a plain keyboard tone first; preserve its strongest interval.','organ'],
 ['Above & Beyond / OceanLab','progressive','Satellite','Emotional harmony, singable phrasing and carefully staged release.','Add a ninth to one chord; leave a full beat for the phrase to breathe.','pluck'],
 ['Super8 & Tab','progressive','Helsinki Scorchin’','A bold rhythmic hook and clean, luminous synth layers.','Pair a tight pluck with a quieter sustained layer using the same harmony.','pluck'],
 ['ilan Bluestone','progressive','Spheres','Weighty melodic progressions and a strong, focused lead voice.','Use fewer bass changes and a wide upper voicing; keep the lead rhythm compact.','supersaw'],
 ['Andrew Bayer','progressive','Once Lydian','Detailed harmonic colour and contrast between sections.','Keep one motif but alternate a dry, sparse statement with a fuller answer.','bell'],
 ['Chicane','balearic','Saltwater','Atmosphere, open space and a wistful melodic contour.','Keep a soft upper melody over open voicings and a deliberately simple bass.','bell'],
 ['ATB','balearic','9 PM (Till I Come)','A recognisable timbre carrying a very economical hook.','Write with two or three strong notes; let articulation supply the personality.','organ'],
 ['Robert Miles','balearic','Children','A memorable keyboard motif against a steady dance foundation.','Reduce your idea to a playable keyboard phrase before expanding the arrangement.','organ'],
 ['Solarstone','balearic','Seven Cities','Long-form emotional lift and clear, enduring melodic shapes.','Hold back the high octave until the second half of the phrase.','anthem'],
 ['Marco V','tech','Simulated','Percussive synth hooks and strong rhythmic pressure.','Use a three-note cell with varied rests; keep effects tails out of the kick.','metal'],
 ['Simon Patterson','tech','Smack','A forceful rhythmic engine contrasted with a melodic release.','Alternate a bass-led section with one short, recognisable melodic statement.','squelch'],
 ['Scot Project','hard','U (I Got A Feeling)','Hard-edged saws, assertive offbeats and dramatic tension.','Build an octave riff with short releases, then cut a beat before the return.','rave'],
 ['Cosmic Gate · early era','hard','Exploration Of Space','Bold riffs and an immediately readable rhythmic shape.','Use the root and fifth as anchors, with a single high-note answer.','rave'],
 ['Astral Projection','goa','Mahadeva','Layered sequences that evolve through timbre and interlocking rhythm.','Make two short lines in separate registers and change their accents independently.','acid'],
 ['Hallucinogen','goa','LSD','Psychedelic melodic turns and animated, resonant textures.','Repeat a small pitch set while moving the filter and displacing the accents.','acid'],
 ['Astrix','psy','Deep Jungle Walk','A precise rolling foundation and gradually unfolding psychedelic layers.','Keep the bass consistent and introduce upper events in four-bar stages.','squelch'],
 ['Infected Mushroom','psy','Becoming Insane','Expressive synthesis, rhythmic surprises and contrasting sections.','Answer a regular phrase with a shorter, timbrally different fragment.','metal']
];
const ARRANGEMENTS={
 uplifting:[['DJ intro',32,25,'Kick, hats, bass. Reveal a filtered fragment in the final eight bars.'],['First statement',32,58,'Introduce the pluck and a restrained chord layer. Keep the biggest register in reserve.'],['Breakdown',32,18,'Remove kick and bass. Expose the chord voicing, then let the melody appear.'],['Build',16,72,'Open the filter, shorten drum subdivisions and leave a short gap before impact.'],['Main release',32,100,'Full hook, grounded bass and a controlled stereo lead. Change the answer after 16 bars.'],['Second movement',32,78,'Remove one layer, alter the response, then return to the full idea.'],['DJ outro',32,30,'Take away the melody and chords in eight-bar steps. Leave a clean rhythmic exit.']],
 progressive:[['Intro',32,20,'Start with the groove and a trace of atmosphere.'],['Establish',32,40,'Introduce the bass and a dry pluck.'],['Evolve',32,63,'Change a chord extension and increase filter decay.'],['Break',16,22,'Expose one emotional detail; avoid adding every layer.'],['Lift',16,75,'Reintroduce rhythmic motion and open the lead filter.'],['Release',32,93,'Use the full harmony with an evolved answer.'],['Outro',32,28,'Reduce density gradually for the mix.']],
 psy:[['Intro',16,25,'Set the tonal centre with sparse texture.'],['Engine',32,64,'Establish kick and bass before the upper sequence.'],['Mutation',32,83,'Alternate resonant motifs every eight bars.'],['Reset',16,20,'Remove the bass and introduce a contrasting texture.'],['Rebuild',16,70,'Tease the engine with short rhythmic fragments.'],['Peak',32,100,'Bring back the stable bass under the most animated upper line.'],['Exit',16,38,'Remove lead elements and keep the rhythm legible.']]
};
