(async()=>{
 const results=[],errors=[],audioStats=[],assert=(ok,name)=>{if(!ok)throw Error(name);results.push(name);};
 window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
 const click=selector=>{const el=document.querySelector(selector);assert(!!el,'Control exists: '+selector);el.click();};
 const set=(id,value,event='change')=>{$(id).value=value;$(id).dispatchEvent(new Event(event,{bubbles:true}));};
 const overflow=label=>assert(document.documentElement.scrollWidth<=innerWidth+1,'No horizontal page overflow: '+label);
 try{
  assert(document.querySelectorAll('[data-study]').length===28,'28 studies render');assert(document.querySelectorAll('[data-artist]').length===24,'24 artists render');assert(document.querySelectorAll('[data-sound]').length===16,'16 sounds render');overflow('initial');
  for(const item of library){changeStudy(item.id);assert($('studyName').textContent===item.name,'Study selection '+item.id);assert(document.querySelectorAll('.chord-card').length===item.beats/4,'All chord voicings visible '+item.id);for(const [variant]of TREATMENTS){click('[data-variant="'+variant+'"]');assert(state.variant===variant,'Treatment '+item.id+' '+variant);assert($('pianoRoll').querySelectorAll('rect').length>sketch.melody.length,'Piano roll renders '+item.id+' '+variant);}overflow(item.id);}
  click('[data-source="source"]');assert(document.querySelectorAll('[data-study]').length===12,'Source-only filter');set('search','012','input');assert(document.querySelectorAll('[data-study]').length===1,'Filename search');set('search','nothing-matches','input');assert($('melodyList').textContent.includes('No melodies match'),'Search empty state');set('search','','input');click('[data-source="study"]');set('styleFilter','psy');assert(document.querySelectorAll('[data-study]').length===2,'Source and style filters combine');set('styleFilter','all');click('[data-source="all"]');
  changeStudy('source-1');const original=sketch.melody[0].n;set('keySelect','2');assert(sketch.melody[0].n===original+2,'Key transposes melody');assert(sketch.harmony[0].label==='D','Key transposes chord labels');set('bpm','160');assert(sketch.bpm===160&&$('delayMath').textContent.includes('281 ms'),'Tempo updates sketch and delay math');set('bpm','999');assert(state.bpm===160,'Out of range tempo rejected');
  set('chordMode','pulse');assert(sketch.chords.length===96,'Pulsed chord notes');set('chordMode','arp');assert(sketch.chords.length===64,'Arpeggiated chord notes');click('[data-roll="chords"]');assert(state.roll==='chords'&&$('rollCaption').textContent.includes('voiced'),'Chord piano roll');click('[data-roll="bass"]');assert(state.roll==='bass','Bass piano roll');
  click('#favorite');assert(state.favorites.includes(state.id),'Favourite stored');restore();assert(state.favorites.includes(state.id),'Favourite restores');click('#favorite');assert(!state.favorites.includes(state.id),'Favourite removed');
  for(let i=0;i<24;i++){click('[data-artist="'+i+'"]');assert(state.voice===ARTISTS[i][5],'Artist loads its suggested voice '+i);assert(current().style===ARTISTS[i][1],'Artist loads matching study '+i);assert(!$('artistExercise').hidden&&$('artistExercise').textContent.includes(ARTISTS[i][4]),'Artist exercise remains visible '+i);}
  click('[data-artist-filter="goa"]');assert(document.querySelectorAll('[data-artist]').length===2,'Artist style filter');set('artistSearch','hallucinogen','input');assert(document.querySelectorAll('[data-artist]').length===1,'Artist combined search');set('artistSearch','nope-nope','input');assert($('artistGrid').textContent.includes('No artist'),'Artist empty state');set('artistSearch','','input');click('[data-artist-filter="all"]');
  for(const style of STYLES){click('[data-world="'+style.id+'"]');assert(current().style===style.id&&document.querySelectorAll('[data-study]').length===2,'World selects its study and filters library '+style.id);}
  for(const sound of SOUNDS){click('[data-sound="'+sound.id+'"]');assert($('soundRecipe').querySelector('h3').textContent===sound.name,'Sound recipe '+sound.id);assert($('soundRecipe').querySelectorAll('li').length===3,'Three sound build steps '+sound.id);overflow(sound.id);}
  click('[data-use-sound]');assert(state.voice==='pulse','Sound can become melody voice');
  for(const type of Object.keys(ARRANGEMENTS)){click('[data-arrangement="'+type+'"]');for(let i=0;i<ARRANGEMENTS[type].length;i++){click('[data-stage="'+i+'"]');assert($('arrangementDetail').querySelector('h3').textContent===ARRANGEMENTS[type][i][0],'Arrangement '+type+' stage '+i);}overflow(type);}
  const downloads=[];download=(bytes,name,type)=>downloads.push({bytes,name,type});changeStudy('source-1');click('#exportSource');assert(downloads.at(-1).bytes.length===550&&downloads.at(-1).name==='Trance_melody_001.mid','Untouched MIDI download');for(const id of ['exportSketch','exportMelody','exportChords','exportBass']){click('#'+id);assert(String.fromCharCode(...downloads.at(-1).bytes.slice(0,4))==='MThd','MIDI UI export '+id);}await exportLibrary();assert(downloads.at(-1).name.endsWith('.zip')&&downloads.at(-1).bytes.length>200000,'Full library download through UI');
  for(const sound of SOUNDS){const ctx=new OfflineAudioContext(2,24000*3,24000),graph=audioGraph(ctx,ctx.destination,138,1),low=sound.type==='Bass';for(const n of low?[45,45,45]:[69,72,76])playTone(ctx,graph.lanes.melody,{n,d:.4,v:110},.01+(low?0:.1)*(n%3),60/138,sound.id);const rendered=await ctx.startRendering();let peak=0,sum=0;for(let ch=0;ch<2;ch++)for(const n of rendered.getChannelData(ch)){if(!Number.isFinite(n))throw Error('Non-finite '+sound.id);peak=Math.max(peak,Math.abs(n));sum+=n*n;}assert(peak>.001&&peak<1,'Sound renders without silence/clipping '+sound.id);audioStats.push({id:sound.id,peak});graph.dispose();}
  for(const style of STYLES){const item=library.find(i=>!i.source&&i.style===style.id),s=makeSketch(item,{bpm:170,chordMode:'pulse'}),ctx=new OfflineAudioContext(2,24000*4,24000),graph=audioGraph(ctx,ctx.destination,170,1);for(const part of ['melody','chords','bass','drums'])for(const n of s[part].filter(n=>n.t<8)){if(part==='drums')playDrum(ctx,graph.lanes.drums,n,.01+n.t*60/170);else playTone(ctx,graph.lanes[part],n,.01+n.t*60/170,60/170,part==='melody'?style.voice:part==='chords'?'pad':'bass');}const rendered=await ctx.startRendering();let peak=0,sum=0;for(let ch=0;ch<2;ch++)for(const n of rendered.getChannelData(ch)){if(!Number.isFinite(n))throw Error('Non-finite mix');peak=Math.max(peak,Math.abs(n));sum+=n*n;}assert(peak>.001&&peak<1&&sum>0,'Full mix unclipped at maximum volume '+style.id);audioStats.push({id:'mix-'+style.id,peak});graph.dispose();}
  state.source='all';state.style='all';$('styleFilter').value='all';changeStudy('source-1');await startPlayback();assert(AudioStudio.playing&&AudioStudio.active.size>0,'Live playback starts and schedules actual nodes');click('[data-part="melody"]');assert(!AudioStudio.mutes.melody,'Live lane mute');click('[data-part="melody"]');assert(AudioStudio.mutes.melody,'Live lane unmute');stopAll();assert(!AudioStudio.playing&&AudioStudio.active.size===0&&!AudioStudio.graph,'Stop clears live nodes and graph');
  await audition();assert(!!previewGraph&&previewNodes.size>0,'Sound audition starts');stopAll();assert(!previewGraph&&previewNodes.size===0,'Sound audition stops');
  document.body.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',bubbles:true}));await new Promise(r=>setTimeout(r,100));assert(AudioStudio.playing,'Space starts playback');document.body.dispatchEvent(new KeyboardEvent('keydown',{code:'Escape',bubbles:true}));assert(!AudioStudio.playing,'Escape stops');
  state.roll='melody';state.arrangement='uplifting';state.arrangementIndex=0;state.sound='supersaw';state.volume=.55;state.favorites=[];state.chordMode='sustain';changeStudy('source-1');renderSounds();renderArtists();overflow('finished');assert(errors.length===0,'No runtime errors');
 }catch(error){errors.push(error.stack||String(error));stopAll();}
 // Avoid recording a per-sample success entry in the final report.
 const filtered=results.filter(r=>!r.startsWith('Finite '));
 await fetch('/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:errors.length?'failed':'passed',viewport:innerWidth,assertions:filtered.length,results:filtered,audioStats,errors})});
})();
