import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {fileURLToPath,pathToFileURL} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url)),root=path.dirname(dir),qa=path.join(dir,'qa');fs.mkdirSync(qa,{recursive:true});
const args=process.argv.slice(2),capture=args.includes('--capture'),file=args.includes('--file'),width=Number(args.find(a=>a.startsWith('--width='))?.split('=')[1]||1440),section=args.find(a=>a.startsWith('--section='))?.split('=')[1]||'',label=(file?'file-':'')+width+(section?'-'+section:''),height=width<800?1100:1250;
const html=fs.readFileSync(path.join(root,'trance.html'),'utf8'),testCode=fs.readFileSync(path.join(dir,'check-browser.js'),'utf8');let resolveResult;const result=new Promise(resolve=>resolveResult=resolve);
const captureCode=`<script>document.documentElement.style.scrollBehavior='auto';${section?`setTimeout(()=>document.getElementById('${section}').scrollIntoView({behavior:'instant',block:'start'}),100);`:''}</script>`;
const server=http.createServer((req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS'){res.writeHead(204).end();return;}if(req.url==='/result'&&req.method==='POST'){let data='';req.on('data',c=>data+=c);req.on('end',()=>{resolveResult(JSON.parse(data));res.end('ok');});return;}res.setHeader('Content-Type','text/html; charset=utf-8');if((width<800||capture)&&req.url==='/'){res.end(`<!doctype html><style>body{margin:0;background:#0b090b}iframe{width:${width}px;height:${height}px;border:0;display:block}</style><iframe src="/app" allow="autoplay"></iframe>`);return;}res.end(html.replace('</body>',(capture?captureCode:`<script>${testCode}</script>`)+'</body>'));});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let url=`http://127.0.0.1:${server.address().port}/`;
if(file){const filename=path.join(qa,'file-check.html');fs.writeFileSync(filename,html.replace('</body>',`<script>${testCode.replace("fetch('/result'",`fetch('${url}result'`)}</script></body>`));url=pathToFileURL(filename).href;}
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'trance-qa-')),log=fs.openSync(path.join(qa,label+(capture?'-capture':'-test')+'.log'),'w');
const flags=['--headless=new','--disable-gpu','--in-process-gpu','--no-sandbox','--run-all-compositor-stages-before-draw','--disable-threaded-scrolling','--disable-background-networking','--no-first-run','--no-default-browser-check','--hide-scrollbars','--autoplay-policy=no-user-gesture-required',`--window-size=${Math.max(width,500)},${height}`,'--user-data-dir='+profile];
if(capture)flags.push('--screenshot='+path.join(qa,label+'.png'),'--virtual-time-budget=1800');flags.push(url);
const child=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',flags,{windowsHide:true,stdio:['ignore',log,log]});child.on('error',e=>resolveResult({status:'failed',errors:[e.message]}));if(capture)child.on('exit',code=>resolveResult({status:code===0?'passed':'failed',capture:label+'.png'}));const timeout=setTimeout(()=>resolveResult({status:'failed',errors:['50-second browser check timeout']}),50000);const report=await result;clearTimeout(timeout);child.kill();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.closeSync(log);fs.writeFileSync(path.join(qa,label+(capture?'-capture':'-report')+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,viewport:report.viewport,assertions:report.assertions,audioRenders:report.audioStats?.length,capture:report.capture,errors:report.errors},null,2));if(report.status!=='passed')process.exitCode=1;
