let currentCache=null,currentCacheKey='';
function currentV2(){const key=JSON.stringify([state.id,state.dev]);if(key!==currentCacheKey){const base=library.find(x=>x.id===state.id)||library.find(x=>!x.source);currentCache=base.source?base:makeDevelopment(sourceFor(base),{take:base.take,...state.dev});currentCacheKey=key;}return currentCache;}
function activeWindow(){const item=current(),bars=item.beats/4,count=state.viewBars==='all'?bars:Math.min(Number(state.viewBars),bars),start=clamp(state.viewStart,0,Math.max(0,bars-count));return {start:start*4,beats:count*4,bars:count};}
function activeListening(){const win=activeWindow();return listeningSketch(sketch,state.hear,state.loop?win.start:0,state.loop?win.beats:sketch.beats);}
function listenMutes(){return state.hear==='upper'||state.hear==='chordTop'?{melody:true,chords:false,bass:false,drums:false}:state.mutes;}
function renderLibraryV2(){
 const q=$('search').value.trim().toLowerCase(),items=library.filter(s=>(state.source==='all'||s.source===(state.source==='source'))&&(state.style==='all'||s.style===state.style)&&[s.name,s.file||s.originFile,s.style,s.source?'source reference':'development answer ascension'].join(' ').toLowerCase().includes(q));
 $('libraryCount').textContent=items.length+' STUDIES';$('melodyList').innerHTML=items.length?items.map(s=>`<button class="melody-item ${state.id===s.id?'active':''}" data-study="${s.id}" aria-pressed="${state.id===s.id}"><span class="num">${String(library.indexOf(s)+1).padStart(2,'0')}</span><span><strong>${esc(s.name)}${state.favorites.includes(s.id)?' ★':''}</strong><small>${s.source?esc(s.file):'FROM '+esc(s.originFile)}<br>${s.beats/4} BARS · ${s.style.toUpperCase()}</small></span><span class="mini-wave" aria-hidden="true"><i></i><i></i><i></i><i></i></span></button>`).join(''):'<p class="empty">No melodies match. Try another search or style.</p>';syncPressed('#sourceTabs button','source',state.source);
}
function renderDevelopment(){
 const item=current(),source=sourceFor(item),siblings=library.filter(x=>x.originId===source.id&&!x.source);
 $('referenceFamily').innerHTML=`<div><span class="tiny red">YOUR REFERENCE → TWO NEW DIRECTIONS</span><strong>${esc(source.file)}</strong></div><div class="family-buttons">${[[source.id,'Source / '+source.beats/4+' bars'],...siblings.map(s=>[s.id,s.take?'Ascension / 16':'New horizon / 8'])].map(([id,name])=>`<button data-family="${id}" class="${id===state.id?'active':''}" aria-pressed="${id===state.id}">${name}</button>`).join('')}</div>`;
 $('developmentControls').disabled=item.source;$('developmentHint').textContent=item.source?'Select New horizon or Ascension above to develop this reference. The source itself is preserved.':'The opening motif is protected when you ask for a new answer. Adjust the contour, movement and rhythm to reshape the full phrase.';
 const settings=item.settings||{bars:8,arc:'arch',motion:7,density:'source',seed:0};$('phraseLength').value=settings.bars;$('arcSelect').value=settings.arc;$('movement').value=settings.motion;$('densitySelect').value=settings.density;$('answerSeed').textContent='ANSWER '+String(settings.seed+1).padStart(2,'0');
 $('undoAnswer').disabled=!devHistory.length||item.source;
 $('listenMode').value=state.hear;$('rollZoom').value=state.viewBars;$('loopWindow').setAttribute('aria-pressed',String(state.loop));$('loopWindow').classList.toggle('active',state.loop);
 const m=phraseMetrics(sketch.topline,sketch.beats);$('melodyMetrics').innerHTML=`<span><b>${m.unique}</b> MELODIC PITCHES</span><span><b>${m.range}</b> SEMITONES OF TRAVEL</span><span><b>${noteName(m.low)} → ${noteName(m.high)}</b> UPPER RANGE</span><span><b>BAR ${m.peakBar}</b> FIRST HIGH POINT</span>`;
 renderPhraseOverview();
}
function renderPhraseOverview(){const item=current(),m=phraseMetrics(sketch.topline,sketch.beats),win=activeWindow();$('phraseOverview').innerHTML=m.bars.map((b,i)=>`<button data-phrase-bar="${i}" class="phrase-bar ${i*4>=win.start&&i*4<win.start+win.beats?'selected':''}" aria-label="View bar ${i+1}: ${item.roles?.[i]||'source phrase'}" aria-pressed="${i*4>=win.start&&i*4<win.start+win.beats}" style="--pitch-height:${b?20+(b.mean-m.low)/Math.max(1,m.range)*70:5}%"><span>${String(i+1).padStart(2,'0')}</span><i></i><small>${item.roles?.[i]&&(!i||item.roles[i]!==item.roles[i-1])?item.roles[i]:!item.roles&&i%4===0?'SOURCE':''}</small></button>`).join('');$('phraseExplanation').textContent=item.source?'The line shows upper-voice pitch movement through the complete source. Click a bar to inspect it; use Loop view to work on that phrase.':'Statement → answer → climax → resolution. The overview shows the actual average pitch in each bar, so you can see where the melody travels.';}
function renderRollV2(){
 const win=activeWindow(),all=sketch[state.roll],notes=all.filter(n=>n.t<win.start+win.beats&&n.t+n.d>win.start),pool=notes.length?notes:all,low=Math.floor(Math.min(...pool.map(n=>n.n))-2),high=Math.ceil(Math.max(...pool.map(n=>n.n))+2),range=high-low+1,W=900,H=270,left=43,top=23,innerW=W-left-9,row=(H-top-8)/range,x=t=>left+(t-win.start)/win.beats*innerW,y=n=>top+(high-n)*row;
 let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="${state.roll} piano roll, bars ${win.start/4+1} to ${(win.start+win.beats)/4}"><title>${esc(current().name)} — ${state.roll}</title><rect width="${W}" height="${H}" fill="#100b10"/>`;
 for(let n=low;n<=high;n++){const black=[1,3,6,8,10].includes(mod(n,12));svg+=`<rect x="${left}" y="${y(n)}" width="${innerW}" height="${row}" fill="${black?'#180e16':'#100b10'}"/><line x1="0" x2="${W}" y1="${y(n)}" y2="${y(n)}" stroke="#34202a" stroke-width=".4"/>`;if(mod(n,12)===0||range<=21&&!black)svg+=`<text x="5" y="${y(n)+row*.75}" fill="#bc96a6" font-family="Consolas,monospace" font-size="${Math.min(11,row*.8)}">${noteName(n)}</text>`;}
 for(let t=win.start;t<=win.start+win.beats;t+=.25){const bar=t%4===0,beat=t%1===0;svg+=`<line x1="${x(t)}" x2="${x(t)}" y1="${top}" y2="${H}" stroke="${bar?'#6e3544':beat?'#38212c':'#24141e'}" stroke-width="${bar?1:.5}"/>`;if(bar&&t<win.start+win.beats)svg+=`<text x="${x(t)+5}" y="15" fill="#c995a5" font-size="10" font-family="Consolas,monospace">${String(t/4+1).padStart(2,'0')}</text>`;}
 const upperKeys=new Set(sketch.topline.map(n=>n.t.toFixed(7)+':'+n.n));
 if(['melody','topline'].includes(state.roll)){const contour=sketch.topline.filter(n=>n.t>=win.start&&n.t<win.start+win.beats);svg+=`<polyline points="${contour.map(n=>`${x(n.t)+2},${y(n.n)+row/2}`).join(' ')}" fill="none" stroke="#ffc5a1" stroke-width="1.4" opacity=".5"/>`;}
 notes.forEach(n=>{const t=Math.max(n.t,win.start),end=Math.min(n.t+n.d,win.start+win.beats),isPedal=state.roll==='melody'&&!upperKeys.has(n.t.toFixed(7)+':'+n.n);svg+=`<rect x="${x(t)+.6}" y="${y(n.n)+.8}" width="${Math.max(2,(end-t)/win.beats*innerW-1.2)}" height="${Math.max(2,row-1.6)}" rx="1" fill="${isPedal?'#765264':state.roll==='chords'?'#c685ac':state.roll==='bass'?'#e7a15f':'#ff7465'}" opacity="${.6+n.v/318}"><title>${noteName(n.n)} · bar ${Math.floor(n.t/4)+1} · beat ${(mod(n.t,4)+1).toFixed(2)} · ${n.d.toFixed(2)} beats</title></rect>`;});
 svg+=`<line id="playhead" class="playhead" x1="${left}" x2="${left}" y1="${top}" y2="${H}" opacity="0"/></svg>`;$('pianoRoll').innerHTML=svg;$('rollMeta').textContent=`BARS ${win.start/4+1}–${(win.start+win.beats)/4} / ${sketch.beats/4}`;$('rollCaption').textContent=state.roll==='topline'?'Upper melodic voice · contour connected':state.roll==='melody'?'Full note content · low/supporting voices in purple':state.roll==='chords'?'Actual voiced chord notes':'Bass follows the suggested chord roots';syncPressed('[data-roll]','roll',state.roll);
 $('prevBars').disabled=win.start===0;$('nextBars').disabled=win.start+win.beats>=sketch.beats;
 $('chordCards').innerHTML=sketch.harmony.filter(c=>c.t>=win.start&&c.t<win.start+win.beats).map(c=>`<div class="chord-card"><small>BAR ${String(c.t/4+1).padStart(2,'0')}</small><strong>${c.label}</strong><span>${c.notes.map(noteName).join(' · ')}</span><span>TOP ${noteName(c.notes.at(-1))} / ROOT ${pitch(c.root)}</span></div>`).join('');$('harmonyHint').textContent='Suggested harmony for the visible bars. Export Chords for the full phrase, or Chord top line for its highest voice.';
}
function renderStudioV2(){const item=current(),style=STYLES.find(x=>x.id===item.style);sketch=makeSketch(item,state);state.viewStart=activeWindow().start/4;
 $('studyMeta').textContent=`${item.source?'YOUR MIDI / '+item.file:'DEVELOPED FROM / '+item.originFile} · ${item.beats/4} BARS`;$('studyName').textContent=item.name;$('studyDescription').textContent=item.explain;
 $('keySelect').innerHTML=Array.from({length:12},(_,pc)=>{let shift=mod(pc-item.root,12);if(shift>6)shift-=12;return `<option value="${shift}">${PITCHES[pc]} ${item.mode}</option>`;}).join('');$('keySelect').value=state.shift;$('bpm').value=state.bpm;$('voiceSelect').value=state.voice;$('chordMode').value=state.chordMode;$('volume').value=state.volume*100;
 $('variations').innerHTML=TREATMENTS.map(([id,name])=>`<button data-variant="${id}" class="${state.variant===id?'active':''}" aria-pressed="${state.variant===id}">${name}</button>`).join('');$('variationHint').textContent=TREATMENTS.find(t=>t[0]===state.variant)[2];$('variationNumber').textContent=String(TREATMENTS.findIndex(t=>t[0]===state.variant)+1).padStart(2,'0')+' / '+TREATMENTS.length.toString().padStart(2,'0');
 const fav=state.favorites.includes(item.id);$('favorite').textContent=fav?'★':'☆';$('favorite').setAttribute('aria-pressed',String(fav));$('exportSource').hidden=!item.source;$('nowPlaying').textContent=item.name;$('transportInfo').textContent=`${state.bpm} BPM · ${pitch(item.root+state.shift)} ${item.mode.toUpperCase()}`;$('delayMath').textContent=`At ${state.bpm} BPM: quarter note = ${Math.round(60000/state.bpm)} ms, eighth = ${Math.round(30000/state.bpm)} ms, dotted eighth = ${Math.round(45000/state.bpm)} ms, sixteenth = ${Math.round(15000/state.bpm)} ms.`;
 const audible=listenMutes();document.querySelectorAll('[data-part]').forEach(b=>{b.classList.toggle('on',audible[b.dataset.part]);b.setAttribute('aria-pressed',String(audible[b.dataset.part]));b.disabled=state.hear!=='full';});$('artistExercise').hidden=state.artist===null;if(state.artist!==null){const a=ARTISTS[state.artist];$('artistExercise').innerHTML='<b>'+esc(a[0])+' / Writing exercise.</b> '+esc(a[4]);}
 renderDevelopment();renderRollV2();renderPosition();save();
}
function renderPositionV2(){const win=activeWindow(),pos=AudioStudio.position()+(state.loop?win.start:0),bar=Math.floor(pos/4)+1;$('beatDisplay').innerHTML=String(bar).padStart(2,'0')+`<span> / ${String(sketch.beats/4).padStart(2,'0')}</span>`;const line=$('playhead');if(line){const x=43+(pos-win.start)/win.beats*848;line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('opacity',AudioStudio.playing&&pos>=win.start&&pos<win.start+win.beats?'1':'0');}document.querySelectorAll('[data-phrase-bar]').forEach(b=>b.classList.toggle('sounding',AudioStudio.playing&&Number(b.dataset.phraseBar)===bar-1));}
const devHistory=[];
function changeDevelopment(key,value){if(current().source)return;devHistory.push({...state.dev});if(devHistory.length>20)devHistory.shift();state.dev={...current().settings,[key]:value};state.variant='original';state.viewStart=0;updateComposition();}
function initLab(){
 document.querySelectorAll('[data-count]').forEach(el=>el.textContent=LIBRARY_COUNTS[el.dataset.count]);
 $('sourceTotal').textContent=`${LIBRARY_COUNTS.sources} SOURCES + ${LIBRARY_COUNTS.studies} MELODIC DEVELOPMENTS`;
 $('downloadLibrary').textContent=`Download all ${LIBRARY_COUNTS.treatments} sketches ↓`;
 $('phraseLength').addEventListener('change',e=>changeDevelopment('bars',Number(e.target.value)));$('arcSelect').addEventListener('change',e=>changeDevelopment('arc',e.target.value));$('movement').addEventListener('change',e=>changeDevelopment('motion',Number(e.target.value)));$('densitySelect').addEventListener('change',e=>changeDevelopment('density',e.target.value));
 $('newAnswer').addEventListener('click',()=>{changeDevelopment('seed',(current().settings.seed+1)%9999);notify('A new answer. Your opening motif is preserved.');});$('undoAnswer').addEventListener('click',()=>{if(devHistory.length){state.dev=devHistory.pop();updateComposition();}});$('resetDevelopment').addEventListener('click',()=>{devHistory.push({...state.dev});state.dev={};updateComposition();});
 $('listenMode').addEventListener('change',e=>{state.hear=e.target.value;updateComposition();});$('rollZoom').addEventListener('change',e=>{state.viewBars=e.target.value;state.viewStart=0;updateComposition();});
 const move=direction=>{state.viewStart=clamp(state.viewStart+direction*activeWindow().bars,0,sketch.beats/4-activeWindow().bars);if(state.loop)updateComposition();else{renderRoll();renderPhraseOverview();}};
 $('prevBars').addEventListener('click',()=>move(-1));$('nextBars').addEventListener('click',()=>move(1));$('loopWindow').addEventListener('click',()=>{state.loop=!state.loop;updateComposition();});
 $('exportTopline').addEventListener('click',()=>exportPart('topline'));$('exportChordTop').addEventListener('click',()=>exportPart('chordTop'));
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.family){state.source='all';state.style='all';$('styleFilter').value='all';$('search').value='';changeStudy(b.dataset.family);}if(b.dataset.phraseBar!==undefined){state.viewBars='4';state.viewStart=clamp(Number(b.dataset.phraseBar),0,sketch.beats/4-4);$('rollZoom').value='4';if(state.loop)updateComposition();else{renderRoll();renderPhraseOverview();}}});
}
