import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url),html=fs.readFileSync(new URL('trance.html',root),'utf8'),js=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ctx={console,Uint8Array,TextEncoder,Math};vm.createContext(ctx);vm.runInContext(js.slice(0,js.indexOf('const $=id=>'))+'\nthis.T={SOURCES,STYLES,SOUNDS,ARTISTS,TREATMENTS,library,makeSketch,midiBytes,zipBytes,crc32};',ctx);const T=ctx.T;
function parse(bytes){const b=Buffer.from(bytes);assert.equal(b.toString('ascii',0,4),'MThd');assert.equal(b.readUInt32BE(4),6);const count=b.readUInt16BE(10),ppq=b.readUInt16BE(12);let p=14,tracks=[];const vlq=()=>{let n=0,x;do{x=b[p++];n=n*128+(x&127);}while(x&128);return n;};
 for(let tr=0;tr<count;tr++){assert.equal(b.toString('ascii',p,p+4),'MTrk');const length=b.readUInt32BE(p+4);p+=8;const stop=p+length;let tick=0,name='',end=false,tempo=null;const active=new Map(),notes=[];while(p<stop){tick+=vlq();const s=b[p++];if(s===255){const type=b[p++],len=vlq();if(type===3)name=b.toString('ascii',p,p+len);if(type===81)tempo=60000000/b.readUIntBE(p,3);if(type===47){assert.equal(len,0);end=true;}p+=len;}else{assert([128,144].includes(s&240));const n=b[p++],v=b[p++];assert(n<=127&&v<=127);if((s&240)===144){const key=(s&15)+':'+n;assert(!active.has(key),'overlapping repeated note '+key+' in '+name);active.set(key,{n,t:tick/ppq,v});}else{const key=(s&15)+':'+n;assert(active.has(key),'note off paired');const note=active.get(key);notes.push({...note,d:tick/ppq-note.t});active.delete(key);}}}assert.equal(p,stop);assert(end);assert.equal(active.size,0);tracks.push({notes,end:tick/ppq,name,tempo});}assert.equal(p,b.length);return tracks;
}
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
test('Catalog has 12 embedded sources, 16 originals, 24 artist perspectives, 16 sounds and 168 treatments',()=>{assert.equal(T.SOURCES.length,12);assert.equal(T.library.length,28);assert.equal(T.ARTISTS.length,24);assert.equal(T.SOUNDS.length,16);assert.equal(T.library.length*T.TREATMENTS.length,168);});
test('Source downloads retain exact file bytes and original playback retains all events',()=>{for(const source of T.SOURCES){assert.deepEqual(Buffer.from(source.original,'base64'),fs.readFileSync(new URL('material/'+source.file,root)));assert.equal(source.notes.length,64);assert.equal(source.beats,16);assert.equal(source.bpm,null);const sketch=T.makeSketch(T.library.find(x=>x.id===source.id));assert.equal(JSON.stringify(sketch.melody),JSON.stringify(source.notes));}});
test('Every treatment, chord motion and transposition produces bounded musical parts',()=>{for(const item of T.library)for(const [variant]of T.TREATMENTS)for(const chordMode of ['sustain','pulse','arp'])for(let shift=-5;shift<=6;shift++){const s=T.makeSketch(item,{variant,chordMode,shift});for(const part of ['melody','chords','bass','drums']){assert(s[part].length>0);for(const n of s[part]){assert(Number.isInteger(n.n)&&n.n>=0&&n.n<=127);assert(n.t>=0&&n.t<s.beats);assert(n.d>0&&n.t+n.d<=s.beats+.000001);assert(n.v>0&&n.v<=127);}}assert.equal(s.harmony.length,s.beats/4);for(const h of s.harmony)assert(h.notes.every((n,i)=>!i||n>h.notes[i-1]));}});
test('All 504 arranged MIDI combinations round-trip with exact notes, loop bounds and tempo',()=>{for(const item of T.library)for(const [variant]of T.TREATMENTS)for(const chordMode of ['sustain','pulse','arp']){const sketch=T.makeSketch(item,{variant,chordMode,bpm:143}),tracks=parse(T.midiBytes(sketch));assert.equal(tracks.length,5);assert(Math.abs(tracks[0].tempo-143)<.001);for(let i=0;i<4;i++){const part=['melody','chords','bass','drums'][i],track=tracks[i+1];assert.equal(track.name,part);assert.equal(track.end,sketch.beats);assert.equal(track.notes.length,sketch[part].length);const sort=(a,b)=>a.t-b.t||a.n-b.n;const original=[...sketch[part]].sort(sort),read=track.notes.sort(sort);for(let j=0;j<read.length;j++){assert.equal(read[j].n,original[j].n);assert.equal(read[j].v,original[j].v);assert(Math.abs(read[j].t-original[j].t)<=1/480);assert(Math.abs(read[j].d-original[j].d)<=2/480);}}}});
test('Single-part exports carry only the selected part plus conductor metadata',()=>{for(const part of ['melody','chords','bass','drums']){const s=T.makeSketch(T.library[0]),tracks=parse(T.midiBytes(s,[part]));assert.equal(tracks.length,2);assert.equal(tracks[1].name,part);}});
test('168-file ZIP has consistent local and central records, CRCs and extractable MIDI',()=>{const files=T.library.flatMap(item=>T.TREATMENTS.map(([variant])=>({name:item.id+'-'+variant+'.mid',bytes:T.midiBytes(T.makeSketch(item,{variant}))}))),zip=Buffer.from(T.zipBytes(files));let p=0,i=0;while(zip.readUInt32LE(p)===0x04034b50){const crc=zip.readUInt32LE(p+14),len=zip.readUInt32LE(p+18),nameLen=zip.readUInt16LE(p+26),extraLen=zip.readUInt16LE(p+28),name=zip.toString('ascii',p+30,p+30+nameLen),start=p+30+nameLen+extraLen,data=zip.subarray(start,start+len);assert.equal(name,files[i].name);assert.equal(T.crc32(data),crc);assert.deepEqual(data,Buffer.from(files[i].bytes));parse(data);p=start+len;i++;}assert.equal(i,168);const centralStart=p;for(let c=0;c<i;c++){assert.equal(zip.readUInt32LE(p),0x02014b50);const len=zip.readUInt16LE(p+28);p+=46+len;}assert.equal(zip.readUInt32LE(p),0x06054b50);assert.equal(zip.readUInt16LE(p+10),168);assert.equal(zip.readUInt32LE(p+16),centralStart);assert.equal(p+22,zip.length);});
test('Every variation changes every study without altering the source',()=>{for(const item of T.library){const before=JSON.stringify(item.notes),original=JSON.stringify(T.makeSketch(item).melody);for(const [variant]of T.TREATMENTS.slice(1))assert.notEqual(JSON.stringify(T.makeSketch(item,{variant}).melody),original,item.id+' '+variant);assert.equal(JSON.stringify(item.notes),before);}});
test('Static anchors and external-dependency-free standalone document are valid',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]).filter(id=>!id.includes('$'));assert.equal(new Set(ids).size,ids.length);for(const [,id]of html.matchAll(/href="#([^"]+)"/g))assert(ids.includes(id),id);assert(!/<script[^>]+src=|<link[^>]+stylesheet/.test(html));assert(!html.includes('__CSS__')&&!html.includes('__SCRIPT__'));});
console.log(checks+' suites passed.');
