/* Original composition recipes. Degrees are zero-based; rhythms use sixteenth steps. */
const ROLES = ['melody','bass','chords','arp','drums'];
const ROLE_NAMES = {melody:'Melody',bass:'Bass',chords:'Chords',arp:'Arpeggio',drums:'Drums'};
const NOTE_NAMES = ['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];
const MODES = {
  minor:[0,2,3,5,7,8,10], major:[0,2,4,5,7,9,11], dorian:[0,2,3,5,7,9,10],
  phrygian:[0,1,3,5,7,8,10], lydian:[0,2,4,6,7,9,11], mixolydian:[0,2,4,5,7,9,10],
  harmonic:[0,2,3,5,7,8,11], melodic:[0,2,3,5,7,9,11]
};
const MODE_NAMES={minor:'Natural minor',major:'Major',dorian:'Dorian',phrygian:'Phrygian',lydian:'Lydian',mixolydian:'Mixolydian',harmonic:'Harmonic minor',melodic:'Melodic minor'};
const MOODS = {
  'Native':{density:1,gate:1,vel:0,lift:0},
  'Euphoric':{density:1.1,gate:1.1,vel:7,lift:7},
  'Melancholic':{density:.72,gate:1.5,vel:-10,lift:0},
  'Hypnotic':{density:.9,gate:.85,vel:-3,lift:0},
  'Dark':{density:.8,gate:1.2,vel:0,lift:-7},
  'Playful':{density:1.15,gate:.65,vel:5,lift:0},
  'Dreamy':{density:.6,gate:1.85,vel:-15,lift:7},
  'Aggressive':{density:1.2,gate:.7,vel:14,lift:0},
  'Soulful':{density:.85,gate:1.25,vel:-4,lift:0}
};
// Each genre supplies its own rhythm, pitch vocabulary, bass articulation and two harmonic paths.
const GENRES = [
 {id:'deep',name:'Deep house',bpm:122,mode:'dorian',mood:'Soulful',artist:'Kerri Chandler · Larry Heard',title:'Velvet room',rh:[0,3,6,10,14],mot:[2,4,6,4,1,2,0,6],bass:'funk',chord:'stab',arp:'updown',drum:'house',prog:[[0,3,0,4],[0,5,3,4]],ext:4,swing:18,tip:'Let the bass answer the chord stabs. Shorten the low notes before adding more sidechain.',sound:'Rounded organ or electric piano; low-pass the chord bus and leave the ninth audible.'},
 {id:'disco',name:'Disco / French house',bpm:124,mode:'minor',mood:'Playful',artist:'Daft Punk · Alan Braxe',title:'Chrome avenue',rh:[0,2,5,7,10,13,15],mot:[0,2,4,7,6,4,2,1],bass:'disco',chord:'chop',arp:'up',drum:'disco',prog:[[5,4,3,0],[3,6,2,0]],ext:4,swing:12,tip:'Pair octave bass pickups with short, uneven chord chops. Keep one beat empty in the turnaround.',sound:'Dry picked bass, filtered saw chords and a small room. Automate filter opening over eight bars.'},
 {id:'piano',name:'Piano house',bpm:126,mode:'major',mood:'Euphoric',artist:'MK · David Morales',title:'Open arms',rh:[0,3,6,8,11,14],mot:[4,4,2,0,1,2,4,7],bass:'offbeat',chord:'piano',arp:'updown',drum:'house',prog:[[0,4,5,3],[0,5,3,4]],ext:3,swing:8,tip:'Use a broad top-line over a restrained bass. The anticipation before beat four is the hook.',sound:'Bright piano with controlled release; high-pass its low octave to make space for the bass.'},
 {id:'techhouse',name:'Tech house',bpm:128,mode:'minor',mood:'Playful',artist:'Chris Lake · FISHER',title:'Pocket pressure',rh:[2,5,6,11,14],mot:[0,0,2,0,4,3,0,7],bass:'skip',chord:'stab',arp:'pedal',drum:'house',prog:[[0,0,3,0],[0,6,0,4]],ext:3,swing:20,tip:'Repeat the short bass cell, then change its last two hits. Silence around the kick adds weight.',sound:'Mono saw bass with a fast filter envelope. Use an octave pluck as the melody response.'},
 {id:'minimal',name:'Minimal / microhouse',bpm:125,mode:'dorian',mood:'Hypnotic',artist:'Ricardo Villalobos · Akufen',title:'Small machinery',rh:[1,6,9,15],mot:[0,3,1,4,2,6,1],bass:'sparse',chord:'sparse',arp:'fifths',drum:'minimal',prog:[[0,0,1,0],[0,3,0,6]],ext:4,swing:25,tip:'Use one surprising placement per bar. Change velocity and length before adding pitches.',sound:'Sine-based bass and a tiny percussive pluck. Keep delay return quieter than the dry hit.'},
 {id:'afro',name:'Afro house',bpm:120,mode:'dorian',mood:'Soulful',artist:'Black Coffee · Keinemusik',title:'Copper sun',rh:[0,3,6,8,11,14],mot:[0,2,4,2,5,4,1,0],bass:'tresillo',chord:'sustain',arp:'euclid',drum:'afro',prog:[[0,3,4,3],[0,6,3,0]],ext:4,swing:10,tip:'Keep the melodic cell singable while percussion supplies the cross-rhythm. Try a 3–3–2 bass answer.',sound:'Mallet pluck over a warm sustained chord; use separate short and long reverbs.'},
 {id:'organic',name:'Organic house',bpm:116,mode:'minor',mood:'Dreamy',artist:'Sébastien Léger · Tim Green',title:'Tidal garden',rh:[0,3,7,10,14],mot:[0,4,2,6,4,7,5,2],bass:'sustain',chord:'sustain',arp:'updown',drum:'afro',prog:[[0,5,2,6],[0,3,5,4]],ext:4,swing:14,tip:'Give the upper motif a two-bar breath. Move a single inner chord voice in the second half.',sound:'Soft mallet attack, long filtered ambience and a bass with very little upper-mid buzz.'},
 {id:'melodic',name:'Melodic house',bpm:123,mode:'minor',mood:'Melancholic',artist:'Ben Böhmer · Lane 8',title:'Last light',rh:[0,2,6,8,11,14],mot:[2,4,7,6,4,2,1,0],bass:'offbeat',chord:'sustain',arp:'updown',drum:'house',prog:[[0,5,2,6],[5,6,0,3]],ext:4,swing:0,tip:'Keep the opening motif recognisable. Let the peak arrive in bar seven, then leave a tail.',sound:'Soft saw pluck with a slower filter decay; widen the lead above the mono bass.'},
 {id:'progressive',name:'Progressive house',bpm:128,mode:'minor',mood:'Euphoric',artist:'deadmau5 · Eric Prydz',title:'Skyline circuit',rh:[0,3,6,9,12,14],mot:[0,4,7,4,2,6,4,1],bass:'rolling',chord:'pulse',arp:'dotted',drum:'house',prog:[[0,5,2,6],[3,5,0,6]],ext:3,swing:0,tip:'Let a repeating dotted rhythm cross the bar line. Expand the register only in the release section.',sound:'Layer a narrow pluck with a quiet octave; increase sustain and filter cutoff together.'},
 {id:'melotech',name:'Melodic techno',bpm:126,mode:'harmonic',mood:'Dark',artist:'Anyma · Stephan Bodzin',title:'Black horizon',rh:[0,3,5,8,11,15],mot:[0,4,3,1,0,6,7,4],bass:'offbeat',chord:'pulse',arp:'down',drum:'techno',prog:[[0,5,3,4],[0,1,5,4]],ext:3,swing:0,tip:'Make one interval carry the tension. The raised seventh in harmonic minor creates a strong return.',sound:'Mono resonant lead with restrained glide; reserve stereo spread for reverb and upper layers.'},
 {id:'detroit',name:'Detroit techno',bpm:132,mode:'dorian',mood:'Soulful',artist:'Jeff Mills · Robert Hood',title:'Future memory',rh:[0,2,5,8,10,13],mot:[0,4,1,5,2,6,3,7],bass:'motor',chord:'stab',arp:'fifths',drum:'techno',prog:[[0,3,0,6],[0,1,3,4]],ext:4,swing:6,tip:'Use the upper sequence as a counterweight to the motor bass. Hold the harmony for longer than the riff.',sound:'Dry FM pluck, warm minor-seventh stabs and a short, consistent bass envelope.'},
 {id:'dub',name:'Dub techno',bpm:122,mode:'minor',mood:'Hypnotic',artist:'Basic Channel · Deepchord',title:'Submerged signal',rh:[0,6,11],mot:[2,4,6,4,1,0],bass:'sparse',chord:'dub',arp:'sparse',drum:'minimal',prog:[[0,0,2,0],[0,3,0,5]],ext:5,swing:10,tip:'A single chord can carry the loop. Send the offbeat stab into delay and automate the return tone.',sound:'Soft minor ninths into filtered feedback delay; keep the sub dry and almost static.'},
 {id:'hardtech',name:'Hard / industrial techno',bpm:148,mode:'phrygian',mood:'Aggressive',artist:'Dax J · Paula Temple',title:'Iron teeth',rh:[0,1,4,6,8,9,12,15],mot:[0,1,0,4,0,1,7,4],bass:'motor',chord:'stab',arp:'pedal',drum:'hard',prog:[[0,1,0,1],[0,0,6,1]],ext:3,swing:0,tip:'The flat second supplies the abrasion. Leave the low octave simple when distortion becomes dense.',sound:'Short distorted bass and a narrow stab; shape the reverb tail separately from the kick.'},
 {id:'acid',name:'Acid house / techno',bpm:134,mode:'minor',mood:'Hypnotic',artist:'Phuture · Josh Wink',title:'Liquid wire',rh:[0,1,3,6,7,9,12,14,15],mot:[0,7,0,2,4,0,6,4,1],bass:'acid',chord:'sparse',arp:'random',drum:'techno',prog:[[0,0,0,6],[0,3,0,4]],ext:3,swing:8,tip:'Contrast low repeated notes with octave jumps and accents. Add synth glide after importing the MIDI.',sound:'Mono saw, resonant low-pass and a snappy filter envelope. MIDI velocity supplies accent cues.'},
 {id:'trance',name:'Uplifting trance',bpm:138,mode:'minor',mood:'Euphoric',artist:'Paul van Dyk · Ferry Corsten',title:'Northern bloom',rh:[0,2,4,6,8,10,12,14],mot:[0,4,7,6,4,2,4,1],bass:'offbeat',chord:'pulse',arp:'up',drum:'trance',prog:[[0,5,2,6],[5,6,0,4]],ext:3,swing:0,tip:'Repeat the first phrase before the octave lift. Keep the offbeat bass short so the kick breathes.',sound:'Supersaw lead with a clear central voice; high-pass the stereo layer and automate the filter.'},
 {id:'psy',name:'Psytrance',bpm:145,mode:'phrygian',mood:'Hypnotic',artist:'Astrix · Infected Mushroom',title:'Fractal trail',rh:[0,1,3,5,6,9,11,13,15],mot:[0,1,4,0,3,1,7,4,0],bass:'psy',chord:'sparse',arp:'random',drum:'trance',prog:[[0,0,1,0],[0,3,1,0]],ext:3,swing:0,tip:'Keep the three bass hits after each kick precise. Let the upper sequence take the irregular phrasing.',sound:'Short saw bass with almost no release; automate lead resonance and formant colour in phrases.'},
 {id:'ukg',name:'UK garage',bpm:132,mode:'minor',mood:'Playful',artist:'MJ Cole · Todd Edwards',title:'Night bus',rh:[1,3,6,9,11,14],mot:[2,0,4,2,6,4,1,0],bass:'garage',chord:'garage',arp:'skip',drum:'garage',prog:[[0,3,6,2],[0,5,3,4]],ext:4,swing:32,tip:'Separate the kick and bass pickups. Keep chord hits very short and let the swung hats connect them.',sound:'Sine sub with a soft second harmonic; bright organ stabs and a small, tight room.'},
 {id:'basshouse',name:'Bass house',bpm:128,mode:'minor',mood:'Aggressive',artist:'JOYRYDE · Habstrakt',title:'Rubber voltage',rh:[0,3,6,7,10,14],mot:[0,0,7,4,3,0,2,0],bass:'wobble',chord:'stab',arp:'pedal',drum:'house',prog:[[0,0,5,4],[0,6,3,0]],ext:3,swing:12,tip:'Use short call-and-response blocks. Different envelopes on repeated notes create the bass conversation.',sound:'Split clean sub from a filtered mid-bass layer. Map velocity to filter depth for the accented hits.'},
 {id:'breaks',name:'Breakbeat / electronica',bpm:132,mode:'minor',mood:'Melancholic',artist:'Bicep · Overmono',title:'Afterimage',rh:[0,3,6,8,10,13,15],mot:[0,4,2,6,7,4,2,1],bass:'breaks',chord:'sustain',arp:'dotted',drum:'breaks',prog:[[0,5,3,6],[5,2,0,6]],ext:4,swing:10,tip:'Let the melody float across the snare. Repeat the emotional interval while the bass stays grounded.',sound:'Soft detuned pluck, slowly opening pads and a rounded sub. Keep the break transient clear.'},
 {id:'electro',name:'Electro',bpm:134,mode:'minor',mood:'Dark',artist:'Drexciya · Anthony Rother',title:'Neon trench',rh:[0,2,5,7,9,12,14],mot:[0,7,4,0,3,7,1,4],bass:'electro',chord:'stab',arp:'fifths',drum:'electro',prog:[[0,0,3,6],[0,5,0,4]],ext:3,swing:0,tip:'Make the bass rhythm converse with the broken kick. Use the octave as a punctuation mark.',sound:'Dry square-wave bass, metallic FM lead and short gated ambience.'},
 {id:'liquid',name:'Liquid drum & bass',bpm:174,mode:'dorian',mood:'Soulful',artist:'Calibre · High Contrast',title:'Rain on glass',rh:[0,3,6,10,14],mot:[2,4,6,7,4,2,1,0],bass:'reese',chord:'sustain',arp:'sparse',drum:'dnb',prog:[[0,3,5,4],[0,6,2,3]],ext:5,swing:8,tip:'Long bass notes make space under the fast drums. Let the melodic answer occupy the second bar.',sound:'Warm filtered Reese, electric piano ninths and a soft lead. Keep bass unison out of the sub.'},
 {id:'neuro',name:'Neurofunk',bpm:174,mode:'phrygian',mood:'Aggressive',artist:'Noisia · Mefjus',title:'Broken alloy',rh:[0,1,5,6,8,11,14,15],mot:[0,1,4,0,7,3,1,0],bass:'neuro',chord:'sparse',arp:'random',drum:'dnb',prog:[[0,1,0,3],[0,0,1,4]],ext:3,swing:0,tip:'Alternate a held bass growl with quick fragments. Resample different tones onto the same note rhythm.',sound:'Clean sub plus an FM or wavetable mid layer. The exported rhythm is a scaffold for sound design.'},
 {id:'dubstep',name:'Dubstep / halftime',bpm:140,mode:'minor',mood:'Dark',artist:'Mala · Digital Mystikz',title:'Half-lit space',rh:[0,3,7,10,15],mot:[0,4,1,0,6,3,0,2],bass:'halftime',chord:'dub',arp:'sparse',drum:'halftime',prog:[[0,0,5,3],[0,6,0,4]],ext:3,swing:15,tip:'Treat the snare on beat three as the anchor. Let sub notes ring, then leave a full beat of air.',sound:'Sine sub, short filtered chord echoes and very sparse high percussion.'},
 {id:'future',name:'Future bass',bpm:150,mode:'major',mood:'Dreamy',artist:'Flume · San Holo',title:'Paper satellites',rh:[0,3,6,9,10,14],mot:[4,7,6,2,4,1,2,0],bass:'halftime',chord:'future',arp:'skip',drum:'halftime',prog:[[3,0,5,4],[5,3,0,4]],ext:4,swing:18,tip:'Use chord retriggers as a rhythm instrument. Leave room for the melodic pickup before the next chord.',sound:'Wide saw chords with a fast amplitude envelope, a quiet pluck and an independent mono sub.'}
];
const TREATMENTS = [
 {name:'Statement',emotion:null,desc:'A clear motif, stable bass and the native harmonic path.'},
 {name:'Conversation',emotion:'Playful',desc:'A shorter answer, displaced pickups and an alternate harmonic path.'},
 {name:'Release',emotion:'Euphoric',desc:'More activity, rising answers, open voicings and a final register lift.'},
 {name:'After hours',emotion:'Dreamy',desc:'More space, lower velocities, longer tones and a restrained ending.'}
];
const BASS_RHYTHMS = {
 funk:[0,3,6,10,12,15],disco:[0,2,4,6,8,10,12,14,15],offbeat:[2,6,10,14],skip:[0,3,6,7,11,14],sparse:[0,7,12],tresillo:[0,6,12],sustain:[0,8],rolling:[0,2,3,6,7,8,10,11,14,15],motor:[0,2,4,6,8,10,12,14],acid:[0,1,3,4,6,7,9,10,12,14,15],psy:[1,2,3,5,6,7,9,10,11,13,14,15],garage:[0,3,7,10,14],wobble:[0,3,6,8,11,14],breaks:[0,3,7,8,11,14],electro:[0,2,5,7,8,10,13,15],reese:[0,6,10],neuro:[0,2,5,6,8,11,13,15],halftime:[0,6,11]
};
const CHORD_RHYTHMS={stab:[0,6,11],chop:[0,3,6,8,11,14],piano:[0,3,6,10,14],sparse:[1],sustain:[0],pulse:[0,2,4,6,8,10,12,14],dub:[2,10],garage:[1,6,11,14],future:[0,3,6,9,12,14]};
const ARP_ORDERS={up:[0,1,2,3],down:[3,2,1,0],updown:[0,1,2,3,2,1],pedal:[0,1,0,2,0,3],fifths:[0,2,1,3,2],euclid:[0,2,1,3,1,2,0],dotted:[0,1,3,2,1],random:[0,3,1,2,3,0,2],sparse:[0,2,3,1],skip:[0,2,1,3,2,0]};
const DRUMS={
 house:[[36,[0,4,8,12]],[38,[4,12]],[42,[0,2,4,6,8,10,12,14]],[46,[2,6,10,14]]],
 disco:[[36,[0,4,8,12]],[39,[4,12]],[42,[0,2,3,4,6,8,10,11,12,14]],[46,[6,14]],[75,[3,10]]],
 minimal:[[36,[0,4,8,12]],[37,[4,12]],[42,[2,5,6,10,13,14]],[76,[3,11]]],
 afro:[[36,[0,4,8,12]],[39,[4,12]],[42,[2,6,10,14]],[64,[0,3,6,10,14]],[63,[2,8,11]],[75,[3,7,11,15]]],
 techno:[[36,[0,4,8,12]],[39,[4,12]],[42,[0,2,4,6,8,10,12,14]],[46,[6,14]],[70,[3,7,11,15]]],
 hard:[[36,[0,4,8,12]],[38,[4,12]],[42,[0,1,2,4,6,7,8,10,12,13,14]],[46,[2,6,10,14]],[45,[3,11,15]]],
 trance:[[36,[0,4,8,12]],[39,[4,12]],[42,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]],[46,[2,6,10,14]]],
 garage:[[36,[0,7,10]],[38,[4,12]],[42,[0,2,3,6,8,10,11,14,15]],[46,[6,14]],[37,[9]]],
 breaks:[[36,[0,6,8,11]],[38,[4,12]],[42,[0,2,3,6,8,10,14,15]],[46,[2,10]],[37,[7,15]]],
 electro:[[36,[0,6,10]],[38,[4,12]],[42,[0,2,4,6,8,10,12,14]],[46,[3,11]],[75,[7,15]]],
 dnb:[[36,[0,6,10]],[38,[4,12]],[42,[0,2,3,6,8,10,11,14]],[46,[2,10]],[37,[7,15]]],
 halftime:[[36,[0,6,11]],[38,[8]],[42,[0,2,4,6,8,10,12,14]],[46,[6,14]],[37,[15]]]
};
const DRUM_NAMES={36:'Kick',37:'Rim',38:'Snare',39:'Clap',42:'Closed hat',45:'Low tom',46:'Open hat',63:'Conga',64:'High conga',70:'Shaker',75:'Claves',76:'Woodblock'};
const PRESETS=GENRES.flatMap((g,gi)=>ROLES.flatMap((role,ri)=>TREATMENTS.map((v,variation)=>({
 id:`${g.id}-${role}-${variation}`,genre:g.id,role,variation,name:`${g.title} / ${v.name}`,
 mood:v.emotion||g.mood,seed:1009+gi*7919+ri*313+variation*97,
 technique:role==='bass'?g.bass:role==='chords'?g.chord:role==='arp'?g.arp:role==='drums'?g.drum:variation===1?'call & response':variation===2?'rising phrase':variation===3?'spacious hook':'motif development'
}))));
const GUIDES_V2=[['groove-cheatsheet.html','Groove','Placement, length & velocity'],['groove-vol2.html','Pattern bank','66 rhythmic building blocks'],['drum-library.html','The kit','Drum sequencing & morphing'],['low-end.html','Low end','Kick, phase & sidechain'],['melody.html','Melody','Rhythm, contour & development'],['chords.html','Voicing','Harmony & voice leading'],['between.html','Between','Make two parts work together'],['arrangement.html','Arc','Arrange beyond the loop'],['buildorder.html','Build order','Choose your next move'],['the-move.html','Transformations','24 ways to develop an idea'],['keyboard.html','Keyboard','Play & practise'],['patch-lab.html','Patch lab','Build the sounds'],['serum-v2.html','Serum 2 V2','48 sound-design recipes'],['sampling.html','The cut','Chop & stretch'],['inkey.html','In key','Transpose with intention'],['disco-house-cheatsheet.html','Disco house','The original quick reference']];
