import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=new URL('./',import.meta.url),read=n=>fs.readFileSync(new URL(n,root),'utf8');
const html=read('../drum-library.html'),js=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(js);
const elements=new Map();
function el(id){if(!elements.has(id))elements.set(id,{value:id==='sort'?'curated':'',disabled:false,innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},querySelectorAll(){return []}});return elements.get(id);}
const ctx={console,Uint8Array,Float32Array,setTimeout,clearTimeout,Math,JSON,localStorage:{getItem:()=>null},document:{getElementById:el,addEventListener(){},querySelector:el,querySelectorAll:()=>[]},window:{addEventListener(){}},navigator:{},location:{hash:''}};
vm.createContext(ctx);vm.runInContext(js.replace(/\ninit\(\);\s*$/,'')+'\nglobalThis.t={LIB,LANES,KITS,KIT_NAMES,TAKES,patternTake,expand,soundQuery,midiBytes,validateSession,session,snapshot,S,morphResult,euclid,filteredLibrary,hitCount};',ctx);
const t=ctx.t;let count=0;function check(name,fn){fn();count++;console.log('PASS '+name);}
check('standalone document, unique IDs and valid section links',()=>{assert(html.startsWith('<!doctype html>'));assert(!/<script[^>]+src=/.test(html));assert(!/fonts.googleapis/.test(html));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const [,id] of html.matchAll(/href="#([^"]+)"/g))assert(ids.includes(id));});
check('48 complete studies with valid two-bar patterns and nine sound kits',()=>{assert.equal(t.LIB.length,48);assert.equal(new Set(t.LIB.map(p=>p.id)).size,48);assert.equal(t.KIT_NAMES.length,9);for(const p of t.LIB){assert(p.d&&p.sig&&p.tags);assert(t.KIT_NAMES.includes(p.kit));assert(p.bpm>=65&&p.bpm<=190);for(const [id,row] of Object.entries(p.p)){assert(t.LANES.some(l=>l.id===id));assert.equal(row.length,32,p.name+' '+id);assert(/^[Xxo-]+$/.test(row));assert(t.soundQuery(p,id).includes(' '));}}});
check('192 distinct pattern/tempo/kit takes; variations never mutate a foundation',()=>{const before=JSON.stringify(t.LIB),all=new Set();for(const p of t.LIB){const own=new Set();for(const take of t.TAKES){const pat=t.patternTake(p,take);assert.equal(Object.keys(pat).length,12);for(const row of Object.values(pat)){assert.equal(row.length,32);assert(row.every(v=>['X','x','o','-'].includes(v)));}own.add(JSON.stringify(pat));all.add(JSON.stringify([pat,p.bpm,p.swing,p.kit]));}assert.equal(own.size,4,p.name+' takes differ');}assert.equal(all.size,192,'all 192 groove settings differ');assert.equal(JSON.stringify(t.LIB),before);});
function parseMidi(bytes){let pos=22,tick=0,notes=[],pending=new Map(),tempo;assert.equal(String.fromCharCode(...bytes.slice(0,4)),'MThd');assert.equal(String.fromCharCode(...bytes.slice(14,18)),'MTrk');assert.equal((bytes[12]<<8)|bytes[13],480);while(pos<bytes.length){let delta=0,b;do{b=bytes[pos++];delta=(delta<<7)|(b&127);}while(b&128);tick+=delta;const status=bytes[pos++];if(status===255){const type=bytes[pos++],len=bytes[pos++];if(type===81)tempo=(bytes[pos]<<16)|(bytes[pos+1]<<8)|bytes[pos+2];pos+=len;if(type===47)break;}else{const note=bytes[pos++],vel=bytes[pos++];assert([0x99,0x89].includes(status));if(status===0x99){assert(vel>0&&vel<=127);pending.set(note,(pending.get(note)||0)+1);notes.push({note,vel,tick});}else{assert(pending.get(note)>0);pending.set(note,pending.get(note)-1);}}}assert.equal(tick,3840);assert([...pending.values()].every(n=>n===0));return {notes,tempo};}
check('all 192 takes export complete, two-bar General MIDI with correct tempos',()=>{for(const p of t.LIB)for(const take of t.TAKES){const state=t.snapshot();state.pat=t.patternTake(p,take);state.bpm=p.bpm;state.swing=p.swing;const {notes,tempo}=parseMidi(t.midiBytes(state));assert.equal(notes.length,Object.values(state.pat).flat().filter(v=>v!=='-').length);assert.equal(tempo,Math.round(60000000/p.bpm));}});
check('MIDI follows mute, solo, swing and level, including silent clips',()=>{const s=t.snapshot();for(const l of t.LANES)s.pat[l.id].fill('-');s.pat.kick[1]='X';s.pat.chh[1]='x';s.swing=60;s.level.chh=50;let m=parseMidi(t.midiBytes(s));assert.equal(m.notes.find(n=>n.note===36).tick,120);assert.equal(m.notes.find(n=>n.note===42).tick,144);assert.equal(m.notes.find(n=>n.note===42).vel,42);s.solo.chh=true;assert.equal(parseMidi(t.midiBytes(s)).notes.length,1);s.mute.chh=true;assert.equal(parseMidi(t.midiBytes(s)).notes.length,0);s.mute.chh=false;s.level.chh=0;assert.equal(parseMidi(t.midiBytes(s)).notes.length,0);});
check('session round-trips preserve edits, with hostile/malformed input rejected',()=>{const source=t.session(),clean=t.validateSession(source);assert.equal(JSON.stringify(clean.pat),JSON.stringify(source.state.pat));clean.pat.kick[0]='-';assert.equal(source.state.pat.kick[0],'X');for(const alter of [x=>x.version=1,x=>x.state.bpm=NaN,x=>x.state.index=-1,x=>x.state.kit='__proto__',x=>x.state.pat.kick=['x'],x=>x.state.level.kick=101,x=>x.state.mute.kick=1,x=>x.state.take='broken',x=>x.state.name='x'.repeat(200)]){const s=structuredClone(source);alter(s);assert.throws(()=>t.validateSession(s));}const injected=structuredClone(source);injected.state.playing=true;injected.state.random='no';const c=t.validateSession(injected);assert(!('playing' in c));assert(!('random' in c));});
check('every morph pair reaches both endpoints and the exact structure boundary',()=>{for(const a of t.LIB)for(const b of t.LIB){const m=t.morphResult(a,b,0),end=t.morphResult(a,b,100);assert.equal(JSON.stringify(m.pat),JSON.stringify(t.expand(a.p)));assert.equal(JSON.stringify(end.pat),JSON.stringify(t.expand(b.p)));assert.equal(end.bpm,b.bpm);assert.equal(end.swing,b.swing);if(m.diff.length){const boundary=t.morphResult(a,b,m.structure/m.diff.length*100);assert.equal(boundary.applied,m.structure);}}});
check('Euclidean rhythms retain exact hit counts for all rotations',()=>{for(let k=1;k<=16;k++)for(let r=0;r<16;r++){const a=t.euclid(k,16,r);assert.equal(a.reduce((x,y)=>x+y,0),k);assert.equal(a.length,16);}});
check('library keyword search and ordering are meaningful',()=>{el('search').value='jungle';assert.equal(t.filteredLibrary().length,1);el('search').value='house warm';assert(t.filteredLibrary().length>0);el('search').value='xyz-no-pattern';assert.equal(t.filteredLibrary().length,0);el('search').value='';el('sort').value='tempo';const a=t.filteredLibrary();assert.equal(a.length,48);assert(a.every((x,i)=>!i||a[i-1].p.bpm<=x.p.bpm));});
console.log(`${count} groups passed. 192 MIDI clips and 2,304 morph pairs checked.`);
